### ISSUE TITLE
Can't get imxg2dvideosink working in Igor's image

### ISSUE THREAD

**Issue by emustafa** [Freescale/gstreamer-imx#100]
Hi,

I am having issue with imxg2dvideosink. The pipeline below does not work for me.

$ sudo gst-launch-1.0 videotestsrc ! imxg2dvideosink
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784349] Internal error: Oops: 5 [#1] SMP ARM

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784501] Process videotestsrc0:s (pid: 1951, stack limit = 0xad24e238)

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784508] Stack: (0xad24fd68 to 0xad250000)

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784517] fd60:                   00000000 00000000 00000001 800fe7a0 00000008 00000000

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784526] fd80: 00000000 00000000 00000000 00000000 0000079e 00000000 0000000e ad174a68

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784536] fda0: 00000000 ad24fe60 ad24fe20 800bbf00 00000001 800f69fc ad094b40 ac396c00

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784545] fdc0: ad0ae900 ad24e020 00007530 ad24e000 00000006 ac0d04d8 6e3ce3f0 804e4b7c

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784554] fde0: 6e3ce438 00000000 000000f8 00000000 6e3ce438 00000000 000000f8 00000000

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784564] fe00: 00000023 00000002 6e3ce840 00000001 76f06000 001b6550 00000002 00000001

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784573] fe20: 00000001 76e88021 001ab2f0 76f06000 80000000 00000000 7682663f 00000000

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784582] fe40: 6dba3000 0001c200 6e3ce840 00000002 6e3ce840 76e88235 76df6c88 fe648600

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784592] fe60: 76935d44 001c3730 76f06000 6e3ce840 001c3730 76f06000 6e3ce840 00000001

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784601] fe80: 00000000 76e673f9 000000f0 00000003 6da2c0fc 6da2c10c 00000000 00000000

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784611] fea0: 76f06000 001ab568 00026230 76f07430 6e3ce530 00000002 76933000 00017700

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784620] fec0: 00000002 6da01424 6e3ce840 6e3ce7d0 001c3730 76906121 00000002 6e3ce538

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784630] fee0: 6e3ce5d4 00000000 76f07218 76e68ce5 00026230 6e3ce7a0 ad1f50c1 ad1f50c0

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784639] ff00: 6e3ce3f0 00007530 00000000 00000006 ac0d04d8 80115a90 aaa14a18 ad174988

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784649] ff20: 80a3b188 00000000 ad174988 00000000 ac07bb50 76935d44 7fffffff 76d7319d

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784658] ff40: 000000f0 00000001 00000000 00000001 76df6ca0 80084cf8 76935d44 00000000

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784667] ff60: ffffffff ad1f50c1 ad1f50c0 6e3ce3f0 00007530 00000000 00000006 00000000

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784677] ff80: 768f2630 80115cbc 001b4420 00002710 7672be80 00007530 00000036 8000e224

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784686] ffa0: ad24e000 8000e0a0 00002710 7672be80 00000006 00007530 6e3ce3f0 001b4420

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784696] ffc0: 00002710 7672be80 00007530 00000036 000000f8 6e3ce748 76f07430 768f2630

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784706] ffe0: 76728100 6e3ce3dc 7670dab0 76c9d206 200f0030 00000006 00000000 00000000

Message from syslogd@localhost at Jun  1 15:25:57 ...
 kernel:[  926.784788] Code: e3042d56 e3442d45 e598c030 e598e038 (e5911000) 

^Chandling interrupt.
Interrupt: Stopping pipeline ...
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...

$ uname -a
Linux cubox-i 3.14.67-cubox #2 SMP Fri Apr 29 03:34:19 CEST 2016 armv7l GNU/Linux

I am using Igor's debian jessie image. imxipuvideosink works fine but I need to get imxg2dimagesink working. Any help is appreciated.

Thanks.

**Comment by dv1** [comment]
Please re-run with the GST_DEBUG environment variable set to "2,*imx*:9". There's not enough information to see what happened inside the GStreamer element.

**Comment by emustafa** [comment]
Here is the output

$ sudo GST_DEBUG=2,*imx*:9 gst-launch-1.0 videotestsrc ! imxg2dvideosink
Setting pipeline to PAUSED ...
0:00:00.118070531 23830  0x17fce00 INFO     imxblittervideosink ../src/blitter/video_sink.c:916:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> opening framebuffer /dev/fb0
0:00:00.118465890 23830  0x17fce00 INFO     imxblittervideosink ../src/blitter/video_sink.c:1205:gst_imx_blitter_video_sink_get_format_from_fb:<imxg2dvideosink0> framebuffer uses 32 bpp (sizes: r 8 g 8 b 8  offsets: r 16 g 8 b 0) => format BGRA
0:00:00.119046594 23830  0x17fce00 INFO     imxblittervideosink ../src/blitter/video_sink.c:1018:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> framebuffer FD is 5
0:00:00.119452619 23830  0x17fce00 INFO     imxphysmemallocator ../src/common/phys_mem_allocator.c:62:gst_imx_phys_mem_allocator_init:<GstImxPhysMemAllocator@0x173d110> initializing physical memory allocator
0:00:00.119893648 23830  0x17fce00 TRACE             imxblitter ../src/blitter/blitter.c:65:gst_imx_blitter_init:<GstImxBlitter@0x180a040> initializing blitter base
0:00:00.120321008 23830  0x17fce00 DEBUG    imxphysmemallocator ../src/common/phys_mem_allocator.c:117:gst_imx_phys_mem_allocator_alloc_internal:<imxg2dallocator0> alloc_internal called: maxsize: 16, align: 0, offset: 0, size: 16
0:00:00.151797016 23830  0x17fce00 INFO         imxg2dallocator ../src/g2d/allocator.c:68:gst_imx_g2d_alloc_phys_mem:<imxg2dallocator0> allocated 16 bytes of physical memory, vaddr 0x76f7c000 paddr 0x3d648000
0:00:00.152333717 23830  0x17fce00 INFO     imxphysmemallocator ../src/common/phys_mem_allocator.c:152:gst_imx_phys_mem_allocator_alloc:<imxg2dallocator0> allocated memory block 0x17fa818 at phys addr 0x3d648000 with 16 bytes
0:00:00.152634069 23830  0x17fce00 LOG            imxg2dblitter ../src/g2d/blitter.c:499:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0> number of planes: 1
0:00:00.152896086 23830  0x17fce00 DEBUG          imxg2dblitter ../src/g2d/blitter.c:532:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0> surface stride: 1920 pixels  width: 1920 pixels height: 1080 pixels
0:00:00.153211440 23830  0x17fce00 DEBUG    imxblittervideosink ../src/blitter/video_sink.c:619:gst_imx_blitter_video_sink_change_state:<imxg2dvideosink0> cleaning up any previous vsync by flipping to page 0
0:00:00.153467456 23830  0x17fce00 LOG      imxblittervideosink ../src/blitter/video_sink.c:1083:gst_imx_blitter_video_sink_select_fb_page:<imxg2dvideosink0> switching to page 0
0:00:00.153835813 23830  0x17fce00 LOG            imxg2dblitter ../src/g2d/blitter.c:499:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0> number of planes: 1
0:00:00.154117831 23830  0x17fce00 DEBUG          imxg2dblitter ../src/g2d/blitter.c:532:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0> surface stride: 1920 pixels  width: 1920 pixels height: 1080 pixels
Pipeline is PREROLLING ...
0:00:00.166199601 23830  0x17fb950 TRACE             imxblitter ../src/blitter/blitter.c:196:gst_imx_blitter_set_input_frame:<imxg2dblitter0> input frame does not use DMA memory - copying input frame to internal frame
0:00:00.166350944 23830  0x17fb950 TRACE             imxblitter ../src/blitter/blitter.c:201:gst_imx_blitter_set_input_frame:<imxg2dblitter0> need to create internal bufferpool
0:00:00.166703633 23830  0x17fb950 INFO    imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:294:gst_imx_phys_mem_buffer_pool_init:<GstImxPhysMemBufferPool@0x6db2c090> initializing physical memory buffer pool
0:00:00.166959983 23830  0x17fb950 INFO    imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:141:gst_imx_phys_mem_buffer_pool_set_config:<imxphysmembufferpool0> caps used for config: video/x-raw, format=(string)I420, width=(int)320, height=(int)240, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, colorimetry=(string)bt601, framerate=(fraction)30/1
0:00:00.167156662 23830  0x17fb950 INFO    imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:151:gst_imx_phys_mem_buffer_pool_set_config:<imxphysmembufferpool0> using horiz/vert alignment: 16/8
0:00:00.167261002 23830  0x17fb950 INFO    imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:174:gst_imx_phys_mem_buffer_pool_set_config:<imxphysmembufferpool0> aligned video info:  width/height: 320/240  padding values right/bottom 0 0
0:00:00.167388344 23830  0x17fb950 TRACE             imxblitter ../src/blitter/blitter.c:233:gst_imx_blitter_set_input_frame:<imxg2dblitter0> acquiring buffer for internal input frame
0:00:00.167489350 23830  0x17fb950 DEBUG    imxphysmemallocator ../src/common/phys_mem_allocator.c:117:gst_imx_phys_mem_allocator_alloc_internal:<imxg2dallocator0> alloc_internal called: maxsize: 115200, align: 0, offset: 0, size: 115200
0:00:00.168622423 23830  0x17fb950 INFO         imxg2dallocator ../src/g2d/allocator.c:68:gst_imx_g2d_alloc_phys_mem:<imxg2dallocator0> allocated 115200 bytes of physical memory, vaddr 0x6d2e3000 paddr 0x3d6c0000
0:00:00.168747097 23830  0x17fb950 INFO     imxphysmemallocator ../src/common/phys_mem_allocator.c:152:gst_imx_phys_mem_allocator_alloc:<imxg2dallocator0> allocated memory block 0x17fa958 at phys addr 0x3d6c0000 with 115200 bytes
0:00:00.168845437 23830  0x17fb950 DEBUG   imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:215:gst_imx_phys_mem_buffer_pool_alloc_buffer:<imxphysmembufferpool0> allocated 115200 bytes for new buffer
0:00:00.169007447 23830  0x17fb950 DEBUG   imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:238:gst_imx_phys_mem_buffer_pool_alloc_buffer:<imxphysmembufferpool0> added video meta with width/height 320/240
0:00:00.169111454 23830  0x17fb950 DEBUG   imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:254:gst_imx_phys_mem_buffer_pool_alloc_buffer:<imxphysmembufferpool0> phys mem meta padding: x/y 0/0 using horiz/vert alignment: 16/8
0:00:00.169234795 23830  0x17fb950 LOG      imxphysmemallocator ../src/common/phys_mem_allocator.c:180:gst_imx_phys_mem_allocator_map:<imxg2dallocator0> mapping 115200 bytes from memory block 0x17fa958 (phys addr 0x3d6c0000), current mapping refcount = 0 -> 1
0:00:00.169356136 23830  0x17fb950 LOG      imxphysmemallocator ../src/common/phys_mem_allocator.c:180:gst_imx_phys_mem_allocator_map:<imxg2dallocator0> mapping 115200 bytes from memory block 0x17fa958 (phys addr 0x3d6c0000), current mapping refcount = 1 -> 2
0:00:00.169468810 23830  0x17fb950 LOG      imxphysmemallocator ../src/common/phys_mem_allocator.c:180:gst_imx_phys_mem_allocator_map:<imxg2dallocator0> mapping 115200 bytes from memory block 0x17fa958 (phys addr 0x3d6c0000), current mapping refcount = 2 -> 3
0:00:00.169877169 23830  0x17fb950 LOG      imxphysmemallocator ../src/common/phys_mem_allocator.c:207:gst_imx_phys_mem_allocator_unmap:<imxg2dallocator0> unmapping memory block 0x17fa958 (phys addr 0x3d6c0000), current mapping refcount = 3 -> 2
0:00:00.170675220 23830  0x17fb950 LOG      imxphysmemallocator ../src/common/phys_mem_allocator.c:207:gst_imx_phys_mem_allocator_unmap:<imxg2dallocator0> unmapping memory block 0x17fa958 (phys addr 0x3d6c0000), current mapping refcount = 2 -> 1
0:00:00.170772893 23830  0x17fb950 LOG      imxphysmemallocator ../src/common/phys_mem_allocator.c:207:gst_imx_phys_mem_allocator_unmap:<imxg2dallocator0> unmapping memory block 0x17fa958 (phys addr 0x3d6c0000), current mapping refcount = 1 -> 0

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661328] Internal error: Oops: 5 [#1] SMP ARM

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661488] Process videotestsrc0:s (pid: 23831, stack limit = 0xacd4a238)

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661495] Stack: (0xacd4bd68 to 0xacd4c000)

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661504] bd60:                   083acf5c 000014d5 00000000 ad3fc800 000014d5 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661514] bd80: 00000000 00000000 00000000 00000000 00005d16 00000178 000004e0 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661523] bda0: 5f1e87ec 00002330 af759c48 8005b51c ad3ebc80 00000000 ad3ebcc8 ac398c00

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661533] bdc0: acae1ec0 acd4a020 00007530 acd4a000 00000006 ac0d04d8 6e41a3f0 804e3fd4

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661542] bde0: 6e41a438 00000000 000000f8 00000000 6e41a438 00000000 000000f8 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661551] be00: 00000023 00000002 76f232ec 76f23498 6db2b290 017f83b8 7681bfec 000000cf

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661560] be20: 00000001 6db06b98 76f23498 6db2b700 80000000 00000000 7687063b 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661569] be40: 6d2e3000 0001c200 76d439f0 00000000 76d43000 00000001 00000000 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661578] be60: 33335b1b a5006d35 76f24e74 00000000 01738e60 00000000 017f8030 7681bfec

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661588] be80: 7681be4c 00000006 00000000 0173d110 6e41a4e8 76eccc1f 000000cf 0173d110

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661597] bea0: 6e41a4e8 00000000 00000000 00026230 6db2b700 7681c1f8 6e41a55c a5bef100

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661607] bec0: 6e41a508 00026230 7681c1f8 6e41a55c a5bef100 000000cf 6e41a748 7686e9c8

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661616] bee0: 7693c630 76ecccd3 000000cf 0173d110 7681c1f8 6e41a55c acf49b41 acf49b40

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661625] bf00: 6e41a3f0 00007530 00000000 00000006 ac0d04d8 801161f0 80a2dc00 80a886e1

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661634] bf20: 8070cca0 80a385d8 00000000 00000000 b332d22a aa832708 00000002 ad068b40

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661643] bf40: 00000118 acd4a018 00000000 ad068b48 7681be4c 801055d4 00000000 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661652] bf60: 00000000 acf49b41 acf49b40 6e41a3f0 00007530 00000000 00000006 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661661] bf80: 7693c630 80116420 017f88e0 00002710 76777e80 00007530 00000036 8000e1c4

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661671] bfa0: acd4a000 8000e040 00002710 76777e80 00000006 00007530 6e41a3f0 017f88e0

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661680] bfc0: 00002710 76777e80 00007530 00000036 000000f8 6e41a748 7686e9c8 7693c630

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661689] bfe0: 76774100 6e41a3dc 76759ab0 76ce7036 20010030 00000006 00000000 00000000

Message from syslogd@localhost at Jun  6 17:15:19 ...
 kernel:[38690.661764] Code: e3042d56 e3442d45 e598c030 e598e038 (e5911000) 
^Chandling interrupt.
Interrupt: Stopping pipeline ...
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...

**Comment by dv1** [comment]
I discussed this with the SolidRun developers. They strongly recommend to not use this image, since many things are broken with it. If you can, retry with one of the SolidRun images.

**Comment by emustafa** [comment]
It works with SolidRun images. I tested. However, I don't have that flexibility to use different image. I need to get this working for the image I am using.

Do you think it is g2d driver that breaks?

**Comment by dv1** [comment]
It is impossible to guess for me. There are many possibilities. I do not know what Igor's image exactly contains. I do strongly suggest that you compare it with a refernce image (like one from SolidRun directly), and check how it runs there.
