### ISSUE TITLE
Noisy green lateral band when using imxipuvideotransform

### ISSUE THREAD

**Issue by giometti** [Freescale/gstreamer-imx#102]
Hello,

I'm using `gstreamer-imx` on my IMX6Q based board running Debian with the following command line:

`gst-launch-1.0 -v filesrc location=pansy-1280x720-565.rgb blocksize=1843200 ! videoparse width=1280 height=720 framerate=5/1 format=29 ! decodebin ! imagefreeze ! imxipuvideotransform ! video/x-raw,format=I420 ! imxvpuenc_mpeg4 ! queue ! rtpmp4vpay ! udpsink host=192.168.32.42 port=5000`

The command takes a static RGB565 image, then calls the `imxipuvideotransform` plugin and sends the result to my host PC over the network where I use the command below to see the image:

`gst-launch-1.0 udpsrc port=5000 caps = "application/x-rtp, media=(string)video,clock-rate=(int)90000, encoding-name=(string)MP4V-ES, profile-level-id=(string)4,config=(string)000001b004000001b59113000001000000012000c888800cd28045a14103, payload=(int)96,ssrc=(uint)3938653480, timestamp-offset=(uint)2667048504, seqnum-offset=(uint)31662" ! rtpmp4vdepay ! avdec_mpeg4 ! autovideosink sync=false`

Everything works well but a noisy green lateral band on the host PC output window! However, if I use the same command as above on my IMX6Q board but replacing the plugin `imxipuvideotransform` with the standard `videoconvert` then the band disappears and the output is perfect.

Any advice in order to fix this issue?

Thanks in advance,

Rodolfo

**Comment by dv1** [comment]
Hm. Can you take a picture that shows this effect? Or make a screenshot? I will try to reproduce it.

**Comment by dv1** [comment]
As described [in this issue](https://github.com/Freescale/gstreamer-imx/issues/99), this seems to be a problem with the IPU's support for I420. I added a workaround to imxv4l2videosrc which enables UYVY support in the video capture. If you can, try with UYVY data instead of I420.
