### ISSUE TITLE
Seeam to be error in  v4l2src.c code

### ISSUE THREAD

**Issue by ezerbib** [Freescale/gstreamer-imx#103]
I think there is a problem at code v4l2src.c:302
```
v4l2src->time_per_frame = gst_util_uint64_scale_int(GST_SECOND,
			v4l2src->fps_d, v4l2src->fps_n);
```
fps_d is denominator
fps_n is numerator

header for the function seam num and denom has been swap 
```
guint64 gst_util_uint64_scale_int (guint64 val,
                           gint num,
                           gint denom);

```

**Comment by sasamy** [comment]
Hello,

time_per_frame = 1 / fps 

therefore I think that there is no error here:

time_per_frame_numerator = fps_denominator
time_per_frame_denominator = fps_numerator

**Comment by dv1** [comment]
Indeed. I added a comment explaining this.
