### ISSUE TITLE
imxg2dvideosink allocation error

### ISSUE THREAD

**Issue by Pehoh** [Freescale/gstreamer-imx#104]
Hello,
I was moving my yocto from fido to jethro, all was working fine with fido, except the VPU (green images) so i decided to move to jethro. With the latest meta-fsl-arm, and latest gstreamer plugins, I got an error when I launch gstreamer:

```
# gst-launch-1.0 imxv4l2videosrc ! imxg2dvideosink
Setting pipeline to PAUSED ... 
g2d_alloc: alloc memory fail with size 16!
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...
```

with more debug :

```
# gst-launch-1.0 imxv4l2videosrc ! imxg2dvideosink
0:00:00.213427667   720  0x10bc480 INFO         imxv4l2videosrc v4l2src.c:452:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps filter (NULL)
0:00:00.214219667   720  0x10bc480 INFO         imxv4l2videosrc v4l2src.c:462:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps video/x-raw, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string)progressive, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:00.215295000   720  0x10bc480 INFO         imxv4l2videosrc v4l2src.c:452:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps filter (NULL)
0:00:00.215888667   720  0x10bc480 INFO         imxv4l2videosrc v4l2src.c:462:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps video/x-raw, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string)progressive, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
Setting pipeline to PAUSED ...
0:00:00.219355667   720  0x10bc480 INFO     imxblittervideosink video_sink.c:917:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> opening framebuffer /dev/fb0
0:00:00.219975667   720  0x10bc480 INFO     imxblittervideosink video_sink.c:1222:gst_imx_blitter_video_sink_get_format_from_fb:<imxg2dvideosink0> framebuffer uses 16 bpp (sizes: r 5 g 6 b 5  offsets: r 11 g 5 b 0) => format RGB16
0:00:00.220878000   720  0x10bc480 INFO     imxblittervideosink video_sink.c:1019:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> framebuffer FD is 5
0:00:00.221592667   720  0x10bc480 INFO     imxphysmemallocator phys_mem_allocator.c:62:gst_imx_phys_mem_allocator_init:<GstImxPhysMemAllocator@0xff7d10> initializing physical memory allocator
0:00:00.222357334   720  0x10bc480 TRACE             imxblitter blitter.c:65:gst_imx_blitter_init:<GstImxBlitter@0x10c0020> initializing blitter base
0:00:00.222964000   720  0x10bc480 DEBUG    imxphysmemallocator phys_mem_allocator.c:117:gst_imx_phys_mem_allocator_alloc_internal:<imxg2dallocator0> alloc_internal called: maxsize: 16, align: 0, offset: 0, size: 16
g2d_alloc: alloc memory fail with size 16!
0:00:00.226715000   720  0x10bc480 ERROR        imxg2dallocator allocator.c:59:gst_imx_g2d_alloc_phys_mem:<imxg2dallocator0> could not allocate 16 bytes of physical memory
0:00:00.227272000   720  0x10bc480 WARN     imxphysmemallocator phys_mem_allocator.c:154:gst_imx_phys_mem_allocator_alloc:<imxg2dallocator0> could not allocate memory block with 16 bytes
0:00:00.227775000   720  0x10bc480 WARN              GST_BUFFER gstbuffer.c:739:gst_buffer_new_allocate: failed to allocate 16 bytes
0:00:00.228318000   720  0x10bc480 ERROR          imxg2dblitter blitter.c:457:gst_imx_g2d_blitter_allocate_internal_fill_frame:<imxg2dblitter0> could not allocate internal fill frame
0:00:00.228965667   720  0x10bc480 ERROR        imxg2dvideosink video_sink.c:84:gst_imx_g2d_video_sink_create_blitter:<imxg2dvideosink0> could not create G2D blitter
0:00:00.229494334   720  0x10bc480 ERROR    imxblittervideosink video_sink.c:1283:gst_imx_blitter_video_sink_acquire_blitter:<imxg2dvideosink0> could not acquire blitter
0:00:00.229970334   720  0x10bc480 ERROR    imxblittervideosink video_sink.c:610:gst_imx_blitter_video_sink_change_state:<imxg2dvideosink0> acquiring blitter failed
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...
```

for information I use a custom v4l2 driver, with BT.1120 support.
Regards,

**Comment by dv1** [comment]
What SoC is this? imx6 soloX? solo? dual? duallite? quad?
Note that not all SoC's have a GPU.

Does this line run?

`GST_DEBUG=2,*imx*:9 gst-launch-1.0 videotestsrc ! imxg2dvideosink`

And what about this one?

`GST_DEBUG=2,*imx*:9 gst-launch-1.0 videotestsrc ! imxipuvideosink`

**Comment by Pehoh** [comment]
It's on iMX6 Duallite, we used to run the pipeline with the fido release.
I'll test the other pipelines as soon as possible (I moved back to fido)

**Comment by sasamy** [comment]
Most likely is necessary to increase a memory reserve for cma, 320M is known what works without problems

# dmesg | grep cma
Reserved memory: initialized node linux,cma, compatible id shared-dma-pool
Memory: 700060K/1048576K available (7395K kernel code, 326K rwdata, 2440K rodata, 312K init, 430K bss, 20836K reserved, **327680K cma-reserved**, 0K highmem)

**Comment by dv1** [comment]
Either that, or there's a mismatch between userspace libraries and kernel drivers. @Pehoh , what device is this? A Sabre board? Something custom?

**Comment by Pehoh** [comment]
@dv1 it is a custom board, with a iMX6 Colibri module by Toradex.
@sasamy This is what I got : cma: CMA: reserved 256 MiB at 1c000000

**Comment by dv1** [comment]
@Pehoh try adding `cma=320M` to the kernel command line. Also, how much RAM does the module have total?

**Comment by Pehoh** [comment]
Sorry for the (very) late answer, I was a bit busy, and we moved back to fido branch. But this problem reappeared on another board.
On the Toradex module, 512MB of RAM, the kernel was 3.14.28, from Toradex's git. it works fine on fido.

On another module, A DART-MX6 from Variscite, 1GB of RAM, kernel 3.14.38 from Variscite's Github, the problem came back on fido branch. 
This is the log : 
```
# GST_DEBUG=2,*imx*:9 gst-launch-1.0 videotestsrc ! imxg2dvideosink
Setting pipeline to PAUSED ...
0:00:00.102220667   426    0xe2c00 INFO     imxblittervideosink video_sink.c:917:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> opening framebuffer /dev/fb0
0:00:00.102470000   426    0xe2c00 INFO     imxblittervideosink video_sink.c:1222:gst_imx_blitter_video_sink_get_format_from_fb:<imxg2dvideosink0> framebuffer uses 16 bpp (sizes: r 5 g 6 b 5  offsets: r 11 g 5 b 0) => format RGB16
0:00:00.102919000   426    0xe2c00 INFO     imxblittervideosink video_sink.c:1019:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> framebuffer FD is 5
0:00:00.103181000   426    0xe2c00 INFO     imxphysmemallocator phys_mem_allocator.c:62:gst_imx_phys_mem_allocator_init:<GstImxPhysMemAllocator@0x20d10> initializing physical memory allocator
0:00:00.103493667   426    0xe2c00 TRACE             imxblitter blitter.c:65:gst_imx_blitter_init:<GstImxBlitter@0xe8000> initializing blitter base
0:00:00.103646000   426    0xe2c00 DEBUG    imxphysmemallocator phys_mem_allocator.c:117:gst_imx_phys_mem_allocator_alloc_internal:<imxg2dallocator0> alloc_internal called: maxsize: 16, align: 0, offset: 0, size: 16
g2d_alloc: alloc memory fail with size 16!
0:00:00.106262667   426    0xe2c00 ERROR        imxg2dallocator allocator.c:59:gst_imx_g2d_alloc_phys_mem:<imxg2dallocator0> could not allocate 16 bytes of physical memory
0:00:00.106365667   426    0xe2c00 WARN     imxphysmemallocator phys_mem_allocator.c:154:gst_imx_phys_mem_allocator_alloc:<imxg2dallocator0> could not allocate memory block with 16 bytes
0:00:00.106443000   426    0xe2c00 WARN              GST_BUFFER gstbuffer.c:739:gst_buffer_new_allocate: failed to allocate 16 bytes
0:00:00.106564667   426    0xe2c00 ERROR          imxg2dblitter blitter.c:457:gst_imx_g2d_blitter_allocate_internal_fill_frame:<imxg2dblitter0> could not allocate internal fill frame
0:00:00.106708667   426    0xe2c00 ERROR        imxg2dvideosink video_sink.c:84:gst_imx_g2d_video_sink_create_blitter:<imxg2dvideosink0> could not create G2D blitter
0:00:00.106784000   426    0xe2c00 ERROR    imxblittervideosink video_sink.c:1283:gst_imx_blitter_video_sink_acquire_blitter:<imxg2dvideosink0> could not acquire blitter
0:00:00.106855667   426    0xe2c00 ERROR    imxblittervideosink video_sink.c:610:gst_imx_blitter_video_sink_change_state:<imxg2dvideosink0> acquiring blitter failed
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...
```

**Comment by accordionman** [comment]
Did anyone solved this problem? I have the same problem using Boundary Nit6Q_I board. The image is built from Yocto Krogoth v.2.1.2 with kernel v. 4.1.15, then we moved to Morty with no improvement. We still get g2d_alloc: alloc memory fail with size ... .For video output imxeglvivsink element is utilized.
Any suggestion?

**Comment by doditaly** [comment]
I have the same problem using Buildroot 2016.05, gst1-imx-0.12.0, kernel 3.10.53.
This is the log for imxg2dvideosink:

`# GST_DEBUG=2,*imx*:9 gst-launch-1.0 videotestsrc ! imxg2dvideosink
Setting pipeline to PAUSED ...
0:00:00.168985667   240   0xeb2ce0 INFO     imxblittervideosink video_sink.c:917:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> opening framebuffer /dev/fb0
0:00:00.169652000   240   0xeb2ce0 INFO     imxblittervideosink video_sink.c:1222:gst_imx_blitter_video_sink_get_format_from_fb:<imxg2dvideosink0> framebuffer uses 16 bpp (sizes: r 5 g 6 b 5  offsets: r 11 g 5 b 0) => format RGB16
0:00:00.170439667   240   0xeb2ce0 INFO     imxblittervideosink video_sink.c:1019:gst_imx_blitter_video_sink_open_framebuffer_device:<imxg2dvideosink0> framebuffer FD is 5
0:00:00.171029667   240   0xeb2ce0 INFO     imxphysmemallocator phys_mem_allocator.c:62:gst_imx_phys_mem_allocator_init:<GstImxPhysMemAllocator@0xe4c2f0> initializing physical memory allocator
0:00:00.171682000   240   0xeb2ce0 TRACE             imxblitter blitter.c:65:gst_imx_blitter_init:<GstImxBlitter@0xeb6000> initializing blitter base
0:00:00.172201333   240   0xeb2ce0 DEBUG    imxphysmemallocator phys_mem_allocator.c:117:gst_imx_phys_mem_allocator_alloc_internal:<imxg2dallocator0> alloc_internal called: maxsize: 16, align: 0, offset: 0, size: 16
g2d_alloc: alloc memory fail with size 16!
0:00:00.181523667   240   0xeb2ce0 ERROR        imxg2dallocator allocator.c:59:gst_imx_g2d_alloc_phys_mem:<imxg2dallocator0> could not allocate 16 bytes of physical memory
0:00:00.182708000   240   0xeb2ce0 WARN     imxphysmemallocator phys_mem_allocator.c:154:gst_imx_phys_mem_allocator_alloc:<imxg2dallocator0> could not allocate memory block with 16 bytes
0:00:00.183831667   240   0xeb2ce0 WARN              GST_BUFFER gstbuffer.c:835:gst_buffer_new_allocate: failed to allocate 16 bytes
0:00:00.184945333   240   0xeb2ce0 ERROR          imxg2dblitter blitter.c:457:gst_imx_g2d_blitter_allocate_internal_fill_frame:<imxg2dblitter0> could not allocate internal fill frame
0:00:00.185521000   240   0xeb2ce0 ERROR        imxg2dvideosink video_sink.c:84:gst_imx_g2d_video_sink_create_blitter:<imxg2dvideosink0> could not create G2D blitter
0:00:00.185916333   240   0xeb2ce0 ERROR    imxblittervideosink video_sink.c:1283:gst_imx_blitter_video_sink_acquire_blitter:<imxg2dvideosink0> could not acquire blitter
0:00:00.186529333   240   0xeb2ce0 ERROR    imxblittervideosink video_sink.c:610:gst_imx_blitter_video_sink_change_state:<imxg2dvideosink0> acquiring blitter failed
ERROR: Pipeline doesn't want to pause.
Setting pipeline to NULL ...
Freeing pipeline ...
`

imxipuvideosink works fine.

**Comment by Pehoh** [comment]
I was able to solve this by updating my kernel to 4.1.15, and my meta to Krogoth. I used the kernel provided by Variscite. I hope this will help.

**Comment by doditaly** [comment]
In my case, using the imx-gpu-viv-5.0.11.p4.5-hfp.bin instead of imx-gpu-viv-5.0.11.p7.4-hfp.bin with kernel 3.10.53 works fine!

**Comment by FarK** [comment]
In my case it is a permissions problem. I have added my non-root user to group `video` and changed permissions of all `mxc` devices:
```
> chown root:video /dev/mxc_*
> chmod 666 /dev/mxc_*
```
