### ISSUE TITLE
error: 'V4L2_PIX_FMT_Y16_BE' undeclared - under Yocto Fido release

### ISSUE THREAD

**Issue by dlarm** [Freescale/gstreamer-imx#105]
Receive a compilation error when trying to compile recent commits. Using a basic bbappend on top of Yocto Fido v1.8 

gstreamer1.0-plugins-imx_0.11.1.bbappend:

DEPENDS_gstreamer1.0-plugins-imx-imxaudio = "virtual/kernel"
DEPENDS_gstreamer1.0-plugins-imx-imxvpu = "virtual/kernel"
DEPENDS_gstreamer1.0-plugins-imx-imxv4l2videosrc = "virtual/kernel"

#Master
#SRCREV = "13038d8323087465ffc01c0e72f8f6dc6aefb43e"
# Breaking Commit 
SRCREV = "e71dc67344ae96fa36e275ff0bb1ad32595b0a60" 
# Latest Working
#SRCREV = "76e9bb6dc6d801e8087dc6eb52f0aac543246890"

Running bitbake gstreamer1.0-plugins-imx:

ERROR: Function failed: do_compile (log file is located at ..//gstreamer1.0-plugins-imx/0.11.1-r0/temp/log.do_compile.2043)
ERROR: Logfile of failure stored in: ..//gstreamer1.0-plugins-imx/0.11.1-r0/temp/log.do_compile.2043
Log data follows:
| DEBUG: Executing shell function do_compile
| Waf: Entering directory `..//gstreamer1.0-plugins-imx/0.11.1-r0/git/build'
| [ 1/70] c: src/common/canvas.c -> build/src/common/canvas.c.1.o
| [ 2/70] c: src/common/fd_object.c -> build/src/common/fd_object.c.1.o
| [ 3/70] c: src/common/phys_mem_allocator.c -> build/src/common/phys_mem_allocator.c.1.o
| [ 4/70] c: src/common/phys_mem_buffer_pool.c -> build/src/common/phys_mem_buffer_pool.c.1.o
| [ 5/70] c: src/common/phys_mem_meta.c -> build/src/common/phys_mem_meta.c.1.o
| [ 6/70] c: src/common/region.c -> build/src/common/region.c.1.o
| [ 7/70] c: src/g2d/allocator.c -> build/src/g2d/allocator.c.1.o
| [ 8/70] c: src/g2d/blitter.c -> build/src/g2d/blitter.c.1.o
| [ 9/70] c: src/g2d/compositor.c -> build/src/g2d/compositor.c.1.o
| [10/70] c: src/g2d/plugin.c -> build/src/g2d/plugin.c.1.o
| [11/70] c: src/g2d/video_sink.c -> build/src/g2d/video_sink.c.1.o
| [12/70] c: src/g2d/video_transform.c -> build/src/g2d/video_transform.c.1.o
| [13/70] c: src/pxp/allocator.c -> build/src/pxp/allocator.c.1.o
| [14/70] c: src/pxp/blitter.c -> build/src/pxp/blitter.c.1.o
| [15/70] c: src/pxp/device.c -> build/src/pxp/device.c.1.o
| [16/70] c: src/pxp/plugin.c -> build/src/pxp/plugin.c.1.o
| [17/70] c: src/pxp/video_sink.c -> build/src/pxp/video_sink.c.1.o
| [18/70] c: src/pxp/video_transform.c -> build/src/pxp/video_transform.c.1.o
| [19/70] c: src/ipu/allocator.c -> build/src/ipu/allocator.c.1.o
| [20/70] c: src/ipu/blitter.c -> build/src/ipu/blitter.c.1.o
| [21/70] c: src/ipu/compositor.c -> build/src/ipu/compositor.c.1.o
| [22/70] c: src/ipu/device.c -> build/src/ipu/device.c.1.o
| [23/70] c: src/ipu/plugin.c -> build/src/ipu/plugin.c.1.o
| [24/70] c: src/ipu/video_sink.c -> build/src/ipu/video_sink.c.1.o
| [25/70] c: src/ipu/video_transform.c -> build/src/ipu/video_transform.c.1.o
| [26/70] c: src/vpu/allocator.c -> build/src/vpu/allocator.c.1.o
| [27/70] c: src/vpu/decoder.c -> build/src/vpu/decoder.c.1.o
| [28/70] c: src/vpu/decoder_context.c -> build/src/vpu/decoder_context.c.1.o
| [29/70] c: src/vpu/decoder_framebuffer_pool.c -> build/src/vpu/decoder_framebuffer_pool.c.1.o
| [30/70] c: src/vpu/device.c -> build/src/vpu/device.c.1.o
| [31/70] c: src/vpu/encoder_base.c -> build/src/vpu/encoder_base.c.1.o
| [32/70] c: src/vpu/encoder_h263.c -> build/src/vpu/encoder_h263.c.1.o
| [33/70] c: src/vpu/encoder_h264.c -> build/src/vpu/encoder_h264.c.1.o
| [34/70] c: src/vpu/encoder_mjpeg.c -> build/src/vpu/encoder_mjpeg.c.1.o
| [35/70] c: src/vpu/encoder_mpeg4.c -> build/src/vpu/encoder_mpeg4.c.1.o
| [36/70] c: src/vpu/framebuffer_array.c -> build/src/vpu/framebuffer_array.c.1.o
| [37/70] c: src/vpu/plugin.c -> build/src/vpu/plugin.c.1.o
| [38/70] c: src/vpu/vpu_framebuffer_meta.c -> build/src/vpu/vpu_framebuffer_meta.c.1.o
| [39/70] c: src/eglvivsink/eglvivsink.c -> build/src/eglvivsink/eglvivsink.c.1.o
| [40/70] c: src/eglvivsink/gl_headers.c -> build/src/eglvivsink/gl_headers.c.1.o
| [41/70] c: src/eglvivsink/gles2_renderer.c -> build/src/eglvivsink/gles2_renderer.c.1.o
| [42/70] c: src/eglvivsink/egl_misc.c -> build/src/eglvivsink/egl_misc.c.1.o
| [43/70] c: src/eglvivsink/plugin.c -> build/src/eglvivsink/plugin.c.1.o
| [44/70] c: src/eglvivsink/egl_platform_fb.c -> build/src/eglvivsink/egl_platform_fb.c.1.o
| [45/70] c: src/v4l2src/v4l2_buffer_pool.c -> build/src/v4l2src/v4l2_buffer_pool.c.1.o
| [46/70] c: src/v4l2src/v4l2src.c -> build/src/v4l2src/v4l2src.c.1.o
| [47/70] c: src/audio/plugin.c -> build/src/audio/plugin.c.1.o
| [48/70] c: src/audio/uniaudio_codec.c -> build/src/audio/uniaudio_codec.c.1.o
| In file included from ../src/v4l2src/v4l2src.c:24:0:
| ..//usr/include/gstreamer-1.0/gst/interfaces/photography.h:28:2: warning: #warning "The GstPhotography interface is unstable API and may change in future." [-Wcpp]
|  #warning "The GstPhotography interface is unstable API and may change in future."
|   ^
| ..//usr/include/gstreamer-1.0/gst/interfaces/photography.h:29:2: warning: #warning "You can define GST_USE_UNSTABLE_API to avoid this warning." [-Wcpp]
|  #warning "You can define GST_USE_UNSTABLE_API to avoid this warning."
|   ^
| ../src/v4l2src/v4l2src.c: In function 'gst_imx_v4l2src_caps_for_current_setup':
| ../src/v4l2src/v4l2src.c:435:8: error: 'V4L2_PIX_FMT_Y16_BE' undeclared (first use in this function)
|    case V4L2_PIX_FMT_Y16_BE:
|         ^
| ../src/v4l2src/v4l2src.c:435:8: note: each undeclared identifier is reported only once for each function it appears in
| Waf: Leaving directory `..//gstreamer1.0-plugins-imx/0.11.1-r0/git/build'
| Build failed
|  -> task in 'gstimxv4l2videosrc' failed (exit status 1):
| 	{task 140667864309008: c v4l2src.c -> v4l2src.c.1.o}
| ['arm-poky-linux-gnueabi-gcc', '-march=armv7-a', '-marm', '-mthumb-interwork', '-mfloat-abi=hard', '-mfpu=neon', '-mtune=cortex-a9', '--sysroot=../', '-Wextra', '-Wall', '-std=gnu99', '-fPIC', '-DPIC', '-O2', '-O2', '-pipe', '-g', '-feliminate-unused-debug-types', '-fPIC', '-pthread', '-pthread', '-pthread', '-pthread', '-pthread', '-Wno-unused-parameter', '-Wno-missing-field-initializers', '-Wno-sign-compare', '-I..//gstreamer1.0-plugins-imx/0.11.1-r0/git/build/src/v4l2src', '-I..//gstreamer1.0-plugins-imx/0.11.1-r0/git/src/v4l2src', '-I..//gstreamer1.0-plugins-imx/0.11.1-r0/git/build', '-I..//gstreamer1.0-plugins-imx/0.11.1-r0/git', '-I..//usr/include/gstreamer-1.0', '-I..//usr/lib/gstreamer-1.0/include', '-I..//usr/include/glib-2.0', '-I..//usr/lib/glib-2.0/include', '../src/v4l2src/v4l2src.c', '-c', '-o', 'src/v4l2src/v4l2src.c.1.o']r0/temp/log.do_compile.2043)

**Comment by dv1** [comment]
Should now be fixed with the latest commit.

**Comment by dlarm** [comment]
Confirmed! Thank you very much.
