### ISSUE TITLE
V4L2_PIX_FMT_XRGB555X undeclared

### ISSUE THREAD

**Issue by DuBistKomisch** [Freescale/gstreamer-imx#107]
Seems to be the same thing as https://github.com/Freescale/gstreamer-imx/issues/105 but a different constant.

Wrapping v4l2src.c:450 with an `#ifdef` resolves the issue.

This is using SolidRun's kernel: https://github.com/SolidRun/linux-fslc

**Comment by dv1** [comment]
Fixed as part of https://github.com/Freescale/gstreamer-imx/pull/106 .

**Comment by DuBistKomisch** [comment]
Haha, perfect, thanks!
