### ISSUE TITLE
imxv4l2src can't use in gstreamer-1.8.2

### ISSUE THREAD

**Issue by hujiqi** [Freescale/gstreamer-imx#113]
run this pipeline: gst-launch-1.0 -v -e imxv4l2src device=/dev/video1 num-buffers=500 ! 'video/x-raw,format=UYVY, width=720, height=576, framerate=5/1'  ! multifilesink location=video%02d.mov
Appear the following questions：
Setting pipeline to PAUSED ...
ERROR: Pipeline doesn't want to pause.
ERROR: from element /GstPipeline:pipeline0/GstImxV4l2VideoSrc:imxv4l2videosrc0: GStreamer error: state change failed and some element failed to post a proper error message with the reason for the failure.
Additional debug info:
gstbasesrc.c(3354): gst_base_src_start (): /GstPipeline:pipeline/GstImxV4l2VideoSrc:imxv4l2videosrc0:
Failed to start
Setting pipeline to NULL ...
Freeing pipeline ...

[debug_info.txt](https://github.com/Freescale/gstreamer-imx/files/446492/debug_info.txt)
)

**Comment by dv1** [comment]
imxv4l2src is an element from the NXP plugins, not from gstreamer-imx.
