### ISSUE TITLE
Eglvivsink does not work with ivi-shell

### ISSUE THREAD

**Issue by sharisan** [Freescale/gstreamer-imx#115]
eglvivsink requires wl_shell which is not provided by ivi-shell. Thus eglvivsink can not be used with ivi-shell

**Comment by dv1** [comment]
I am not familiar with ivi-shell. What would be the quickest way to incorporate it into a Yocto setup?

**Comment by sharisan** [comment]
ivi-shell comes in weston package provided by meta-ivi layer

**Comment by Arunvist** [comment]
We are able to play the video with ivi-shell (using ivi-application interface).
We need to block the wl_shell api calls properly.

**Comment by dv1** [comment]
I now have some time to look at this. Is meta-ivi all I need? Can I use it with any imx6 platform?

**Comment by Arunvist** [comment]
@sharisan can tell you which meta-ivi can be used for this implementation. We are trying to give it as a patch with working changes. Is it possible to review it and take it as a patch?

**Comment by sharisan** [comment]
@dv1  meta-ivi is enough. You can use it with any imx6 platform. Currently i use 10.0 branch of meta-ivi which is compatible with yocto jethro branch.

**Comment by dv1** [comment]
@sharisan Would 11.0 also work? I have been working with krogoth.

**Comment by sharisan** [comment]
@dv1 yes.. it will also work

**Comment by dv1** [comment]
@sharisan , any reason why meta-ivi has its own gstreamer recipes? And is still using 1.2.3?

**Comment by Arunvist** [comment]
@dv1 , i can attach the modified files, but there some build dependency with ilm header files. that @sharisan can provide you for the full build.

**Comment by Arunvist** [comment]
Please find the patch file.

[gst-ivi-support-latest.zip](https://github.com/Freescale/gstreamer-imx/files/578458/gst-ivi-support-latest.zip)

**Comment by dv1** [comment]
Thanks. That patch is substantial though. I'll add it, but not in this release - it will be in the next.

**Comment by Arunvist** [comment]
Thanks very much...

**Comment by Arunvist** [comment]
After applying the patch for eglvivsink compilation wayland ivi extension package config file is hard dependency. We created that file manually as it is missing in the wayland ivi extension package.

Please mention this too. Otherwise they will get compilation isssue.

========
/usr/lib/pkgconfig$ cat ilm.pc 

prefix=/usr
exec_prefix=/usr
libdir=/usr/lib
includedir=/usr/include

Name: Wayland-ivi-extension
Description: interface library layermanager
Version: 1.9.1
Libs: -L${libdir} -lilmClient -lilmCommon -lilmControl -lilmInput
Cflags: -I${includedir}

=========

**Comment by Arunvist** [comment]
**FINAL PATCH**

Issue fix has been added to this patch(error handling).

[0001-GST-Multiple-IVI-surface-handling-v02.zip](https://github.com/Freescale/gstreamer-imx/files/834005/0001-GST-Multiple-IVI-surface-handling-v02.zip)
