### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by RuoZhang** [Freescale/gstreamer-imx#119]
I am now have a gstreamer 1.8.3 installed on imx6 board with several basic plugins.
1. Will this imx plugins run without any problems while using gstreamer 1.8.3.
2. My gstreamer 1.8.3 is installed in the default folder /usr/local not /usr. Therefore, when I install this imx plugins, should I use the same directory as gstreamer 1.8.3 and other plugins?
   (Because it says: './waf install' installs artifacts to its prefix + /lib/gstreamer-1.0 but they need to be installed to /usr/lib/arm-linux-gnueabihf/gstreamer-1.0 which is why we created a symlink above before installing)

Thanks in advance!

**Comment by dv1** [comment]
1. Yes
2. I am confused. "Because it says". "it" = ? In your case, I guess gstreamer-imx plugins should go to /usr/local/lib/gstreamer-1.0/ , since you want to use gstreamer-imx with 1.8.3.

**Comment by il--ya** [comment]
May I ask, why compositor, common and blitter plugins don't go to plugin_install_path (default ${PREFIX}/lib/gstreamer-1.0), whereas everything else does?
Is it intentional behaviour, or just omission?
