### ISSUE TITLE
imxipucompositor does not seem to be alpha blending correctly

### ISSUE THREAD

**Issue by charlie-ht** [Freescale/gstreamer-imx#121]
Hi, it seems like the alpha channel is not being blended into a video stream using the IPU compositor. This is my launch line on my iMX.6 board,

```
GST_DEBUG=1 gst-launch-1.0 -e imxipucompositor name=mix sink_0::xpos=0 sink_0::ypos=0 sink_0::zorder=1 sink_1::xpos=0 sink_1::ypos=0 sink_1::alpha=0.5 sink_1::zorder=2 ! 'video/x-raw,width=800,height=600' ! videoconvert ! imxipuvideotransform ! imxvpuenc_h264 bitrate=400 idr-interval=21 name=enc ! filesink location=test.mp4 \
            imxv4l2videosrc device=/dev/camera imx-capture-mode=3 ! videoconvert ! queue ! mix.sink_0       \
            filesrc location=/tmp/test_alpha.png ! pngdec ! imagefreeze ! queue ! mix.sink_1
```

Here's a screen shot of what I see,

![incorrect_alpha_blending](https://cloud.githubusercontent.com/assets/14251608/19691250/897cfd94-9acb-11e6-861a-0fd4c4198e82.png)

Using an equivalent launch line on my X86 machine,

```
gst-launch-1.0 -e videomixer name=mix sink_0::xpos=0 sink_0::ypos=0 sink_0::zorder=1 sink_1::xpos=0 sink_1::ypos=0 sink_1::alpha=0.5 sink_1::zorder=2 ! 'video/x-raw,width=800,height=600' ! videoconvert ! xvimagesink \
    v4l2src device=/dev/video1 ! videoconvert ! mix.sink_0 \
    filesrc location=/tmp/test_alpha.png ! pngdec ! imagefreeze ! queue ! mix.sink_1
```

I see what  I expect, correct alpha blending,

![correct_alpha_blend](https://cloud.githubusercontent.com/assets/14251608/19691356/de2864e6-9acb-11e6-841c-d7c1e44b0ed3.png)

Unfortunately I haven't been able to test on my iMX.6 the GPU compositor because it's disabled for "reasons".

This is my test file with an alpha channel in case anyone has time to try a test on their setup,

![test_alpha](https://cloud.githubusercontent.com/assets/14251608/19691436/2d111e4a-9acc-11e6-9501-9419df5eb187.png)

TIA,

**Comment by charlie-ht** [comment]
Ah, `gst_imx_ipu_blitter_blit` ignores the alpha parameter. I guess that answers that :)

**Comment by dv1** [comment]
Yes. Alpha blending with the IPU is currently not supported. Unfortunately, only G2D is truly reliable for this task. PxP might in theory be able to do it too, but is not supported on the i.MX6Dual/Quad SoC, and is also difficult to use for general blending.

**Comment by JamesCC** [comment]
I have global alpha blending working in the g2d compositor, but would I be right in thinking that local (pixel level) alpha blending is not supported?  I couldn't get it to work on v0.11.  

I'm looking for a way to pixel level alpha blend a slow rate stream (containing my overlay) with a fast rate one (my video) which is then h264 encoded.  The compositor looked ideal for that.

**Comment by JamesCC** [comment]
Sorry to reply to my own comment - I've got local alpha blending working on the g2d compositor 0.11.1 (and should be true for the current version 0.12.2).

When (g2d) compositing with an alpha of 1.0 the local alpha blending does not apply (it is a straight copy of original source image without using the pixel level alpha channel).  Admittedly that is stated in the README.

What I didn't notice was that with an **alpha of less than 1.0** you do get local (pixel level) alpha blending.  I don't want global alpha blending, so I've chosen 0.99 - which is a good enough solution for now.

I need to experiment further but I see in src/g2d/blitter.c::gst_imx_g2d_blitter_blit() there are some interesting things happening with variable empty_alpha and (I guess the cause of the issue I'm facing) the disabling of G2D_BLEND if variable alpha is 255 (true when alpha of 1.0 is used).  I assume disabling G2D_BLEND improves blit performance, so the general solution is probably not as simple as removing it.

**Comment by dv1** [comment]
Hm. So, for you, the total blending is a combination of global and per-pixel alpha, right? So, like: out_color = pixel_color * pixel_alpha * global_alpha ?

I guess I could make it enable BLEND even if global_alpha is 1.0 if the input data has an alpha channel. That would probably be the best approach.

**Comment by JamesCC** [comment]
Yes it does seem:
`out_color = pixel_color * pixel_alpha * global_alpha`  (if global_alpha is < 1.0)
`out_color = pixel_color `  (if global_alpha is 1.0)

![capture2](https://cloud.githubusercontent.com/assets/5609493/20101313/55c9cda8-a5b9-11e6-8043-a0d328920b4b.png)

The following gst-launch indicates my point:
`gst-launch-1.0 imxg2dcompositor name=d sink_0::zorder=0 sink_1::xpos=300 sink_1::ypos=90 sink_1::zorder=1 sink_1::alpha=0.99 ! autovideosink   videotestsrc pattern=1 ! "video/x-raw,format=BGRA,width=640,height=480,framerate=25/1" ! d.sink_0   videotestsrc pattern=18 foreground-color=0x00fffffff ! "video/x-raw,format=BGRA,width=240,height=240,framerate=25/1" ! d.sink_1`

sink1 has an square image of a black background with a transparent ball (ball's pixels are white with alpha=1.0).

`sink_1::alpha=0.0` - just background (ball and the black background of the ball are fully transparent)
`sink_1::alpha=0.5` - ball is fully transparent and the black(ish) background is 50% transparent
`sink_1::alpha=1.0` - ball is fully white opaque and the background is fully black opaque
`sink_1::alpha=0.99` - ball is fully transparent and the background is fully black opaque (as shown above)

> I guess I could make it enable BLEND even if global_alpha is 1.0 if the input data has an alpha channel. That would probably be the best approach.

Sounds like a good solution.

**Comment by dv1** [comment]
I just pushed an update. In my tests, it worked - a PNG with per-pixel alpha was blended correctly.

**Comment by JamesCC** [comment]
Just noticed this is still open.  It works for me on 0.12.3.
