### ISSUE TITLE
imxg2dcompositor breaking pipe when buffer is not the expected size

### ISSUE THREAD

**Issue by Jtis** [Freescale/gstreamer-imx#126]
Hello,

I have a quick question to you  again.
I am using the compositor to do the following pipeline:
v4l2src - > imxg2dcompositor  -> queue2 -> imxg2dvideosink
The source is coming from a stk1160. And from time to time (I suspect only when switching  stream status ) the stk1160 driver does not send full data (normal behaviour ?). 
On gstreamer side I then got : gst_video_frame_map_id: invalid buffer size 414720 < 829440 . This stream ending then the pipe.
My main problem here is that the pipe crash when I'am using the compositor but not when I only do v4l2src -> imxg2dvideosink.
I then wondering why the compositor do not accept broken frames?  
Do I miss a  configuration somewhere ?

Thanks by advance for you feedback.

Jérôme.

EDIT: I am using fido branch so gstreamer-imx v0.11.1

**Comment by dv1** [comment]
Hi, sorry, I was busy with other projects.

Indeed, the compositor expects complete frames. I recommend you look at the videoparse element. This however assumes that the driver *does* send all the frame data, just not all at once (that is, it sends the first N bytes in one buffer, and the remaining bytes in the next buffer). If instead it *loses* bytes, then you need to somehow detect that and drop these frames. You could do that in a pad probe.

**Comment by Jtis** [comment]
Hello thanks for your feedback.

Indeed this is the workaround I finally ended with : detecting in a pad prob on the v4l2src and dropping the bad frame. It works nice in my case because I haven't much broken frame.

Regards,

Jérôme.
