### ISSUE TITLE
Issue when the element clockoverlay added to the recording pipeline will lead to high cpu usage 

### ISSUE THREAD

**Issue by kasome** [Freescale/gstreamer-imx#128]
Hi,

I try to use gstreamer-imx for recording camera stream, and it works as the following,

gst-launch-1.0 imxv4l2videosrc device=/dev/video0 num-buffers=1800 do-timestamp=true ! video/x-raw,format=I420,width=1280,height=720,framerate=30/1 ! queue ! imxvpuenc_h264 bitrate=5000 gop-size=30 ! queue ! h264parse ! matroskamux ! filesink location=/run/media/mmcblk1p1/output_HD_30_2.mkv sync=false &

with low cpu usage (<8%), but when I add the element **clockoverlay** to the pipeline, e.g.

gst-launch-1.0 imxv4l2videosrc device=/dev/video0 num-buffers=1800 do-timestamp=true ! video/x-raw,format=I420,width=1280,height=720,framerate=30/1 ! queue ! **clockoverlay auto-resize=false time-format="%Y/%m/%d %H:%M:%S"** ! imxvpuenc_h264 bitrate=5000 gop-size=30 ! queue ! h264parse ! matroskamux ! filesink location=/run/media/mmcblk1p1/output_HD_30_2_OSD.mkv sync=false &

then the cpu usage become very high (>30%), 

how to solve this problem ?  any suggestion will be welcome

Best Regards,

Huang

**Comment by dv1** [comment]
The problem I see here is that when you do that, clockoverlay paints the pixels with the CPU. The first pipeline uses CPU-zerocopy, meaning that frame data transfers only occur via DMA. But the second pipeline breaks that. Furthermore, the DMA memory is non-cacheable, so write operations will be slow.

Try this test: make the overlay very small, and see how the CPU usage is then.

The non-cacheable stuff might be solvable with a different physmem allocator arrangement. But CPU based writes will always noticeably increase the CPU usage.

**Comment by bmx666** [comment]
I have same issue, blending 3 lines of static text on 4 PAL cams with i.MX6 Quad cause CPU usage 100% of all cores.
After investigation, I found bottleneck in **gst-plugins-base/ext/pango/gstbasetextoverlay.c** in function
```C
static GstFlowReturn
gst_base_text_overlay_push_frame (GstBaseTextOverlay * overlay,
   GstBuffer * video_frame) {
...
video_frame = gst_buffer_make_writable (video_frame);
...
if (!gst_video_frame_map (&frame, &overlay->info, video_frame,
          GST_MAP_READWRITE))
    goto invalid_frame;
...
gst_video_overlay_composition_blend (overlay->composition, &frame);
...
}
```
I cloned pango plugins into custom imxpango plugins and allocate memory via g2d allocator for rendered text. But I stuck, when trying blend video_frame with rendered text. How to use g2dcompositor for blending?

**Comment by bmx666** [comment]
I finally solve this issue for our team - #147
