### ISSUE TITLE
A complex pipeline causes g2d_alloc: alloc memory fail with size 3686400! 

### ISSUE THREAD

**Issue by accordionman** [Freescale/gstreamer-imx#130]
Hi,
having the following pipeline, after some time of running I get the **g2d_alloc: alloc memory fail with size 3686400 error**. Any suggestion how to solve this? I use the *Nit6Q_I board* and the image is built from *Yocto Morty* with kernel *v. 4.1.15.*

The **pipeline** is:
`export DISPLAY=:0.0`
<pre><code>gst-launch-1.0 \
imxg2dcompositor name=comp sink_0::alpha=1 sink_1::alpha=0.5 ! queue2 ! video/x-raw, width=1280, height=720 ! tee name=te \
	rtspsrc location=rtsp://192.0.0.143/streaming/channels/103 latency=0 ! queue ! rtph264depay ! decodebin ! imxipuvideotransform ! comp.sink_0 \
	videotestsrc pattern=18 ! "video/x-raw,width=1280,height=720, framerate=5/1" ! queue ! comp.sink_1 \
	te. ! queue ! imxeglvivsink \
	te. ! queue  ! imxipuvideotransform ! imxvpuenc_h264 ! h264parse ! splitmuxsink location="/mnt/hdd/highres_%02d.mp4" max-size-time=10000000000 async-handling=1 message-forward=1 
	te. ! queue ! imxipuvideotransform ! "video/x-raw,width=640,height=360" ! queue ! imxvpuenc_h264 ! h264parse ! splitmuxsink location="/mnt/hdd/lowres_%02d.mp4" max-size-time=10000000000 async-handling=1 message-forward=1</code></pre>

**Comment by sasamy** [comment]
Hello,
g2d_alloc has the 32MB limit

https://community.nxp.com/thread/380975#comment-593511

and in accordance with the documentation "i.MX 6 Graphics User’s Guide" the size can be changed

> 
> 9.2 GPU memory pools
> Reserved memory
> In the Linux 3.10.y kernel, the memory is reserved from CMA implemented in the GPU kernel driver, the size can be changed through U-Boot args with “galcore.contiguoussize =xxx”

**Comment by accordionman** [comment]
I already tried that. I thought it was 320MB and I have enlarged it up to 420MB, see dmesg output:
<pre><code>
[    0.000000] cma: early_cma(420M)
[    0.000000] Reserved memory: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] cma: dma_contiguous_reserve(limit ffffffff)
[    0.000000] Kernel command line: cma=420M mxc_hdmi.only_cea=1 console=ttymxc1,115200 vmalloc=400M consoleblank=0 rootwait fixrtc root=/dev/mmcblk0p2 wlcore.mac=00:19:b8:81:a1:5f
[    0.000000] Memory: 696504K/1048576K available (9220K kernel code, 554K rwdata, 2632K rodata, 1024K init, 454K bss, 24392K reserved, 327680K cma-reserved, 0K highmem)
</code></pre>
However, the problem still lasts...

**Comment by sasamy** [comment]
Hi,
galcore uses CMA - this is true, but galcore also has its own limits, on newer versions of the driver, the parameter has a slightly different name.

Galcore version 5.0.11.41671 (kernel version 4.1.15)

cat /sys/module/galcore/parameters/contiguousSize
134217728

134217728 = 128 * 1024 * 1024 = 128M

Please try to increase this limit:

dynamic kernel module:

```
# rmmod galcore
# modprobe galcore contiguousSize=201326592
```

statically-linked driver:

galcore.contiguousSize=201326592

not sure that it works, but you can try through sysfs:

`echo '201326592' >  /sys/module/galcore/parameters/contiguousSize`

201326592 = 192 * 1024 *1024

**Comment by accordionman** [comment]
Hi, according to your suggestions, I set up the UBoot parameter. There is dmesg output:
<pre><code>
[    0.000000] cma: early_cma(420M)
[    0.000000] Reserved memory: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] cma: dma_contiguous_reserve(limit ffffffff)
[    0.000000] Kernel command line: cma=420M galcore.contiguousSize=201326592 mxc_hdmi.only_cea=1 console=ttymxc1,115200 vmalloc=400M consoleblank=0 rootwait fixrtc root=/dev/mmcblk0p2
[    0.000000] Memory: 696504K/1048576K available (9220K kernel code, 554K rwdata, 2632K rodata, 1024K init, 454K bss, 24392K reserved, 327680K cma-reserved, 0K highmem)
</code></pre>
The output of 
<pre><code>cat /sys/module/galcore/parameters/contiguousSize</code></pre>
is 
<pre><code>201326592</code></pre>
but the problem still appears...

**Comment by accordionman** [comment]
Recently I found out that the problem occurs with both compositor and video recording branches. When there is only one of these critical sections, the problem disappears.

**Comment by accordionman** [comment]
I finally found out that for some reason I'm not able to use both imx...compositor and imx...transform element in a branch after tee. When I tried to use only one of these crucial elements there was no g2d_alloc error. I have to find another solution for substitution of the compositor element.
