### ISSUE TITLE
OV5647 image/jpeg (MJPEG) support for imxv4l2videosrc 

### ISSUE THREAD

**Issue by Skryabin** [Freescale/gstreamer-imx#131]
Hello,

Would it be possible to add support for V4L2_PIX_FMT_JPEG to imxv4l2videosrc ? I am using the RaspiCam (OV5647) on the HummingBoard Pro, and I would like to take advantage of the built-in MJPEG compression. 

Many thanks,

Alexandre

PS. Kernel used is SolidRun's official 3.14.60-fslc-imx6-sr.

**Comment by dv1** [comment]
Hmm perhaps. I need to get an OV5647 though. I'll update this issue when I have such a cam.

**Comment by Skryabin** [comment]
I have a few... Would you like me to send you one?

**Comment by dv1** [comment]
Thanks! Hmm perhaps. I might be able to get one here, but if not, I'll get back on your offer.

**Comment by Skryabin** [comment]
Great ! Don't hesitate.

Cheers,

Alexandre


Alexandre Vovan



Enseignant - Techniques de l'informatique
Informatique de gestion | 
Développement d'applications Web et mobiles


Cégep de Sorel-Tracy
3000, boulevard de Tracy 
Sorel-Tracy (Québec)  J3R 5B9 

(450) 742-6651, poste 4104
alexandre.vovan@cegepst.qc.ca


Avant l'impression, il faut penser à  l'Environnement.
>>> dv1 <notifications@github.com> 02/28/17 5:45 PM >>>
Thanks! Hmm perhaps. I might be able to get one here, but if not, I'll get back on your offer.
 —
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
     
NaN.
