### ISSUE TITLE
Gstreamer support auto adjust brightness for OV5640 camera

### ISSUE THREAD

**Issue by thanhnhiel** [Freescale/gstreamer-imx#132]
Hello,

Will Gstreamer be support auto adjust brightness under low light conditions when construct a streaming form OV5640 camera? I want process balancing color at streamer on imx6.
Is is possible processing on the imx6 chip?
I only found color balance operation on xvimagesink, colorbalance element which is used for player (client).

Thank you.

Best regards,
Nhi.Tran

**Comment by dv1** [comment]
Sorry about not reacting, I can't do much at the moment - I'll be able to do more next week. As for your question, I unfortunately do not know. This involves the ov5640 driver, which I think is pretty basic, and the imxv4l2videosrc element is largely not written by me (it was donated to the project & got patched by many other people).

**Comment by thanhnhiel** [comment]
Hi dv1,

Thank you for your answer.

Best regards,
Nhi.Tran
