### ISSUE TITLE
imxg2dcompositor prevents seeking in pipeline

### ISSUE THREAD

**Issue by pylorak** [Freescale/gstreamer-imx#133]
I have a gst command line like the following:
```
./basic-player $FLAGS -p \
    "filesrc location=\"${AVI}\" ! avidemux name=demux ! jpegdec ! video/x-raw,framerate=25/1 ! queue ! imxipuvideotransform ! \
     video/x-raw,format=I420 ! imxg2dvideosink name=\"video-sink\" window-x-coord=0 window-y-coord=35 window-width=438 window-height=248 framebuffer=\"/dev/fb0\""
```

"basic-player" above does only little more than constructing and executing the pipeline given in its -p argument. It listens on dbus, and controls the pipeline based on the messages it gets, allowing to pause, continue, and seek the video. And it works perfectly...

... until imxg2dcompositor gets added to the pipeline. The following pipeline, for example, does not seek any more:

```
./basic-player $FLAGS -p \
    "filesrc location=\"${AVI}\" ! avidemux name=demux ! jpegdec ! video/x-raw,framerate=25/1 ! queue ! imxipuvideotransform ! \
    video/x-raw,format=I420 ! imxg2dcompositor ! imxg2dvideosink name=\"video-sink\" window-x-coord=0 window-y-coord=35 window-width=438 window-height=248 framebuffer=\"/dev/fb0\""
```
I simply added an instance of imxg2dcompositor to the first pipeline. I know the imxg2dcompositor here is very useless, it just shows what the minimal addition is to make seek stop working. I can construct usefull pipelines with imxg2dcompositor using multiple image sources and alpha transparency, and all display great, but seeking works in none of them.

**Comment by pylorak** [comment]
Using GStreamer 1.10.2 on an iMX 6QP.

**Comment by dv1** [comment]
Interesting, I have not yet discovered why seeking fails. Somehow I missed this...
Here's another way to test it: run `gst-play-1.0 --videosink "imxg2dcompositor ! imxg2dvideosink" <video file>` and press the arrow keys. Will post updates when I have some.
