### ISSUE TITLE
imxvpudec  

### ISSUE THREAD

**Issue by avazquezdev** [Freescale/gstreamer-imx#138]
Hi All.
I am compiling gstreamer-imx and I just found that the imxvpudec plugin does not work.
I have a jpeg streaming which I can see without problems if I don't use HW acceleration.
_gst-launch-1.0 souphttpsrc is-live=TRUE location=http://192.168.0.156:8080/video ! jpegdec  ! imxipuvideosink_
When I use HW acceleration, the image never be displayed.
_gst-launch-1.0 souphttpsrc is-live=TRUE location=http://192.168.0.156:8080/video ! multipartdemux ! imxvpudec ! imxipuvideosink_
The trace of information:

[outGstreamer.txt](https://github.com/Freescale/gstreamer-imx/files/771723/outGstreamer.txt)

I have inspected this item (imxvpudec) with gst-inspect and I have found that the pads are empty.

[outGstinpect.txt](https://github.com/Freescale/gstreamer-imx/files/771736/outGstinpect.txt)

I am not sure if it is a plugin error or that the HW decoding libraries are not compiling well.
Do you have any idea what may be happening?

Version Libs
Gstreamer-1.11.1
Gstreamer-good-1.24
imx-vpu-5.4.33
libimxvpuapi-0.10.3
gstreamer-imx-0.12.3

Thanks!
Regards!

**Comment by avazquezdev** [comment]
Solve. I changed the Gstreame version and I updated the vpu firmware and now work!
Thanks!

**Comment by DavidIngraham** [comment]
Hello @avazquezdev,
I am having the same problem. What version of the VPU firmware worked for you?
-David

**Comment by avazquezdev** [comment]
Hi! @DavidIngraham 
I use imx-vpu 5.4.33 and libimxvpuapi 0.10.3
