### ISSUE TITLE
Bad file descriptor in imxv4lbufferpool

### ISSUE THREAD

**Issue by rolox** [Freescale/gstreamer-imx#14]
While Streming a video from the imxv4l source I get a bad file descriptor error from within the source filter every few minutes. Restaring the pipeline solves the problem.

Before I had a similar issue with the gstreamer 0.10 version that happend because the freescale v4l source was not thread safe around their implementation of some kind of bad designed buffer pool implementation. After fixing this it worked perfectly.
The curent problem "smells" similar.

Output from log shows:

0:00:02.192587667  6706   0x16dfc0 ERROR      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:317:gst_imx_v4l2_buffer_pool_stop:<imxv4l2bufferpool0> VIDIOC_STREAMOFF error: Bad file descriptor
0:00:02.192919667  6706   0x16dfc0 ERROR      imxv4l2bufferpool ../src/v4l2src/v4l2_buffer_pool.c:317:gst_imx_v4l2_buffer_pool_stop:<imxv4l2bufferpool0> VIDIOC_STREAMOFF error: Bad file descriptor
Cleanup ...

**Comment by dv1** [comment]
imxv4l2videosrc has been patched considerably since this was reported, and it was never observed again. Closing. If it reappears, please open a new issue.
