### ISSUE TITLE
Qt5 QML Video sink

### ISSUE THREAD

**Issue by dmitry-pozhidaev** [Freescale/gstreamer-imx#143]
So as I seen GStreamer 1.0 QML GL sink support is horrible. No native build on Buildroot. Only by hand. But it is hard work.
May be someone begin write Freescale QML GL video sink here?
Qt5 framework grow very fast and many folks will glad use IMX6 GStreamer plugin under Qt5 .

**Comment by otavio** [comment]
We have been using Qt Multimedia with good success in some customers. A more GStreamer-pure support would be indeed good as it would allow for finer control but in general Qt Multimedia does work.

**Comment by dmitry-pozhidaev** [comment]
There is simple method use of QML VideoOutput with custom RTP bin? How make join custom rtp stream and QML Item over QtMultimedia?
