### ISSUE TITLE
Why imxg2dvideotransform have no property "output-rotation"?

### ISSUE THREAD

**Issue by dmitry-pozhidaev** [Freescale/gstreamer-imx#144]
Hi
Why imxg2dvideotransform have no property "output-rotation"?
I want show camera view. It must be mirrored. I use Qt5 and QML. So I can do the mirror view at qml. 
An element imxg2dvideotransform work as color space transphormer from the camera to QQuick Item. Only this. If pluging be able make and rotate too it will nice, I think.
So may be add to imxg2dvideotransform ability make it?

Best regards!

**Comment by thsle** [comment]
Hi,

I am new using these gstreamer-imx plugins and i was also surprised not finding any rotation property for imxg2dvideotransform, as well as for imxipuvideotransform or imxpxpvideotransform. Indeed, reading the readme, this feature seems to be enabled for *videocompositor elements (inherited from blitter if i well understand what is under the hood). Any reason for not allowing rotation transforms from *videotransform elements?

To avoid "why not using the compositor" answer, let me precise that I am serving over network a camera device that includes a mirror in the optical sensing so the video needs to be flipped horizontally (note that as we have many different video clients it is not acceptable to assume the flip to be done on the client side).

Best regards,

**Comment by dv1** [comment]
Hmm this may just have been an oversight. I currently see no reason why there shouldn't be such a property.

**Comment by JamesCC** [comment]
(just a "up vote")

I'm keen for this feature too.  We want to be able to rotate during playback, and we are going to several destinations so it would be handy to do this in one place (rather than all the sinks).  We are already using the transform for "zoom" and "pan" (i.e. crop and scale).

I too would prefer not to use the compositor as it affects seek during playback (or at least 0.11.1 did).

**Comment by javiervalcarce** [comment]
Hi. I would like to up vote this too. 

I need to both rotate AND flip. My application needs to visualize ip cameras, some of them are retroview cameras and hence must be mirrored or not depending on the direction of movement.

**Comment by thsle** [comment]
Hi all,
Thanks @JamesCC and @javiervalcarce for voting up.
@dv1, I understand from your point that adding a property is possible but do you mean that the backend is already able to "on-the-fly" mirror or rotate? If so, can anyone point out the corresponding sources so I could have an idea of what have to be done?
Regards,

**Comment by dv1** [comment]
Finally I had some time to add this! Better late than never :) Please let me know how it works for you.

**Comment by thsle** [comment]
Hi, thanks @dv1, good news! My platforms are running gstreamer-imx 0.12.3. I hope to find time to update one with the latest commit and test within the next weeks. I'll let you know then in case of issue.
