### ISSUE TITLE
Can we use application created wayland window handle in imx eglvivsink to render the video instead creating its by own?

### ISSUE THREAD

**Issue by Arunvist** [Freescale/gstreamer-imx#145]
Hello,

Currently we are not passing any window handle to eglvivsink, so eglvivsink will create the wayland window.

If we keep on skip the video to play next video let say 10 to 20 times in a second, then memory leak is happening and system get restarted.

"imxc_vpu 2040000.vpu_fsl: Physical memory allocation error!" 

gst_imx_egl_viv_sink_egl_platform_init_window is called with window_handle, but inside that still this function creates its own window. is that the intentional? or we cant pass the window handle created by application.
[gst_appication_log.txt](https://github.com/Freescale/gstreamer-imx/files/860517/gst_appication_log.txt)

Can you please suggest or clarify and please find the attached logs for the memory leak issue.

Thanks,
Arun

**Comment by AstroJimX** [comment]
Hello, I am trying to do the same but haven't been successful. I noticed that gst_imx_egl_viv_sink_egl_platform_init_window() takes window_handle as a parameter but does not use it, explaining why the imxeglvivsink is unable to render video inside a wayland-based user window.
