### ISSUE TITLE
Is there an imx zero copy videorate equivalent

### ISSUE THREAD

**Issue by james-huang** [Freescale/gstreamer-imx#146]
I'm trying to change my frame rates, but it seems like imxipuvideotransform and imxg2dvideotransform do not have that functionality? Or am I doing something wrong here:

`gst-launch-1.0 imxv4l2videosrc device=/dev/video0 ! "video/x-raw,width=640,height=480,framerate=30/1" ! imxipuvideotransform ! "video/x-raw,width=320,height=240,framerate=10/1" ! fakesink
`

If I take out `framerate=10/1` everything works fine.

**Comment by bmx666** [comment]
You must use "fps-n" prop in *imxv4l2videosrc*

**Comment by james-huang** [comment]
thanks!
