### ISSUE TITLE
imxvpuenc_h264 fails from time to time: failed to encode frame: failure timeout

### ISSUE THREAD

**Issue by rolox** [Freescale/gstreamer-imx#15]
While encoding a video (SD TV 25 Hz) I get a timeout from time to time (maybe 5 minutes or less).

As far as I could follow  the error comes from within the vpuwrapper library V 1.0.46 . I tried to increase the timeout parameters within the vpu rapper library , but this did not solve the problem.
With the gstreamer 0.10 implementation I had not such a problem!

0:00:14.447259335 14263 0x2bd59980 ERROR          imxvpubaseenc ../src/vpu/encoder/base_enc.c:784:gst_imx_vpu_base_enc_handle_frame:<vpuh264enc> failed to encode frame: failure timeout
While encoding a video (SD TV 25 Hz) I get a timeout from time to time (maybe 5 minutes or less).

As far as I could follow  the error comes from within the vpuwrapper library V 1.0.46 . I tried to increase the timeout parameters within the vpu rapper library , but this did not solve the problem.
With the gstreamer 0.10 implementation I had not such a problem!

0:00:14.447259335 14263 0x2bd59980 ERROR          imxvpubaseenc ../src/vpu/encoder/base_enc.c:784:gst_imx_vpu_base_enc_handle_frame:<vpuh264enc> failed to encode frame: failure timeout

**Comment by Gateworks** [comment]
I'm encountering the VPU blocking issue on a IMX6Q (64bit DDR3) with the simple pipeline of:
gst-launch-1.0 videotestsrc ! imxvpuenc_h264 ! fakesink

It seems that the more loading you have on the MMDC the quicker you will see the issue (even though mmdc2 shows that I'm not that heavily loaded). With mmc2 reporting no load prior to the pipeline it will occur within a minute or so.

If you have enabled 1080p@60Hz HDMI output (placing a load on IPU) (ie video=mxcfb0:dev=hdmi,bpp=32,1920x1080M@60,if=RGB24) you will see it very quickly (within a minute). Blank the display (echo 1 > /sys/class/graphics/fb0/blank) to eliminate the IPU burden and it again takes a minute or so to recreate.

Can anyone else confirm they are seeing this?

Here are the versions of what I'm using:
flsc-3.14 kernel
firmware-imx-vpu-imx6q - 1:3.14.28-1.0.0-r0
gstreamer1.0-plugins-imx - 0.11.1+0+606a077c3d-r0
gstreamer1.0 - 1.4.5-r0
libfslvpuwrap3 - 1.0.58-r0
libvpu4 - 1:5.4.28-r0
libfslcodec-mp3 - 4.0.3-r0
libfslvpuwrap3 - 1.0.58-r0

Any ideas?

**Comment by Gateworks** [comment]
This is resolved in the 5.4.31 imx-vpu lib. Freescale has this as ENGR00231107: https://github.com/rabeeh/android-imx6-kitkat/blob/master/platform/external/linux-lib.git/0219-ENGR00231107-VPU-lib-workaround-for-VPU-BWB-blocking.patch#L41

**Comment by dv1** [comment]
Closing this. Two main causes have been identified: older imx-vpu versions can cause this, and so can overclocked VPU cores. Neither of these involve gstreamer-imx.
