### ISSUE TITLE
RTSP streaming slow

### ISSUE THREAD

**Issue by avazquezdev** [Freescale/gstreamer-imx#150]
Hi, All.
I have an ip camera that I access through rtsp and h264. My problem is that the image display is very slow.
The probemas are as follows:
-IDMAC21's EBA0 is not 8-byte aligned
-A lot of buffers are being dropped.
-There may be a timestamping problem, or this computer is too slow.

I don't know if I have the pipeline correctly configured or I need to use some additional options to play correctly. I have tried using the libav plugin and the video plays correctly but I would like to use gstreamer-imx.

gst-launch-1.0  rtspsrc latency=200 location=rtsp://192.168.0.243 ! rtph264depay !  h264parse ! imxvpudec ! imxipuvideosink

Setting pipeline to PAUSED ...
Pipeline is live and does not need PREROLL ...
Progress: (open) Opening Stream
Progress: (connect) Connecting to rtsp://192.168.0.243
Progress: (open) Retrieving server options
Progress: (open) Retrieving media info
Progress: (request) SETUP stream 0
Progress: (request) SETUP stream 1
Progress: (open) Opened Stream
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Progress: (request) Sending PLAY request
Progress: (request) Sending PLAY request
Progress: (request) Sent PLAY request
[INFO]  bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
[WARN]  VPU iram is less than needed, some parts don't use iram
imx-ipuv3 2400000.ipu: IDMAC21's EBA0 is not 8-byte aligned
WARNING: from element /GstPipelinimx-ipuv3 2400000.ipu: **IDMAC21's EBA0 is not 8-byte aligned**
e:pipeline0/GstImxIpuVideoSink:imxipuvideosink0: **A lot of buffers are being dropped.**
Additional debug info:
gstbasesink.c(2854): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstImxIpuVideoSink:imxipuvideosink0:
**There may be a timestamping problem, or this computer is too slow.**
WARNING: from element /GstPipelinimx-ipuv3 2400000.ipu: IDMAC21's EBA0 is not 8-byte aligned
e:pipeline0/GstImxIpuVideoSink:imxipuvideosink0: A lot of buffers are being dropped.
Additional debug info:
gstbasesink.c(2854): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstImxIpuVideoSink:imxipuvideosink0:
There may be a timestamping problem, or this computer is too slow.
WARNING: from element /GstPipelinimx-ipuv3 2400000.ipu: IDMAC21's EBA0 is not 8-byte aligned
e:pipeline0/GstImxIpuVideoSink:imxipuvideosink0: A lot of buffers are being dropped.
Additional debug info:
gstbasesink.c(2854): gst_base_sink_is_too_late (): /GstPipeline:pipeline0/GstImxIpuVideoSink:imxipuvideosink0:
There may be a timestamping problem, or this computer is too slow.
handling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:04.646373333
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

Thanks!
Regards!

**Comment by Pehoh** [comment]
Hello!
You can try to add some queues to your pipeline, and use imxg2dvideosink if you can.
I hope this can help you,
Regards, 
Pierre-Olivier.

**Comment by avazquezdev** [comment]
Hi, Pierre-Olivier.
I used imxg2dvideosink and I have the same problem. I have also tried to use queues and the problem continues.
If I increase the latency to 500ms it works but the delay is appreciated.
I believe that the problem is in imxvpudec because if I use avdec_h264 and I don't have this problem.
Can you think of anything else you can do to try?
Thanks!
Regards!
