### ISSUE TITLE
imxipuvideosink sink selection

### ISSUE THREAD

**Issue by md-jamal** [Freescale/gstreamer-imx#156]
Hi,

If I have two displays connected one over the HDMI interface and the other over LVDS.

How can I select the display device in imxipuvideosink

In the gstreamer-0.10 i was using the following command:

gst-launch playbin2 uri=file:///mnt/usb/Trailer1.mp4 flags=0x57 video-sink="imxv4l2sink device=/dev/video17" To play on HDMI 

gst-launch playbin2 uri=file:///mnt/usb/Trailer1.mp4 flags=0x57 video-sink="imxv4l2sink device=/dev/video18" To Play on LVDS.

I don't see the device property in imxipuvideosink to select between displays...

**Comment by Pehoh** [comment]
Hello,
On imxipvideosink there is the framebuffer property:
```
 framebuffer         : The device name of the framebuffer to render to
                        flags: readable, writable
                        String. Default: "/dev/fb0"
```
For example on my iMX6, /dev/fb0 and /dev/fb1 are for HDMI (foreground and background).  Framebuffers are set in U-Boot.

**Comment by md-jamal** [comment]
In the above scenario, I can do only one task at a time
Consider a scenario where I want to play two videos at the same time....

**Comment by dv1** [comment]
It is not clear what you want. I am guessing that you want to play 2 videos simultaneously *and* also want to be able to select which video stream goes to what screen. Is this correct?
