### ISSUE TITLE
Issue when using gstreamer-imx to record 5 camera stream simultaneously

### ISSUE THREAD

**Issue by kasome** [Freescale/gstreamer-imx#157]
Hi,

I try to use gstreamer-imx to record 5 camera stream simultaneously, as the following

                       FPS            Resolution          EncodingBitrate
camera0          30              1280x720                   5M
camera1          30             720x480                      2M
camera2          30             720x480                      2M
camera3          30             720x480 		            2M
camera4          30             720x480                      2M

But when I start recording, it keeps showing the message like

tw6869 0000:01:00.0: tw6869_dma_reset: DMA 0
tw6869 0000:01:00.0: tw6869_dma_reset: DMA 1
tw6869 0000:01:00.0: tw6869_dma_reset: DMA 2
tw6869 0000:01:00.0: tw6869_dma_reset: DMA 3

after a while, and finally the following message show up, then from camera1 to camera4 recording are all stop, only camera0 still running

tw6869 0000:01:00.0: tw6869_dma_reset: DMA 0: forced OFF
tw6869 0000:01:00.0: tw6869_dma_reset: DMA 1: forced OFF
tw6869 0000:01:00.0: tw6869_dma_reset: DMA 2: forced OFF
tw6869 0000:01:00.0: tw6869_dma_reset: DMA 3: forced OFF

I use linux kernel version imx6qsabresd 3.14.52-1.1.1, and the camera drvier for camera1 to camera4 come from here

https://github.com/sasamy/tw6869

Is there any performance issue when recording 5 camera simultaneously by using use gstreamer-imx?  any suggestion will be welcome

Best Regards,

Huang

**Comment by Gateworks** [comment]
Huang,

We use the avc8000nano on our IMX6 based boards with a slighly different tw6869 driver. I doube your issue is a performance one, most likely a driver issue:
 - wiki: http://trac.gateworks.com/wiki/minipciexpressmodules/avc8000nano
 - driver in 3.14 kernel: https://github.com/Gateworks/linux-imx6/tree/gateworks_fslc_3.14_1.0.x_ga/drivers/media/pci/tw6869
 - patch to gstreamer-imx for DMA buffers: https://github.com/Gateworks/meta-gateworks/blob/pyro/recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx/0001-imxv4l2videosrc-v4l2_buffer_pool-Add-special-case-fo.patch

Regards,

Tim

**Comment by bmx666** [comment]
In project we use 4 PAL cameras + tw6869 + gstreamer-imx + 2xSD-card. Boundary Yocto Morty + Boundary Kernel 4.1.15 (kernel already include tw6869 driver from [here](https://github.com/sasamy/tw6869/tree/linux-4.x))

4 pipelines in parallel:
v4l2src /dev/videoN -> iputransform (interlacing) -> 3 x textoverlay -> iputransform (convert colorspace RGB -> NV12) -> tee -> 1,2,3,4
1. -> queue -> h264enc -> file
2. -> queue -> mjpegenc -> file
3. -> queue -> g2d screen
4. -> queue -> rtp

Our team faced with the following problems:
1. Recording on SD-cards was very bad idea. For bitrate 2Mbps+ performance decreasing after 5-10 min on FAT, ext4fs without journal - 30min, btrfs - 1hour. We tuned many params of filesystems, I/O scheduling, multithreading, disk caching. Still very poor performance on SD-cards
2. Filesystem can hangs on I/O task and imxv4l2src will be stopped/crashed when using with multifilesink/filesink elements
3. Best solution, pre-recording parts in RAM, then concatinate parts on SD-cards in background threads.
4. When GPU decrease frequency on overhot it reduce performance of VPU - increasing execution of IPU tasks (interlacing, converting colorspace and etc.). This cause imxv4l2src stop/crash when imxvpuenc_h264 doesn't have time to encode incoming frames. Tune prop **queue-size** for imxv4l2src doesn't solve the problem on 100%, but optimal value for us was when **queue-size=8**

IMHO analog cam is ancient technology that require so much resouces for such a terrible quality.

**Comment by dv1** [comment]
I've also had problems with the tw6869 when trying to use multiple streams. And yes, it is surprising how this old tech can cause these troubles - but then again, we are interfacing analog and digital here.
