### ISSUE TITLE
closing pipeline with imxipuvideosink doesnt clear the output framebuffer

### ISSUE THREAD

**Issue by Arunvist** [Freescale/gstreamer-imx#160]
Hello,

We are creating pipeline using imxipuvideosink to play a video to /dev/fb0.
When we try to close the pipeline, the last frame is still available in fb0.
How it can be cleared?

should i  use "gst_imx_ipu_blitter_fill_region" function for clearing? & where?

Thanks,
Arunkumar

**Comment by javiervalcarce** [comment]
Hi.
I have the same problem, for the moment, I've solved it drawing directly to the framebuffer, i.e, outside gstreamer world. There are many tutorials explaining how to mmap() the /dev/fb0 and accesing directly the pixel data (but it is very slow, the blink effect is perfectly visible).

**Comment by dv1** [comment]
I added a clear-at-null property that does this. If clear-at-null is set to TRUE, then the framebuffer is filled with black pixels if the pipeline is set to NULL. Let me know if it works for you.

**Comment by dv1** [comment]
Closing this issue, since all tests here show me that it works. Reopen please if there are still problems.
