### ISSUE TITLE
SIGSEGV error while playing high frame rate video with imxvpudec and imxeglvivisink

### ISSUE THREAD

**Issue by Arunvist** [Freescale/gstreamer-imx#161]
Segmentation fault reported when playing high frame rate videos with the pipeline we create and also with playbin. Same files can be played if I use vpudec instead of imxvpudec.

Please find the pipeline for the playbin:
gst-launch-1.0 playbin uri=file:///tmp/usb/ Managaram.mp4 audio-sink="alsasink device=route_media_sink" video-sink="imxeglvivsink ivi-surfaceid= 110 window-width=800 window-height=480" &

Error we received:

[INFO]  Product Info: i.MX6Q/D/S
Setting pipeline to PAUSED ...
output_scale
Pipeline is PREROLLING ...

====== AIUR: 4.0.9 build on Jun 14 2017 11:00:18. ======
        Core: MPEG4PARSER_06.09.22  build on Jan 12 2016 05:26:25
 file: /usr/lib/imx-mm/parser/lib_mp4_parser_arm11_elinux.so.3.2
------------------------
    Track 00 [audio_0] Enabled
        Duration: 2:16:15.287808000
        Language: und
    Mime:
        audio/mpeg, mpegversion=(int)1, channels=(int)2, rate=(int)44100, bitrate=(int)127706
------------------------
------------------------
    Track 01 [video_0] Enabled
        Duration: 2:16:18.343936000
        Language: und
    Mime:
        video/x-h264, parsed=(boolean)true, alignment=(string)au, stream-format=(string)avc, width=(int)640, height=(int)290, framerate=(fraction)500000/20833, codec_data=(buffer)01640015ffe1001767640015acd940a023b01100005161000f42408f162d9601000668ebe3cb22c0
------------------------

====== BEEP: 4.0.9 build on Jun 14 2017 11:00:22. ======
        Core: MP3 decoder Wrapper  build on Mar 21 2014 15:04:50
 file: /usr/lib/imx-mm/audio-codec/wrap/lib_mp3d_wrap_arm12_elinux.so.3
CODEC: BLN_MAD-MMCODECS_MP3D_ARM_02.13.00_CORTEX-A8  build on Apr 10 2014 15:26:15.
[INFO]  bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Not initialized
Caught SIGSEGV
[issue_log.txt](https://github.com/Freescale/gstreamer-imx/files/1087182/issue_log.txt)
![test_1](https://user-images.githubusercontent.com/17027682/27319436-146385f6-55af-11e7-838e-efb1e8fdfe66.png)

Attached the properties of the file played and gst log.

**Comment by Arunvist** [comment]
@dv1 Have you seen this issue?
Could you please help us to understand this issue?

Thanks,
Arunkumar R

**Comment by dv1** [comment]
aiur is NXP's parser. At least in the past, NXP's parsers did not mix with non-NXP decoder elements. Try if you can play without the aiur elements installed.
