### ISSUE TITLE
There is plans for g729 code/decode support for GStreamer-1.0?

### ISSUE THREAD

**Issue by dmitry-pozhidaev** [Freescale/gstreamer-imx#163]
Hi
The IMX6 have embedded coder/encoder for G.729ab - Release Notes for G.729AB Decoder and Encoder/08-7023-RN-ZCH66.
There is plans for g729 code/decode support for GStreamer?
May be add to gstreamer-imx and G.711  too?

**Comment by dv1** [comment]
I won't add this to gstreamer-imx unless some NXP codec libraries exist for these codecs. I'll see if there are any.
