### ISSUE TITLE
Cropping issue with IPU or G2D

### ISSUE THREAD

**Issue by thsle** [Freescale/gstreamer-imx#165]
Hi all,

I'd like to crop a stream at the display time using imxg2dsink. Here is a simple pipeline to illustrate:

`DISPLAY=:0 gst-launch-1.0 -v videotestsrc ! video/x-raw, top=50, left=50, right=50, bottom=50 ! imxg2dvideosink input-crop=true`

I use a SABRE i.MX6QP Smart Device Board plateform running NXP/Yocto 2.1.0 (fsl-image-qt5 with all gstreamer and gstreamer-imx recipes).

The above pipeline does not work; neither trying to crop from IPU or G2D compositors, videotransform or sinks. "does not work" means the video is displayed uncropped.

Am I wrong in specifying the caps (params top, left, right and bottom) or is this really an issue? Due to the platform?

Thanks for your support,

**Comment by dv1** [comment]
Hmm, no, this is not correct. In fact, this is actually a problem at the moment in GStreamer - there is no way to just insert a video crop meta (which is what you need here). I currently have no solution for this. The videocrop element doesn't just insert a video crop meta, it actually removes pixels with the CPU.

I am thinking of adding an "addvideocropmeta" element to address this issue.

**Comment by ndufresne** [comment]
I'm pretty sure there is a bug report about it, and that it's relatively easy to do.

**Comment by dierberg** [comment]
We use this patch for the blitters, works fine with v4l2src.
[0001-cropping-added-to-video-sink-plugins-HYP-15795.txt](https://github.com/Freescale/gstreamer-imx/files/1374763/0001-cropping-added-to-video-sink-plugins-HYP-15795.txt)

**Comment by ndufresne** [comment]
This patch looks like what is implement in v4l2src, except that it's using crop- and a rectangle, so crop-top, crop-left, crop-width, crop-height.

**Comment by dierberg** [comment]
Booth is possible, I decide to use top, bottum, left, right because it fits better to our application

**Comment by woutervanh** [comment]
Is there already an implemented solution somewhere for this one?
BTW, at the initial question, there's no use to specify the DISPLAY=:0  here? As imxg2dvideosink just pushes to g2d, not to the windowing system?

**Comment by angolini** [comment]
It's been a while since an update in this issue. Could anyone, please, share the status (as we had a lot of source code update since 2019)
@woutervanh @dierberg @ndufresne @dv1

**Comment by dierberg** [comment]
Please tell me, is cropping now supported? We still use my patch in our application.

**Comment by angolini** [comment]
Let's wait from @dv1

**Comment by dv1** [comment]
The GstVideoCropMeta is already supported. One difference to gstreamer-imx 0.x is that now the sink announces to upstream that it can handle that meta. This may help in cases where upstream normally does crop in software but can use that meta instead if downstream supports it.

Also, @woutervanh , this is correct. DISPLAY=:0 is X11 specific.
