### ISSUE TITLE
Release 0.12.4 ?

### ISSUE THREAD

**Issue by clopez** [Freescale/gstreamer-imx#166]
Hi,

Last release 0.12.3 was a year ago.
Can you please do a new release?

I will like to send a patch for updating the Yocto recipe from meta-freescale and I prefer to do that using a commit tagged as release.

**Comment by dv1** [comment]
I'll do a release in a few days. Then you can send in the Yocto recipe.

**Comment by dv1** [comment]
Update: This will not be 0.12.4, but 0.13.0, since there are new elements (various G2D+pango based ones, and imxv4l2videosink) and other nontrivial changes. I need to review all this, so it takes me longer than planned. Roughly one more week.

**Comment by dv1** [comment]
Alright, you can go ahead. I just released 0.13.0.

**Comment by dv1** [comment]
@clopez , any news? I can also send a patch to meta-freescale.

**Comment by clopez** [comment]
@dv1 please feel free to send the patch yourself if you wish (I'm busy with unrelated things). Thanks

**Comment by dv1** [comment]
Since this is done, I'm closing this issue.
