### ISSUE TITLE
g2dvideosink displays wrong cache content 

### ISSUE THREAD

**Issue by dierberg** [Freescale/gstreamer-imx#169]
We have a workaround/fix in memory allocation of g2d. 
[0001-imxg2dvideosink-allocation-cache-fix-HYP-13887.txt](https://github.com/Freescale/gstreamer-imx/files/1381650/0001-imxg2dvideosink-allocation-cache-fix-HYP-13887.txt)

**Comment by dv1** [comment]
Hmm this needs more explanation. I've never had any problems with this. Why do you have to disable caching? Sounds more like a bug in your G2D version..

**Comment by dierberg** [comment]
We had green video out content when switching to an IP-camera which was replaced after first frames by real content. Also with heavy motion of the camera we saw content from old frames. Both was fixed by this patch.

**Comment by dierberg** [comment]
The bug came up with the Jethro branch of openembedded. (Fido worked fine)

**Comment by dv1** [comment]
Interestingly, #172 seems to also suffer from G2D caching problems. I disabled uncached pages in a commit now, and added a #define to re-enable it if needed.

**Comment by dv1** [comment]
Closing for now, since the mentioned change should fix it. Reopen if there are still problems please.
