### ISSUE TITLE
Refcounting error on phys mem alloc for mmap 

### ISSUE THREAD

**Issue by dierberg** [Freescale/gstreamer-imx#171]
We observe problems and fixed them using this patch: 
[0001-phys_mem_allocator-refcountig-mmap-fix-HYP-12917.txt](https://github.com/Freescale/gstreamer-imx/files/1374457/0001-phys_mem_allocator-refcountig-mmap-fix-HYP-12917.txt)

**Comment by dv1** [comment]
When I try to open this, I get a download dialog, and the downloaded file is HTML. Can you fix this so I can access the patch itself?

**Comment by dierberg** [comment]
Sorry, my fault ... 

[0001-phys_mem_allocator-refcountig-mmap-fix-HYP-12917.txt](https://github.com/Freescale/gstreamer-imx/files/1381635/0001-phys_mem_allocator-refcountig-mmap-fix-HYP-12917.txt)

**Comment by dv1** [comment]
I've been going over this, and it looks interesting, but I think this can be integrated in a more generic fashion. I'll do that in a post-0.13.0 release.

**Comment by dv1** [comment]
Reviving this issue. Check out this pull request: https://github.com/Freescale/gstreamer-imx/pull/183 it looks like this one overlaps with your patches.

**Comment by dierberg** [comment]
Yes, it overlaps. But #183 does not fix the refcounting problem. In simple pipelines this may be not a problem, but we have very complex gstreamer app with many sources, recording, video out and live streams.

**Comment by dv1** [comment]
Closing this since this allocator is no longer present in new gstreamer-imx versions.
