### ISSUE TITLE
2D GPU AXI BUS error during repeated destruction and creation of pipeline

### ISSUE THREAD

**Issue by jamescc-spx** [Freescale/gstreamer-imx#172]
We are making good use of the g2d plugins (compositor and transform) in our gstreamer pipeline.  However we notice after several attempts we get a AXI bus failure (attached).  Annoyingly this is after large number of attempts!

To be clear we are repeatedly - creating a pipeline with g2d gstreamer-imx plugins, putting it into a PLAYING state, putting it to the NULL state and destroying the pipeline.

We also use the g2d gpu directly in our code (out side of gstreamer), and doing so the problem is seen more frequently - 1 in 100 attempts.  If we avoid using this g2d code in our code (outside of the plugins) using memcpy's instead, the problem is only seen 1 in 500 attempts.

**Using UNCACHED memory for the g2d_alloc seems to resolve the problem?**  My suspicion is that this is a memory allocation/deallocation occuring whilst the GPU is still running.  Anecdotally, it seems to occur more frequently when the ARM cores are more busy.

We are using:
- gstreamer-imx commit 8eb726a (Mar 1st)
- https://github.com/Freescale/kernel-module-imx-gpu-viv.git release 5.0.11.p8.6 and the corresponding userspace libraries.

[axi_bus_error.txt](https://github.com/Freescale/gstreamer-imx/files/1397598/axi_bus_error.txt)

Questions about the g2d if anyone knows the answers:

1. The g2d_alloc(), g2d_cache_op() functions.  Where is the cache?  Is this just the ARM caches, or is there some 2d GPU specific cache?   My assumption is that this is just managing the ARM caches.

2. Is the g2d_cache_op() immediate or is it queued like g2d_copy(), g2d_blit() GPU operations.  i.e. do we need to run g2d_finish() to make sure the operation has completed?  Obviously if this is just managing the CPU cache then I assume it is immediate.

**Comment by dv1** [comment]
It seems as if G2D caching isn't stable. I disabled uncached pages in a commit now, and added a #define to re-enable it if needed. Let me know if this successfully circumvents the issue for you.

**Comment by jamescc-spx** [comment]
Thanks, good idea to remove the cache operations as well.

Will get back to you early next week.  Might need to cherry pick as we are stuck on an old kernel  (3.14) and the new v4l2 sink is preventing compilation.

**Comment by dv1** [comment]
Ah, good point about the kernel. I pushed a commit that adds configuration switches for selectively disabling imxv4l2videosrc / imxv4l2videosink. The plugin I also renamed from v4l2src to v4l2video.

**Comment by jamescc-spx** [comment]
Commit 22222e5c757cae12a9c835e63a413ab8a5d9d7c9 has resolved the issue for us, with the benefit of some additional fixes w.r.t. building the plugins for our older kernel (3.14).

As discussed above the key commit is 15b92f6e018bfddfb94a0a82d2e296a7731f0acc to disable the 2D GPU cache.  For safety we have also disabled the cache in our code where we make use of the 2D GPU outside of gstreamer.  

Although disappoint to make use of the cache in our use case, a pipeline with a compositor, a few image transforms (for scaling), a colour space conversion, and use of the VPU (for encoding), the performance impact does not seem significant.
