### ISSUE TITLE
High CPU Load with gstreamer-1.0

### ISSUE THREAD

**Issue by md-jamal** [Freescale/gstreamer-imx#173]
Hi,

I am using gst-launch-1.0 to play a video on iMX6 board, and found it is taking almost 70% of my CPU .. How can i reduce the CPU Load.

gst-launch-1.0 playbin uri=file:///Images/test.mp4 video-sink="imxeglvivsink"

I tried changing the video-sink to "imxipuvideosink" still no effect.
Please help

**Comment by dv1** [comment]
Sorry for the very late reply... busy with a lot of stuff :/

Try using flags=0x57 to disable all kinds of software based image processing. Like:

    gst-launch-1.0 playbin flags=0x57 uri=file:///Images/test.mp4 video-sink="imxeglvivsink"

Also note that if the video is not encoded in a format supported by the VPU, this cmdline will most likely use a software decoder, which is very slow on imx6.
