### ISSUE TITLE
imxipuvideotransform output-rotation does not work for rotate-90 and rotate-270

### ISSUE THREAD

**Issue by javiervalcarce** [Freescale/gstreamer-imx#174]
Hi all.
The following pipeline freezes when I set `imxipuvideotransform` output-rotation propery to "rotate-90" and "rotate-180". I'm using gstreamer-imx 0.13.0

`gst-launch-1.0 rtspsrc latency=100 location=rtsp://169.254.11.5:554/live.sdp ! rtph264depay ! h264parse ! imxvpudec ! imxipuvideotransform output-rotation="rotate-270" ! imxipuvideosink window-x-coord=0 window-y-coord=0 window-width=800 window-height=480`

dmesg output is:
`Nov 10 12:00:37 cgtimx6 user.err kernel: mxc_ipu mxc_ipu: ERR: no-0x0,ipu_queue_task err:-22
Nov 10 12:00:37 cgtimx6 user.err kernel: mxc_ipu mxc_ipu: ERR: no-0x0,ipu_queue_task err:-22`

With "rotate-180" I see also these warnings:
`[  951.201468] imx-ipuv3 2800000.ipu: IDMAC21's U offset is not 8-byte aligned
[  951.201495] imx-ipuv3 2800000.ipu: IDMAC21's V offset is not 8-byte aligned`

but video is displayed correctly.

Any idea? 
I would like to test this same piepelie with gstreamer-imx 0.12.3 but imxipuvideotramsform lacks output-rotation property.

Thanks.

**Comment by grburkhart** [comment]
For us, we could down sample the image to a size in which no side is greater than 1024 pixels and that worked as a work-around.

**Comment by dv1** [comment]
New v2 version of gstreamer-imx implements manual tiling to fix this issue. However, IPU performance is much lower with 90/270 degree rotations. This appears to be a hardware and/or driver limitation.
