### ISSUE TITLE
Buffer problem using videorate with imxvpuenc_h264

### ISSUE THREAD

**Issue by angelobt** [Freescale/gstreamer-imx#176]
If I compose a pipeline putting together videorate and imxvpuenc elements, I get the following errors

GStreamer-CRITICAL **: gst_buffer_pool_has_option: assertion 'GST_IS_BUFFER_POOL (pool)' failed

 GStreamer-CRITICAL **: gst_object_unref: assertion 'object != NULL' failed

example pipeline:
gst-launch-1.0 imxv4l2videosrc ! imxipuvideotransform ! videorate  ! imxvpuenc_h264 ! filesink location=/dev/null

I'm using the latest versions of gstreamer-imx plugins.
Gstreamer version is 1.8.3.
I`m using an IMX 6 dual with linux 4.1.15

Tell me if you need more logs info.

Thanks

**Comment by Pehoh** [comment]
You probably need to add the `drop-only` property to `true`, and also add caps to specify the framerate you want.
`gst-launch-1.0 imxv4l2videosrc ! imxipuvideotransform ! videorate drop-only=true ! "video/x-raw, framerate=5/1" ! imxvpuenc_h264 ! filesink location=/dev/null`
