### ISSUE TITLE
low performance with rtp

### ISSUE THREAD

**Issue by ranshalit** [Freescale/gstreamer-imx#177]
Hello,

We get a low performance trying to use gstreamer with rtp for 1280,1024 resolution. Only if reduce the resolution to a very low value, we start to see the video as required.
We are not sure if imx6 quad is just too weak, if it is a gpu or memory bottleneck.
 
This is what we tried:
1. Change screen settings to support 32 bit per pixel:
fbset -depth 32 -xres 1920 -yres 1080 

2. --- Linux Ubuntu sender (bouncing ball)----- (in the sending host)
gst-launch-1.0 -v videotestsrc pattern=18 ! video/x-raw,width=1280,height=1024,framerate=25/1,sampling=YCbCr-4:2:0 ! rtpvrawpay ! udpsink host=192.168.204.101 port=5000

3. --- Imx.6 reciever using display sink with GPU support ( imxg2dvideosink ) -----
gst-launch-1.0 -v udpsrc port=5000 caps = "application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)RAW,width=(string)1280,height=(string)1024, payload=(int)96,sampling=YCbCr-4:2:0" ! rtpvrawdepay ! imxg2dvideosink use-vsync=true 
 
Doing the same test with intel cpu instead of imx6, works just fine.

If we reduce the resolution in imx6 test to a lower resolution width=(string)320,height=(string)340, then it works much better (yet, still not perfect even then)
 
Is it that gpu is too weak or some other issue ?
 
Thank you for any idea,
Ran

**Comment by Vavooon** [comment]
It looks like you're sending too much data through network. You may try to encode the stream.

**Comment by ranshalit** [comment]
Hi, I am sending uncompressed video on purpose. That's the requirements. Thanks.
