### ISSUE TITLE
No I-Frames in imxvpuenc_h264 streams 

### ISSUE THREAD

**Issue by dierberg** [Freescale/gstreamer-imx#181]
Hello, 
checking the new openembedded branch "rocko" we found that there are no more  I-frames in h.264 encoded streams in 0.13.0.

We use the following properties:
 				"gop-size", 30,
				"idr-interval", 30,
				"quant-param", 19,
				"bitrate", 0,
				"me-search-range", 3, 
and defaults.

libimxvpuapi. is version 0.10.3

Any help would be appreciated - regards

**Comment by garygumdrops** [comment]
Has anyone looked into this either?
I am using:

Linux var-som-mx6 4.14.78-mx6+ge692c3062368 #1 SMP PREEMPT Wed Aug 26 10:32:13 UTC 2020 armv7l armv7l armv7l GNU/Linux
gstreamer 1.14.4
libgstimxvpu.so 0.13.0

It seems that changing either or both of **gop-size** and **idr-interval** for the **imxvpuenc_h264** encoder has no effect on I-frames. Or at least if it does then not in the way that gstreamer identifies them which is to make sure the **GST_BUFFER_FLAG_DELTA_UNIT** flag is clear.

**Comment by dv1** [comment]
New v2 versions of libimxvpuapi and gstreamer-imx produce I/IDR-frames. Verified with current yocto master (soon-to-be-release codename "hardknott").
