### ISSUE TITLE
Overlay not working in combination with VPU h264 encoder

### ISSUE THREAD

**Issue by VJ-Tony** [Freescale/gstreamer-imx#182]
I'm facing a problem with a text overlay on the i.MX6 when I use the VPU h264 encoder. 
Replacing the CPU encoder by a software encoder does fix the issue.
So when I use the x264enc, I have text annotated and when I use the imxvpuenc_h264 I have no text at all. 
This only occurs if there is also an imx camera input and a tee in the pipeline. 

The pipelines:
[test-day-with-tee.txt](https://github.com/Freescale/gstreamer-imx/files/1626243/test-day-with-tee.txt)
[test-day-with-tee-sw-enc.txt](https://github.com/Freescale/gstreamer-imx/files/1626244/test-day-with-tee-sw-enc.txt)

The debug outputs:
[debug_output_with_tee.log](https://github.com/Freescale/gstreamer-imx/files/1626230/debug_output_with_tee.log)
[debug_output_with_tee_sw_enc.log](https://github.com/Freescale/gstreamer-imx/files/1626231/debug_output_with_tee_sw_enc.log)

For more information see [this](http://gstreamer-devel.966125.n4.nabble.com/Text-overlays-don-t-work-on-i-MX6-in-certain-pipelines-td4685858.html) post

**Comment by eloi29** [comment]
Here is an interesting discussion on Gstreamer ML pointing a potiential issue in gstreamer-imx:
http://gstreamer-devel.966125.n4.nabble.com/Text-overlays-don-t-work-on-i-MX6-in-certain-pipelines-tt4685858.html

**Comment by angolini** [comment]
I think we can close this issue by now.

@dv1 if this is still something you want to keep open, please reopen the issue. thx
