### ISSUE TITLE
convert gstreamer0.10 pipeline to gstreamer1.0 pipeline

### ISSUE THREAD

**Issue by md-jamal** [Freescale/gstreamer-imx#184]
Hi Guys,

I need to convert the following gstreamer0.10 command which is used to stream video over IP into gstreamer1.0

	`gst-launch -v udpsrc port=5004 ! application/x-rtp, payload=96 ! rtph264depay ! vpudec low-latency=true ! imxv4l2sink sync=false`

I tried the following below command, but it failed when we are trying to stream:

   ```
 gst-launch-1.0 -v udpsrc port=5004 ! application/x-rtp, payload=96 ! rtph264
    depay ! imxvpudec  ! imxipuvideosink sync=false
```

I get error:streaming stopped, reason not-negotiated (-4)

Can you please help me in forming the pipeline.

**Comment by md-jamal** [comment]
Ok. I got the following pipeline working. It may help someone.

```
gst-launch-1.0 -vvv udpsrc port=5004 ! application/x-rtp, payload=96 ! rtph2
64depay ! h264parse ! imxvpudec ! imxipuvideosink sync=false
```

**Comment by dv1** [comment]
Can you try out:

    gst-launch-1.0 udpsrc port=5004 ! "application/x-rtp, payload=96" ! rtph264depay ! h264parse ! imxvpudec ! queue ! imxipuvideosink

and see how this works? The "sync=false" should not be necessary.
