### ISSUE TITLE
Hardware accelerated decoding of individual jpeg pictures

### ISSUE THREAD

**Issue by guillerodriguez** [Freescale/gstreamer-imx#187]
I am successfully using imxvpudec to decode mjpeg, mpeg4, and h264 video, however it seems I cannot decode individual jpeg pictures, even though the imxvpudec caps suggest it should be possible.

For example the following pipeline fails:

     gst-launch-1.0 souphttpsrc location=http://192.168.0.241/image.jpeg ! imxvpudec ! imxipuvideosink

Output:

```
Setting pipeline to PAUSED ...                                                  
Pipeline is PREROLLING ...                                                      
ERROR: from element /GstPipeline:pipeline0/GstImxVpuDecoder:imxvpudecoder0: VPU 
decoder was not created                                                         
Additional debug info:                                                          
../src/vpu/decoder.c(509): gst_imx_vpu_decoder_handle_frame (): /GstPipeline:pip
eline0/GstImxVpuDecoder:imxvpudecoder0                                          
ERROR: pipeline doesn't want to preroll.                                        
Setting pipeline to NULL ...                                                    
Freeing pipeline ... 
```

The same pipeline replacing imxvpudec with jpegdec (software decoding) works fine.

Is this normal / expected?

**Comment by dv1** [comment]
Try adding jpegparse between souphttpsrc and imxvpudec .

**Comment by guillerodriguez** [comment]
Indeed this works. Why is it necessary? For a single jpeg frame (not jpeg) the output of souphttpsrc is already the raw jpeg data. Shouldn't imxvpudec be able to handle that directly?

**Comment by dv1** [comment]
This is common in GStreamer. You also have to use h264parse before imxvpudec for h264 data, for example. The reason is that the input stream may deliver only parts of JPEG/h264/etc. frames. jpegparse and co. accumulate data until an entire frame is present, and output said frame. Furthermore, they parse the frame data, and produce appropriate GstSegments and GstCaps.

**Comment by guillerodriguez** [comment]
I see, that makes sense. Thanks!
