### ISSUE TITLE
Tearing with imxipuvideosink when showing individual jpeg frames

### ISSUE THREAD

**Issue by guillerodriguez** [Freescale/gstreamer-imx#189]
I have a simple gstreamer application that shows video from a HTTP source that serves individual JPEG images (not an MJPEG stream!). The pipeline looks like this:

    souphttpsrc -> jpegparse -> jpegdec -> imx***videosink

When I get an EOS event, I set the pipeline to NULL, then set it back to PLAYING so that the next image is fetched, decoded, and shown.

This works just fine with imxg2dvideosink. However with imxipuvideosink, I see heavy tearing -- the framebuffer is apparently cleared to black before showing each image. I trace this to the following code in blitter.c:

https://github.com/Freescale/gstreamer-imx/blob/master/src/ipu/blitter.c#L450

If I disable the above code, the tearing goes away.

So, questions:
 * Why is this necessary for the ipu sink, whereas it doesn't seem to be necessary for the g2d sink?
 * Is it always necessary? (even when inner region == outer region?)
 * Any suggestions on how to avoid this?

**Comment by angolini** [comment]
Could you, please test with latest version and update the status @guillerodriguez ?
