### ISSUE TITLE
Problem with imxvpudec when video sink is resized

### ISSUE THREAD

**Issue by guillerodriguez** [Freescale/gstreamer-imx#191]
I have a simple pipeline that uses imxvpudec for decoding and imxg2dvideosink for rendering.

If I try resize the video sink on the fly, the video is corrupted. When I switch back to the "initial" resolution, the video looks good again.

I suspect that imxvpudec and imxg2dvideosink are initially negotiating the window size. Then imxvpudec starts generating frames of that size. Later when imxg2dvideosink is resized, this change is not propagated back, so imxvpudec continues generating frames with the (now wrong) size.

Indeed in the logs I see the following:

Initial frame size is 640x480:

```
0:00:08.594657334   269 0x74d03350 LOG                imxvpuapi imxvpuapi_vpulib.c:2143:imx_vpu_dec_decode: output info: 
 indexFrameDisplay 6  indexFrameDecoded 12  NumDecFrameBuf 0  picType 1  idrFlg 2  numOfErrMBs 0  hScaleFlag 0  vScaleFla
g 0  notSufficientPsBuffer 0  notSufficientSliceBuffer 0  decodingSuccess 1  interlacedFrame 0  mp4PackedPBframe 0  h264N
pf 0  pictureStructure 0  topFieldFirst 0  repeatFirstField 0  fieldSequence 0  decPicWidth 640  decPicHeight 480
```

Then I resize the videosink to 240x180:

```
0:00:02.231138001   288 0x74e03290 LOG            imxipublitter blitter.c:447:gst_imx_ipu_blitter_blit:<imxipublitter0> m
ain_task input:  width:  640  height: 480  format: 0x30323449 (I420)  crop: 0,0 640x480  phys addr 0x45600000  deinterlac
e enable 0 motion 0x0
0:00:02.231370001   288 0x74e03290 LOG            imxipublitter blitter.c:457:gst_imx_ipu_blitter_blit:<imxipublitter0> m
ain_task output:  width:  240  height: 320  format: 0x41524742 (BGRA)  crop: 0,70 240x180  paddr 0x3c400000  rotate: 0
```

The new size does not seem to be propagated back to imxvpudec.

Shouldn't the video sink be forcing a renegotiation?

Other than that -- how can I work around this?

**Comment by angolini** [comment]
Could you, please, test with the latest version and share the status @guillerodriguez ?
