### ISSUE TITLE
Deadlock during state change to ready if stream is already at EOS

### ISSUE THREAD

**Issue by mfarver** [Freescale/gstreamer-imx#194]
Has anyone seen this?  When a stream using imxeglvivsink is in the process of shutting down because it has reached the end of the stream, and you set the state to Ready manually the two threads will deadlock.  This is using the latest head of gstreamer-imx, and an older gstreamer1.0. (1.6.3).  What data would help troubleshoot this, or would it be best if I try to build a test application that displays it?

**Comment by angolini** [comment]
Could you, please, test using the latest version and update the status @mfarver ?
