### ISSUE TITLE
upcoming gstreamer 1.14 webrtc bin causes internal dataflow error.

### ISSUE THREAD

**Issue by aduskett** [Freescale/gstreamer-imx#196]
GStreamer 1.14 has a new webrtc bin element that allows making a pipeline into a compatible webrtc stream (see http://blog.nirbheek.in/2018/02/gstreamer-webrtc.html for more details.)

However, when using the webrtc plugin, the imx6 GStreamer element chokes with the following output:

``
ERROR: v4l2 capture: mxc_v4l_dqueue timeout enc_counter 0
0:00:36.838531886   479  0x20b8b80 ERROR      imxv4l2bufferpool v4l2_buffer_pool.c:262:gst_imx_v4l2_buffer_pool_acquire_buffer:<imxv4l2bufferpool0> VIDIOC_DQBUF failed: Timer expired
0:00:36.838815379   479  0x20b8b80 INFO                 basesrc gstbasesrc.c:2839:gst_base_src_loop:<imxv4l2videosrc0> pausing after gst_base_src_get_range() = error
0:00:36.839067855   479  0x20b8b80 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<imxv4l2videosrc0> error: Internal data stream error.
0:00:36.839202932   479  0x20b8b80 WARN                 basesrc gstbasesrc.c:3055:gst_base_src_loop:<imxv4l2videosrc0> error: streaming stopped, reason error (-5)
``
What's interesting is that the live stream continues to run for several seconds afterwards with almost no lag.

To reproduce the error, perform the following steps:

1) Download the the project from: https://github.com/centricular/gstwebrtc-demos/
2) Edit sendrecv/gst/webrtc-sendrecv.c 
3) Replace the pipeline on line 269 with:
``
pipe1 = gst_parse_launch ("webrtcbin name=sendrecv stun-server=stun://stun.l.google.com:19302 imxv4l2videosrc device=/dev/video0 fps-n=30 imx-capture-mode=0 ! queue ! imxvpuenc_h264 bitrate=5000 idr-interval=60 ! h264parse ! rtph264pay ! queue ! application/x-rtp,media=video,encoding-name=H264,payload=96 ! sendrecv. ", &error); 
``
4) Cross compile the application
5) Go to https://webrtc.nirbheek.in and run the application

I know that GStreamer 1.14 isn't technically out yet, but the list of blocking bugs are very very small, and after a discussing on IRC with the GStreamer developers, we determined that this is an IMX issue and not a GStreamer issue. Any help would be appreciated!

Adam

**Comment by aduskett** [comment]
As an update: GStreamer 1.14.0 is out and the same problem persists.

**Comment by dv1** [comment]
This is on my list for the next week. From looking at it, I can imagine that this is caused by imxv4l2videosrc. I'll have more info later. Sorry for the delay, had tons of other things to do.

**Comment by aduskett** [comment]
Oh great! Thanks a ton! I really appreciate it!

**Comment by dv1** [comment]
I have been looking at this ... and it really is weird. I created pipelines that work with openh264enc, but not with imxvpuenc_h264. I'm continuing to investigate. Unfortunately, no clue yet.

**Comment by aduskett** [comment]
Hey! I appreciate your help and feedback. I'm also glad that you were able to replicate the issue I was having.

Thanks so much again!

Adam

**Comment by dv1** [comment]
Hi. You should try this again. In my investigations, I found that there were problems with GStreamer's own webrtc h264 support. See here for details: https://bugzilla.gnome.org/show_bug.cgi?id=795404
