### ISSUE TITLE
Not able to render on overlay window using imxeglvivsink

### ISSUE THREAD

**Issue by naseebpanghal** [Freescale/gstreamer-imx#198]
I have created a player by referring link [https://gstreamer.freedesktop.org/documentation/tutorials/basic/toolkit-integration.html](url) with some modifications.
Instead of "playbin" i have used "filesrc", "decodebin", "imxeglvivsink", "autoaudiosink"

Drawing window is created using gtk api `gtk_drawing_area_new` 
Overlay is set using gst api `gst_video_overlay_set_window_handle`.

When i run the application, it plays audio only but video is not rendered on overlay window. "imxeglvivsink" plugin get blocked on XNextEvent inside mainloop thread. Although XSendEvent also gets called(i verified using logs) but don't know where those Events get vanished.

In my application, if i create window using X11 api `XCreateWindow` instead of GTK then everything works fine but i want to create window using GTK itself. 

Also, this code(with GTK window) works well on my old ubuntu 14.04 system(libgtk-3-dev: v3.10..8 , gstreamer:  v1.2.4, imxeglvivsink: v0.11.1 ) whereas on ubuntu 16.04(libgtk-3-dev v3.18.9: , gstreamer: 1.8.0, imxeglvivsink: v0.12.0) it creates problem.

Please suggest if overlay usage is changed in later versions or imxeglvivsink expect window some other way.

**Comment by dv1** [comment]
Closing this since imxeglvivsink no longer exists. Use glimagesink or waylandsink instead.
