### ISSUE TITLE
Automatically handle video rotation

### ISSUE THREAD

**Issue by DuBistKomisch** [Freescale/gstreamer-imx#200]
For example, many videos recorded on mobile devices are saved in qt/mov/mp4 containers with metadata saying they should be played back rotated by 90 degrees. It seems like gstreamer is able to extract this information (`image-orientation=(string)rotate-90`) but it isn't put into the caps, it's instead in the tags.

I've written some code in our application to listen to messages on the pipeline, and extract this tag and apply it manually to the video sink:

```
    case GST_MESSAGE_TAG:
      {
        GstTagList *tags;
        gst_message_parse_tag(msg, &tags);

        // manually apply orientation to sink
        gchar *image_orientation;
        if (gst_tag_list_get_string(tags, "image-orientation", &image_orientation)) {
          int rotation = 0;
          if (g_strcmp0(image_orientation, "rotate-90") == 0) {
            rotation = 1;
          } else if (g_strcmp0(image_orientation, "rotate-180") == 0) {
            rotation = 2;
          } else if (g_strcmp0(image_orientation, "rotate-270") == 0) {
            rotation = 3;
          }
          g_object_set(obj->videoSink,
              "output-rotation", rotation,
              NULL);
          g_free(image_orientation);
        }

        gst_tag_list_unref(tags);
        break;
      }
```

(The string matching and magic numbers obviously suck, this is just a quick and dirty bug fix.)

Am I missing some built in way this is meant to happen? There seem to be elements like `videoflip` related to this but even with software decoding `playbin`/`gst-play-1.0` don't handle this.

Would it be a good idea to make the imx sinks handle this automatically (by responding to tags events), at least with an opt-in property?

**Comment by DuBistKomisch** [comment]
Follow up: turns out the official vaapi plugin's sink does exactly this: https://github.com/GStreamer/gstreamer-vaapi/blob/master/gst/vaapi/gstvaapisink.c#L1679

**Comment by dv1** [comment]
Implemented in the new imx2d blitter transform, compositor, and sink elements.
