### ISSUE TITLE
Internal physmem buffer pool of compositor/blitter destroyed/created for every single buffer if pads have different caps

### ISSUE THREAD

**Issue by sdroege** [Freescale/gstreamer-imx#201]
When input streams are not in physmem, an internal buffer pool is currently created in `gst_imx_blitter_set_input_frame_internal`. This is cached and reused in the blitter instance, and only destroyed again at the end or whenever `gst_imx_blitter_set_input_video_info` is called (and the video info changes).

`gst_imx_blitter_set_input_video_info` is called by `gst_imx_blitter_compositor_draw_frame` for every frame. So if the input streams have different caps, the buffer pool is going to be destroyed again the next time another pad's buffer is handled.

This causes a new buffer pool to be created and destroyed for every single frame, causing lots of overhead and memory allocations/deallocations.

A solution would be to cache the buffer pool per pad, and also store the corresponding video info per pad.

**Comment by angolini** [comment]
I see patches being added for this issue, so I'm closing this issue
