### ISSUE TITLE
Update internal aggregator/videoaggregator copies

### ISSUE THREAD

**Issue by sdroege** [Freescale/gstreamer-imx#202]
They are from 1.8 times and full of bugs and problems that are fixed since years in GStreamer.

Aggregator is in GStreamer core since 1.14, videoaggregator will be with 1.16 and at that point the internal copies should probably be laid to rest and be removed.

**Comment by dv1** [comment]
New v2 version of gstreamer-imx uses GstVideoAggregator from 1.16, so this is no longer relevant.
