### ISSUE TITLE
imxipuvideotransform de-interlacing half's frame-rate

### ISSUE THREAD

**Issue by ghost** [Freescale/gstreamer-imx#204]
Hi All,
We are working on i.MX6 Dual with Linux Kernel version 4.9.
Our camera's are outputting interlaced video (720X576@25),
But once de-interlaced with imxipuvideotransform we drop to 12.5 fps.
It seems that we get 1 progressive frame for every 2 fields,
instead of the expected 1 progressive frame for every 1 field,
we seem to be getting 2 fields per buffer in a rate of 12.5 buffers per second,
so num-buffers=100 gives 8 seconds of video.
once the imxipuvideotransform de-interlaces the video we get 12.5 fps.
Any assistance will be greatly appreciated.
Regards,
Yair

**Comment by angolini** [comment]
Could you, please, test using the latest version and update the status  @yair-podemsky-l4b ?
