### ISSUE TITLE
imx8 gstreamer plugins

### ISSUE THREAD

**Issue by skyline220** [Freescale/gstreamer-imx#205]
Hi,

Are the gst-plugins specifically for IMX
(such as imxvpuenc_mjpeg) working on the IMX8? If so is there an image with them? The most recent release on the main website doesnt contain them. gst-inspect-1.0 yields no vpu_enc or vpu_dec or imx or omx based plugins.

Either Linux or Android is fine.

Thanks

**Comment by dv1** [comment]
No, they are for imx6. I am working on imx8 support though, as part of a new major version update (1.0.0).

**Comment by bodangly** [comment]
@dv1 Has there been any progress on imx8(m) support for gstreamer? What left is there to do? Is it something that can be accelerated by getting more people working on it? Thanks so much.

**Comment by dv1** [comment]
Hi. Sorry for the silence. Yes, there has been substantial progress. There will be a complete rewrite to accomodate for the differences between i.MX6 and i.MX8 codecs. Currently I am working on a libimxvpuapi rewrite, which will handle i.MX8 Hantro based decoding as well as i.MX6 CODA based en/decoding. I also have started a rewrite of gstreamer-imx based on the new libimxvpuapi. Decoding already works on the i.MX8, with all formats except for RealVideo (and, AVS is broken currently). If all goes well, I'll have something online by the end of January.

**Comment by dv1** [comment]
I finally managed to get a v2 branch up. Check it out.
