### ISSUE TITLE
SIGSEGV error in gst-launch-1.0 (v 1.8.1) when converting a grey-format file to rgb-format file

### ISSUE THREAD

**Issue by chenghyang2001** [Freescale/gstreamer-imx#206]
Dear Sir,
         My device uses a imx6 platform and the BSP version I use is "NXP's 4.1.15-2.1.0 Yocto Project BSP"
.
 I execute a "gst-launcher-1.0" command as following to convert a grey format picture file to a rgb format picture file.

gst-launch-1.0 -v filesrc location=test.grey blocksize=5038848  !  "video/x-bayer,format=bggr,width=2592,height=1944,framerate=1/1" !  bayer2rgb ! filesink location=test.rgb 

Most of time, this command executes successfully to convert my file "test.grey" to my desired file "test.rgb". However an error occurs randomly and the error is shown below:

     Caught SIGSEGV
#0 0x76be71a4 in poll () at ../sysdeps/unix/syscall-template.S:84
#1 0x76ccccb4 in ?? () from /usr/lib/libglib-2.0.so.0
Spinning. Please run 'gdb gst-launch-1.0 15629' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core.
 

After diving into the source files, I found this error results from the function "bin_handle_async_done()" in the gstream source file "gstbin.c". 
 

My question is : why this error occurs? Because I have seen the error several times on different testing scenarios. I executed a test script to execute this command for 2000 times and this error always occurs at different loop. Sometimes it occurs at 220th loop and next time it occurs at 515th loop or 858th loop. In brief, this error occurs randomly.

Please help,
Thanks,
Peter

**Comment by rob-mclean** [comment]
Peter,
I'm having a problem with the same symptoms.  Did you ever find a solution to the problem?

**Comment by rob-mclean** [comment]
In my case I upgraded the ORC recipe from 0.4.27 to 0.4.29, and the problem went away.
