### ISSUE TITLE
streaming video using gstreamer on local + rtmp server

### ISSUE THREAD

**Issue by harshal034** [Freescale/gstreamer-imx#207]
Hello,

 

I am trying capture a stream from local video and show it to local display as well as want to stream the same on RTMP server.

 

I am expecting no latency (at least, on a local display).

 

Issue is when I use streaming to only local it's working fine with below pipe:

 

gst-launch-1.0 imxv4l2videosrc device=/dev/video1 imx-capture-mode=4 fps-n=30 ! video/x-raw,width=1280,height=720,framerate=30/1 ! timeoverlay ! imxipuvideosink

 

When I want to stream it to local + rtmp server, I could see lot of latency and frame drops on local as well. Here is the pipeline that I am using:

 

gst-launch-1.0 imxv4l2videosrc device=/dev/video1 imx-capture-mode=4 fps-n=30 ! video/x-raw,width=1280,height=720,framerate=30/1 ! timeoverlay ! tee name="local" local. ! queue !  imxipuvideosink local. ! queue ! imxipuvideotransform ! imxvpuenc_h264 bitrate=8000  ! h264parse ! flvmux ! rtmpsink location=rtmp://192.168.0.56/live

 

Any suggestions/clue?

**Comment by angolini** [comment]
Could you, please, test using the latest version and update the status  @harshal034 ?
