### ISSUE TITLE
Semi-transparent pixels are overlaid onto existing framebuffer contents instead of replacing

### ISSUE THREAD

**Issue by DuBistKomisch** [Freescale/gstreamer-imx#220]
I'm trying to use the imx6 fb1 hardware overlay feature with local (per pixel) alpha blending, and I'd like to output the overlay via a gstreamer pipeline. However, a frame with transparency given to the `imx*sink` seems to just get alpha blended onto whatever is already in the framebuffer memory, rather than clearing it out and just being transparent. This also seems to happen with the imxg2dtextoverlay: whatever random data is in the allocated memory is left there and with the text blended onto it.

I'm not sure if this is just some built in behaviour of the hardware, but is there a way to force replacing instead of blending? My current workaround is to `dd if=/dev/zero of=/dev/fb1 2>/dev/null` which clears the framebuffer memory (at least when not in triple buffering mode), but this is slow and awkward to control. Luckily the current use case is not frequently updating the overlay, but this does prevent more ambitious overlays we'd like to do such as a clock or news ticker.

Here is an example of playing some greenscreen video from youtube with `alpha method=1` (obviously get terrible framerate but good to demonstrate the issue) on fb1, while a normal non-alpha video plays on fb0, each new frame appears on top of the previous one, instead of replacing it:

![image](https://user-images.githubusercontent.com/703055/47976258-b7d3d780-e105-11e8-8ccc-4b97d15a9e26.png)

Another simple test is playing a PNG or GIF image with transparency with `gst-play-1.0`, it will appear on top of whatever the last frame was, rather than having no (black) background.

**Comment by DuBistKomisch** [comment]
I see that `gst_imx_g2d_blitter_blit` is deciding to use local blending when the input format has an alpha channel, and disabling that seems to do what I want. I think I should be able to add a property to imxg2dvideosink to control this, and pass it into blitter_blit. I notice the alpha parameter seem to be ignored in the ipu and pxp blitters though.

**Comment by angolini** [comment]
Could you, please, test using the latest version and update the status @DuBistKomisch ?
