### ISSUE TITLE
It's not working : mxc_v4l2_capture -> gstreamer imxv4l2src

### ISSUE THREAD

**Issue by tech4npo** [Freescale/gstreamer-imx#225]
https://community.nxp.com/thread/497342
Context : imx6.yocto.jethro(kernel 4.1.15) : tvp_5150 -> (CSI-0,IPU-0) -> mxc_v4l2_capture -> /dev/video0

In Our gstreamer 1.0 plugin imxv4l2videosrc is missing, but we have a plugin imxv4l2src, why the plugin imxv4l2videosrc may be missing

**Comment by dv1** [comment]
imxv4l2src is from NXP's imx-gst1.0-plugin package, not from gstreamer-imx, so the latter was not installed on your image.
