### ISSUE TITLE
gst 1.14 glimagesink no longer works with imx video decoder

### ISSUE THREAD

**Issue by philn** [Freescale/gstreamer-imx#228]
Because the wscript looks for the gst allocators library in -bad, but it moved to -base in 1.14.

**Comment by dv1** [comment]
This should work again now in the v2 branch, as part of the major rewrite that introduces i.MX8 support and requires GStreamer 1.14.

**Comment by philn** [comment]
Fixed by https://github.com/Freescale/gstreamer-imx/pull/236 I suspect...
