### ISSUE TITLE
Is there a reason not to change window position in eglvivsink?

### ISSUE THREAD

**Issue by elvis-epx** [Freescale/gstreamer-imx#230]
I have noted that eglvivsink allows changing the window size while it is active, but not the x/y position,  at least in X11 platform, at least when the window is not inside another window. Is there any reason for this?

I needed to change window position while playing video, and the video window is not inside another (it floats above my app, which is HTML5), so I patched the plugin as follows, so I can hide and move around the video on screen, allowing this seems to be harmless.

```
--- a/src/eglvivsink/egl_platform_x11.c
+++ b/src/eglvivsink/egl_platform_x11.c
@@ -645,12 +645,9 @@ gboolean gst_imx_egl_viv_sink_egl_platform_set_coords(GstImxEglVivSinkEGLPlatfor
 {
 	EGL_PLATFORM_LOCK(platform);

-	if (platform->parent_window != 0)
-	{
-		Display *x11_display = (Display *)(platform->native_display);
-		Window this_window = (Window)(platform->native_window);
-		XMoveWindow(x11_display, this_window, x_coord, y_coord);
-	}
+	Display *x11_display = (Display *)(platform->native_display);
+	Window this_window = (Window)(platform->native_window);
+	XMoveWindow(x11_display, this_window, x_coord, y_coord);

 	EGL_PLATFORM_UNLOCK(platform);
```

**Comment by angolini** [comment]
I think this issue is now obsolete, please take a look at https://github.com/Freescale/gstreamer-imx#integration-with-gstreamer-and-other-external-elements

I'm closing it. In case of any comment you can reopen it if you like.
