### ISSUE TITLE
eglvivsink doesn't work with wayland

### ISSUE THREAD

**Issue by BMValeev** [Freescale/gstreamer-imx#241]
If compile eglvivsink on wayland platform 

> Selected EGL platform: wayland

In result eglvivsink always fails with wl_display_connect failed: No such file or directory
I tried:
export FB_MULTI_BUFFER=2
export XDG_RUNTIME_DIR=/var/run/root/1000 
export DISPLAY=:0
tried to use with weston, result was the same.
With fb works fine

**Comment by dv1** [comment]
Closing this since imxeglvivsink no longer exists. waylandsink, kmssink (with force-modesetting set to true) and glimagesink are the alternatives.
