### ISSUE TITLE
imxG2D plugins not getting build on IMX6 SABRE SD with Yocto Dizzy

### ISSUE THREAD

**Issue by phoenix1584** [Freescale/gstreamer-imx#25]
Hi,
I moved to the Community BSP recently from the FSL beta yocto BSP.
I primarily want to consume all available VPU/IPU capabilities via gstreamer.
root@imx6qsabresd:~# gst-launch-1.0 --version
gst-launch-1.0 version 1.4.1
GStreamer 1.4.1

=> But the final BSP built using the fsl-image-multimedia-full is not building all the plugins for my setup.
=> I saw the size related issue regarding the ipusink and hence wanted to try put the g2dvideosink.
=> How is colorspace conversion facilitated by the new set of plugins in gst-1.0 ??
     root@imx6qsabresd:~# gst-inspect | grep csc
     ipucsc.imx:  mfw_ipucsc: IPU-based video converter

Please guide me in getting the entire set of plugins for testing. I am fine with gstreamer 1.2.3 as well, in that case please tell me the way to get older version of gstreamer in Dizzy.

Following are setup details:
BSP:
$ bitbake gstreamer1.0-plugins-imx
Build Configuration:
BB_VERSION        = "1.24.0"
BUILD_SYS         = "i686-linux"
NATIVELSBSTRING   = "Ubuntu-14.04"
TARGET_SYS        = "arm-poky-linux-gnueabi"
MACHINE           = "imx6qsabresd"
DISTRO            = "poky"
DISTRO_VERSION    = "1.7"
TUNE_FEATURES     = "arm armv7a vfp neon callconvention-hard cortexa9"
TARGET_FPU        = "vfp-neon"
meta              
meta-yocto        = "(nobranch):02627ad3d93e8221daf5d178c096ab48a9d1fd68"
meta-oe           
meta-multimedia   = "(nobranch):510b7a9d8d5dda07120df5866507742a626478c1"
meta-fsl-arm      = "(nobranch):caa153361370d69394cf2208b2f4821fda33eba3"
meta-fsl-arm-extra = "(nobranch):eb59dbb9d4372ad531ea6917854b2db97dc7c420"
meta-fsl-demos    = "(nobranch):48cb0bcdd226d2e7eee1fdc222713e1dff93342c"

NOTE: Preparing runqueue
NOTE: Executing SetScene Tasks
NOTE: Executing RunQueue Tasks

IMX6 Board:
root@imx6qsabresd:~# gst-inspect-1.0 | grep imx
imxvpu:  imxvpudec: Freescale VPU video decoder
imxvpu:  imxvpuenc_h263: Freescale VPU h.263 video encoder
imxvpu:  imxvpuenc_h264: Freescale VPU h.264 video encoder
imxvpu:  imxvpuenc_mpeg4: Freescale VPU MPEG-4 video encoder
imxvpu:  imxvpuenc_mjpeg: Freescale VPU motion JPEG video encoder
imxeglvivsink:  imxeglvivsink: Freescale EGL video sink
imxv4l2src:  imxv4l2src: V4L2 CSI Video Source

IPU Error:
0:00:03.551338334   826 0x75c01d20 LOG            imxipublitter ../src/ipu/blitter.c:771:gst_imx_ipu_blitter_blit:<imxipublitter0> task input:  width:  1920  height: 1088  format: 0x30323449  crop: 0,0 1920x1088  phys addr 0x48100000  deinterlace enable 0 motion 0x0
0:00:03.551576334   826 0x75c01d20 LOG            imxipublitter ../src/ipu/blitter.c:780:gst_imx_ipu_blitter_blit:<imxipublitter0> task output:  width:  1920  height: 1080  format: 0x50424752  crop: 0,0 1920x1080  paddr 0x44c00000  rotate: 0
0:00:03.556509334   826 0x75c01d20 ERROR          imxipublitter ../src/ipu/blitter.c:802:gst_imx_ipu_blitter_blit:<imxipublitter0> queuing IPU task failed: Invalid argument

imxipu:  imxipuvideotransform: Freescale IPU video transform element
imxipu:  imxipusink: Freescale IPU video sink

**Comment by dv1** [comment]
How do you build gstreamer-imx ? With the newest Yocto recipes for 0.10.0, the G2D library should have been built as a dependency. If it cannot be found, you won't get G2D elements.

**Comment by phoenix1584** [comment]
Hi,
I added "gstreamer1.0-plugins-imx \" to the local.conf file.
Do I need to check any specific recipe to confirm if G2D dependency is
enabled in my setup.



On Thu, Jan 8, 2015 at 12:43 PM, dv1 <notifications@github.com> wrote:

> How do you build gstreamer-imx ? With the newest Yocto recipes for 0.10.0,
> the G2D library should have been built as a dependency. If it cannot be
> found, you won't get G2D elements.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Freescale/gstreamer-imx/issues/25#issuecomment-69144123>
> .
>



-- 
Regards
Subodh

**Comment by dv1** [comment]
Do you mean you added this to IMAGE_INSTALL? Like this: IMAGE_INSTALL_append = " gstreamer1.0-plugins-imx " ?

If so, try specifying gstreamer1.0-plugins-imx-meta instead.

**Comment by phoenix1584** [comment]
I tried the above option but the plugins for G2D were still not built.
PFA the config I am using, I think I am missing on some parameter.

On Thu, Jan 8, 2015 at 1:47 PM, dv1 <notifications@github.com> wrote:

> Do you mean you added this to IMAGE_INSTALL? Like this:
> IMAGE_INSTALL_append = " gstreamer1.0-plugins-imx " ?
>
> If so, try specifying gstreamer1.0-plugins-imx-meta instead.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Freescale/gstreamer-imx/issues/25#issuecomment-69148672>
> .
>



-- 
Regards
Subodh

**Comment by dv1** [comment]
Can you paste the log.configure file somewhere? A log.configure file is generated for every recipe you build in Yocto. It should be somewhere in tmp/work/<your machine name>/gstreamer1.0-plugins-imx/temp/log.configure .

**Comment by phoenix1584** [comment]
PFA the log, let me know incase I should grep for something specific in my
setup to get more clues.
Pasting logs as a precaution in case attachment fails

DEBUG: Executing python function sysroot_cleansstate
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/libgstimxcommon.so
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/libgstimxcommon.so.0.9.9
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/libgstimxcommon.so.0
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/gstreamer-1.0/libgstimxeglvivsink.so
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/gstreamer-1.0/libgstimxipu.so
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/gstreamer-1.0/libgstimxvpu.so
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/gstreamer-1.0/libgstimxv4l2src.so
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/sysroot-providers/gstreamer1.0-plugins-imx
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/gstreamer-1.0/
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/sysroot-providers/
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/lib/
DEBUG: Removing manifest:
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd/usr/
DEBUG: Python function sysroot_cleansstate finished
DEBUG: Executing shell function do_configure
Setting top to                           :
/Data1/yocto/fsl-community-bsp/build/tmp/work/imx6qsabresd-poky-linux-gnueabi/gstreamer1.0-plugins-imx/0.9.9-r0/git
Setting out to                           :
/Data1/yocto/fsl-community-bsp/build/tmp/work/imx6qsabresd-poky-linux-gnueabi/gstreamer1.0-plugins-imx/0.9.9-r0/git/build
Checking for 'gcc' (c compiler)          : arm-poky-linux-gnueabi-gcc
-march=armv7-a -mthumb-interwork -mfloat-abi=hard -mfpu=neon
-mtune=cortex-a9
--sysroot=/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/imx6qsabresd
Testing compiler flags -O2 -pipe -g -feliminate-unused-debug-types and
linker flags -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed : yes
Checking for compiler switch -O2
                                                      : yes
Checking for compiler switch -DPIC
                                                      : yes
Checking for compiler switch -fPIC
                                                      : yes
Checking for compiler switch -std=gnu99
                                                     : yes
Checking for compiler switch -Wall
                                                      : yes
Checking for compiler switch -Wextra
                                                      : yes
Checking for library m
                                                      : yes
Checking for library pthread
                                                      : yes
Checking for program pkg-config
                                                     :
/Data1/yocto/fsl-community-bsp/build/tmp/sysroots/i686-linux/usr/bin/pkg-config
Checking for 'gstreamer-1.0 >= 1.2.0'
                                                     : yes
Checking for 'gstreamer-base-1.0 >= 1.2.0'
                                                      : yes
Checking for 'gstreamer-video-1.0 >= 1.2.0'
                                                     : yes
checking whether or not the kernel version is greater than 3.5.0
                                                      : yes
checking for linux/fb.h and the IPU header linux/ipu.h
                                                      : yes
IPU sink will be built
Checking for 'libfslvpuwrap >= 1.0.45'
                                                      : yes
Checking for library X11
                                                      : yes
Checking for header X11/Xlib.h
                                                      : yes
Checking for library ['EGL']
                                                      : yes
Checking for header EGL/eglvivante.h
                                                      : yes
Checking for header EGL/egl.h
                                                     : yes
Checking for library GLESv2
                                                     : yes
Checking for header GLES2/gl2.h
                                                     : yes
Checking for header ['GLES2/gl2.h', 'GLES2/gl2ext.h']
                                                     : yes
Checking for GLES texture format VIV_I420
                                                     : yes
Checking for GLES texture format VIV_YV12
                                                     : yes
Checking for GLES texture format VIV_NV12
                                                     : yes
Checking for GLES texture format VIV_NV21
                                                     : yes
Checking for GLES texture format VIV_YUY2
                                                     : yes
Checking for GLES texture format VIV_UYVY
                                                     : yes
EGL sink with Vivante direct textures will be built
Selected EGL platform: x11
'configure' finished successfully (2.266s)
DEBUG: Shell function do_configure finished
DEBUG: Executing python function do_qa_configure
NOTE: Checking autotools environment for common misconfiguration
NOTE: gstreamer1.0-plugins-imx: md5 checksum matched for
file://LICENSE;md5=55ca817ccb7d5b5b66355690e9abc605
DEBUG: Python function do_qa_configure finished



On Thu, Jan 8, 2015 at 3:03 PM, dv1 <notifications@github.com> wrote:

> Can you paste the log.configure file somewhere? A log.configure file is
> generated for every recipe you build in Yocto. It should be somewhere in
> tmp/work//gstreamer1.0-plugins-imx/temp/log.configure .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Freescale/gstreamer-imx/issues/25#issuecomment-69155679>
> .
>



-- 
Regards
Subodh

**Comment by dv1** [comment]
Well, you are using gstreamer-imx 0.9.9 , which does not contain G2D. Update the recipe to 0.10.0. meta-fsl-arm recently got an update.

**Comment by phoenix1584** [comment]
should I just do a repo-sync ??

On Thu, Jan 8, 2015 at 3:17 PM, dv1 <notifications@github.com> wrote:

> Well, you are using gstreamer-imx 0.9.9 , which does not contain G2D.
> Update the recipe to 0.10.0. meta-fsl-arm recently got an update.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Freescale/gstreamer-imx/issues/25#issuecomment-69157160>
> .
>



-- 
Regards
Subodh

**Comment by phoenix1584** [comment]
repo sync results in the following error for meta-fsl-arm.

/Data1/yocto/fsl-community-bsp$ repo sync
Fetching project fsl-community-bsp-base
Fetching project Documentation
Fetching project meta-fsl-demos
Fetching project meta-fsl-arm
Fetching projects:  14% (1/7)  Fetching project poky
Fetching projects:  28% (2/7)  Fetching project meta-openembedded
Fetching projects:  42% (3/7)  Fetching project meta-fsl-arm-extra
Fetching projects:  85% (6/7)  remote: Counting objects: 25, done.
remote: Compressing objects: 100% (16/16), done.
remote: Total 16 (delta 14), reused 0 (delta 0)
Unpacking objects: 100% (16/16), done.
From git://git.yoctoproject.org/poky
   130958c..97d44bf  master     -> yocto/master
Fetching projects: 100% (7/7), done.
Traceback (most recent call last):
  File "/Data1/yocto/fsl-community-bsp/.repo/repo/main.py", line 500, in
<module>
    _Main(sys.argv[1:])
  File "/Data1/yocto/fsl-community-bsp/.repo/repo/main.py", line 476, in
_Main
    result = repo._Run(argv) or 0
  File "/Data1/yocto/fsl-community-bsp/.repo/repo/main.py", line 155, in
_Run
    result = cmd.Execute(copts, cargs)
  File "/Data1/yocto/fsl-community-bsp/.repo/repo/subcmds/sync.py", line
675, in Execute
    project.Sync_LocalHalf(syncbuf)
  File "/Data1/yocto/fsl-community-bsp/.repo/repo/project.py", line 1204,
in Sync_LocalHalf
    lost = self._revlist(not_rev(revid), HEAD)
  File "/Data1/yocto/fsl-community-bsp/.repo/repo/project.py", line 2241,
in _revlist
    return self.work_git.rev_list(*a, **kw)
  File "/Data1/yocto/fsl-community-bsp/.repo/repo/project.py", line 2435,
in rev_list
    p.stderr))
error.GitError: meta-fsl-arm rev-list
(u'^7539a694f3d01f1ab5162bfee16b0327f827c4f7', 'HEAD', '--'): fatal: bad
object 7539a694f3d01f1ab5162bfee16b0327f827c4f7



On Thu, Jan 8, 2015 at 3:18 PM, Subodh Chiwate <subodh.austin@gmail.com>
wrote:

> should I just do a repo-sync ??
>
> On Thu, Jan 8, 2015 at 3:17 PM, dv1 <notifications@github.com> wrote:
>
>> Well, you are using gstreamer-imx 0.9.9 , which does not contain G2D.
>> Update the recipe to 0.10.0. meta-fsl-arm recently got an update.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Freescale/gstreamer-imx/issues/25#issuecomment-69157160>
>> .
>>
>
>
>
> --
> Regards
> Subodh
>



-- 
Regards
Subodh

**Comment by dv1** [comment]
Hm, that I do not know. You can try to replace gstreamer1.0-plugins-imx_0.9.9.bb with gstreamer1.0-plugins-imx_0.10.0.bb manually though. The latter you can find at https://github.com/Freescale/meta-fsl-arm/blob/dizzy/recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_0.10.0.bb . Other than that, you should ask in the meta-freescale mailing list about updating meta-fsl-arm if you wanna do that.

**Comment by phoenix1584** [comment]
Okay ..will try the manual switch and chk if it the build process succeed.
Will update issue with results.
Thanks.

On Thu, Jan 8, 2015 at 3:41 PM, dv1 <notifications@github.com> wrote:

> Hm, that I do not know. You can try to replace
> gstreamer1.0-plugins-imx_0.9.9.bb with gstreamer1.0-plugins-imx_0.10.0.bb
> manually though. The latter you can find at
> https://github.com/Freescale/meta-fsl-arm/blob/dizzy/recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_0.10.0.bb
> . Other than that, you should ask in the meta-freescale mailing list about
> updating meta-fsl-arm if you wanna do that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Freescale/gstreamer-imx/issues/25#issuecomment-69159761>
> .
>



-- 
Regards
Subodh

**Comment by phoenix1584** [comment]
Manual update worked. You may mark the issue resolved.
Thanks for the prompt analysis and responses.

root@imx6qsabresd:~# gst-inspect-1.0 | grep imx
imxv4l2src:  imxv4l2src: V4L2 CSI Video Source
imxg2d:  imxg2dvideosink: Freescale G2D video sink
imxg2d:  imxg2dvideotransform: Freescale G2D video transform
imxipu:  imxipuvideotransform: Freescale IPU video transform
imxipu:  imxipuvideosink: Freescale IPU video sink
imxvpu:  imxvpudec: Freescale VPU video decoder
imxvpu:  imxvpuenc_h263: Freescale VPU h.263 video encoder
imxvpu:  imxvpuenc_h264: Freescale VPU h.264 video encoder
imxvpu:  imxvpuenc_mpeg4: Freescale VPU MPEG-4 video encoder
imxvpu:  imxvpuenc_mjpeg: Freescale VPU motion JPEG video encoder
imxpxp:  imxpxpvideosink: Freescale PxP video sink
imxpxp:  imxpxpvideotransform: Freescale PxP video transform
imxaudio:  imxuniaudiodec: Freescale i.MX uniaudio decoder
imxeglvivsink:  imxeglvivsink: Freescale EGL video sink




On Thu, Jan 8, 2015 at 3:43 PM, Subodh Chiwate <subodh.austin@gmail.com>
wrote:

> Okay ..will try the manual switch and chk if it the build process succeed.
> Will update issue with results.
> Thanks.
>
> On Thu, Jan 8, 2015 at 3:41 PM, dv1 <notifications@github.com> wrote:
>
>> Hm, that I do not know. You can try to replace
>> gstreamer1.0-plugins-imx_0.9.9.bb with gstreamer1.0-plugins-imx_0.10.0.bb
>> manually though. The latter you can find at
>> https://github.com/Freescale/meta-fsl-arm/blob/dizzy/recipes-multimedia/gstreamer/gstreamer1.0-plugins-imx_0.10.0.bb
>> . Other than that, you should ask in the meta-freescale mailing list about
>> updating meta-fsl-arm if you wanna do that.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Freescale/gstreamer-imx/issues/25#issuecomment-69159761>
>> .
>>
>
>
>
> --
> Regards
> Subodh
>



-- 
Regards
Subodh
