### ISSUE TITLE
Gstreamer Pipeline gives segmentation fault on random basis

### ISSUE THREAD

**Issue by nikitapanchal09** [Freescale/gstreamer-imx#250]
Hi,

I am working on Gstreamer on an imx6-Dualite processor having Linux and GStreamer version as following:
_Debian: Debian GNU/Linux 9 (stretch)
Linux Kernel: Linux var-som-mx6 4.9.88-10182-gec7d7d8-dirty #3 SMP PREEMPT Mon Sep 23 14:19:33 IST 2019 armv7l GNU/Linux
Gstreamer: 1.10.4_

I have installed gasteamer using following command:
_apt-get libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools  gstreamer1.0-alsa_

When I execute the following command to stream my live video on LCD(MIPI-DSI) some times it crashes(mostly when power on board first time).
Command: **GST_DEBUG=2,*imx*:9 gst-launch-1.0 imxv4l2videosrc ! textoverlay text="1234567890" name=overlay valignment=top halignment=left font-desc="Sans, 22" shaded-background=yes ! autovideosink**

Please find the output as below:
_root@var-som-mx6:~# GST_DEBUG=2,*imx*:9 gst-launch-1.0 imxv4l2videosrc ! textover
rlay text="sensit 1234567890" name=overlay valignment=top halignment=left font-de
esc="Sans, 22" shaded-background=yes ! autovideosink
ioctl_dev_init: AR1335 : Started Loading BootData....
ioctl_dev_init: AR1335 : Loading BootData Completed....
0:00:08.334294668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:647:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps filter (NULL)
0:00:08.334589335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:660:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps video/x-raw, format=(string){ UYVY, I420 }, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string){ progressive, interleaved }, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:08.335079335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:647:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps filter (NULL)
0:00:08.335251668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:660:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps video/x-raw, format=(string){ UYVY, I420 }, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string){ progressive, interleaved }, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:08.335724668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:647:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps filter (NULL)
0:00:08.335895001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:660:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps video/x-raw, format=(string){ UYVY, I420 }, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string){ progressive, interleaved }, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:08.336401668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:647:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps filter (NULL)
0:00:08.336568001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:660:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps video/x-raw, format=(string){ UYVY, I420 }, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string){ progressive, interleaved }, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
Setting pipeline to PAUSED ...
No protocol specified
0:00:08.384264001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[31;01mERROR  \0x1b[00m \0x1b[00m  imxeglplatform_x11 egl_platform_x11.c:90:gst_imx_egl_viv_sink_egl_platform_create:\0x1b[00m could not open X display
0:00:08.406650001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m imxblittervideosink video_sink.c:1013:gst_imx_blitter_video_sink_open_framebuffer_device:<autovideosink0-actual-sink-imxg2dvideo>\0x1b[00m opening framebuffer /dev/fb0
0:00:08.406797335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m imxblittervideosink video_sink.c:1358:gst_imx_blitter_video_sink_get_format_from_fb:<autovideosink0-actual-sink-imxg2dvideo>\0x1b[00m framebuffer uses 32 bpp (sizes: r 8 g 8 b 8 a 8  offsets: r 16 g 8 b 0 a 24) => format BGRA
0:00:08.407089335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m imxblittervideosink video_sink.c:1122:gst_imx_blitter_video_sink_open_framebuffer_device:<autovideosink0-actual-sink-imxg2dvideo>\0x1b[00m framebuffer FD is 7
0:00:08.407419001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m imxphysmemallocator phys_mem_allocator.c:84:gst_imx_phys_mem_allocator_init:<GstImxPhysMemAllocator@0x1e316e8>\0x1b[00m initializing physical memory allocator
0:00:08.407644335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mTRACE  \0x1b[00m \0x1b[00m          imxblitter blitter.c:65:gst_imx_blitter_init:<GstImxBlitter@0x20d6010>\0x1b[00m initializing blitter base
0:00:08.407742668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m imxphysmemallocator phys_mem_allocator.c:139:gst_imx_phys_mem_allocator_alloc_internal:<imxg2dallocator0>\0x1b[00m alloc_internal called: maxsize: 16, align: 0, offset: 0, size: 16
0:00:08.676946335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxg2dallocator allocator.c:91:gst_imx_g2d_alloc_phys_mem:<imxg2dallocator0>\0x1b[00m allocated 16 bytes of physical memory, vaddr 0x6dafd000 paddr 0x3c590000
0:00:08.677063001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m imxphysmemallocator phys_mem_allocator.c:174:gst_imx_phys_mem_allocator_alloc:<imxg2dallocator0>\0x1b[00m allocated memory block 0x20cd6e8 at phys addr 0x3c590000 with 16 bytes
0:00:08.677153668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m       imxg2dblitter blitter.c:514:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0>\0x1b[00m number of planes: 1
0:00:08.677253001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m       imxg2dblitter blitter.c:547:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0>\0x1b[00m surface stride: 480 pixels  width: 480 pixels height: 800 pixels
0:00:08.677323335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m imxblittervideosink video_sink.c:686:gst_imx_blitter_video_sink_change_state:<autovideosink0-actual-sink-imxg2dvideo>\0x1b[00m cleaning up any previous vsync by flipping to page 0
0:00:08.677374001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m imxblittervideosink video_sink.c:1219:gst_imx_blitter_video_sink_select_fb_page:<autovideosink0-actual-sink-imxg2dvideo>\0x1b[00m switching to page 0
0:00:08.677427668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m       imxg2dblitter blitter.c:514:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0>\0x1b[00m number of planes: 1
0:00:08.677477335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m       imxg2dblitter blitter.c:547:gst_imx_g2d_blitter_set_surface_params:<imxg2dblitter0>\0x1b[00m surface stride: 480 pixels  width: 480 pixels height: 800 pixels
0:00:08.678689335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:326:gst_imx_v4l2src_start:<imxv4l2videosrc0>\0x1b[00m start
0:00:08.827290335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mWARN   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:124:gst_imx_v4l2src_is_tvin:<imxv4l2videosrc0>\0x1b[00m VIDIOC_QUERYSTD failed: Inappropriate ioctl for device
0:00:08.827406335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mWARN   \0x1b[00m \0x1b[00m     imxv4l2ERROR: v4l2 capture: unsupported ioctrl!
videosrc v4l2src.c:128:gst_imx_v4l2src_is_tvin:<imxv4l2videosrc0>\0x1b[00m VIDIOC_G_STD failed: Inappropriate ioctl for device
0:00:08.827474001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:213:gst_imx_v4l2src_capture_setup:<imxv4l2videosrc0>\0x1b[00m pixelformat = 842093913  field = 0
0:00:08.827539335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:227:gst_imx_v4l2src_capture_setup:<imxv4l2videosrc0>\0x1b[00m capture mode 0: 640x480
0:00:08.867507668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:647:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps filter (NULL)
0:00:08.867868001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:660:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0>\0x1b[00m get caps video/x-raw, format=(string){ UYVY, I420 }, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string){ progressive, interleaved }, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:08.869283335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:265:gst_imx_v4l2src_capture_setup:<imxv4l2videosrc0>\0x1b[00m allowed src caps: video/x-raw, format=(string){ UYVY, I420 }, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string){ progressive, interleaved }, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ] -> allowed formats: video/x-raw, format=(string){ UYVY, I420 }, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string){ progressive, interleaved }, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:08.869751335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:291:gst_imx_v4l2src_capture_setup:<imxv4l2videosrc0>\0x1b[00m using "UYVY" pixel format
0:00:08.870031668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m         imxfdobject fd_object.c:59:gst_fd_object_new:\0x1b[00m new 0x1f87e00 with FD 5
0:00:08.870177001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:344:gst_imx_v4l2src_start:<imxv4l2videosrc0>\0x1b[00m width = 640
0:00:08.870272668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:345:gst_imx_v4l2src_start:<imxv4l2videosrc0>\0x1b[00m height = 480
0:00:08.870361001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:346:gst_imx_v4l2src_start:<imxv4l2videosrc0>\0x1b[00m sizeimage = 614400
0:00:08.870447335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:347:gst_imx_v4l2src_start:<imxv4l2videosrc0>\0x1b[00m pixelformat = 1498831189
0:00:08.870540001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:1213:v4l2_s_ctrl:<imxv4l2videosrc0>\0x1b[00m VIDIOC_S_CTRL(V4L2_CID_FOCUS_AUTO, 0)
0:00:08.870654001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:1220:v4l2_s_ctrl:<imxv4l2videosrc0>\0x1b[00m VIDIOC_S_CTRL(V4L2_CID_FOCUS_AUTO, 0) failed
0:00:08.870757335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:1213:v4l2_s_ctrl:<imxv4l2videosrc0>\0x1b[00m VIDIOC_S_CTRL(V4L2_CID_AUTO_FOCUS_STOP, 0)
0:00:08.870871335 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:1220:v4l2_s_ctrl:<imxv4l2videosrc0>\0x1b[00m VIDIOC_S_CTRL(V4L2_CID_AUTO_FOCUS_STOP, 0) failed
0:00:08.877087668 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:1198:v4l2_g_ctrl:<imxv4l2videosrc0>\0x1b[00m VIDIOC_G_CTRL(V4L2_CID_3A_LOCK) failed
0:00:08.877318001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:1213:v4l2_s_ctrl:<imxv4l2videosrc0>\0x1b[00m VIDIOC_S_CTRL(V4L2_CID_FOCUS_RANGE, 0)
0:00:08.877467001 \0x1b[333m  482\0x1b[00m  0x20bb4e0 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:1220:v4l2_s_ctrl:<imxv4l2videosrc0>\0x1b[00m VIDIOC_S_CTRL(V4L2_CID_FOCUS_RANGE, 0) failed
Pipeline is live and does not need PREROLL ...
0:00:08.880160335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:637:gst_imx_v4l2src_negotiate:<imxv4l2videosrc0>\0x1b[00m negotiated caps video/x-raw, format=(string)UYVY, width=(int)640, height=(int)480, interlace-mode=(string)progressive, framerate=(fraction)30/1, pixel-aspect-ratio=(fraction)1/1
0:00:09.210711335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[36mINFO   \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:669:gst_imx_v4l2src_set_caps:<imxv4l2videosrc0>\0x1b[00m set caps video/x-raw, format=(string)UYVY, width=(int)640, height=(int)480, interlace-mode=(string)progressive, framerate=(fraction)30/1, pixel-aspect-ratio=(fraction)1/1
Setting pipeline to PLAYING ...
0:00:09.215272668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:389:gst_imx_v4l2_buffer_pool_init:<GstImxV4l2BufferPool@0x20c4af8>\0x1b[00m initializing V4L2 buffer pool
New clock: GstSystemClock
0:00:09.215727001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:112:gst_imx_v4l2_buffer_pool_set_config:<imxv4l2bufferpool0>\0x1b[00m set_config: size 614400, min 6, max 0
0:00:09.251743335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:329:gst_imx_v4l2_buffer_pool_start:<imxv4l2bufferpool0>\0x1b[00m start
0:00:09.251873668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:158:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m alloc 0 0x20d5e70
0:00:09.252060001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:189:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m driver name: "mxc_v4l2"  card type: "ar1335_mipi"
0:00:09.252132001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:205:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m vbuffer virt addr 0x6c769000 phys addr 0x3c100000
0:00:09.252200335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:313:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0>\0x1b[00m qbuf 0 0x20d5e70
0:00:09.252260668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:158:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m alloc 1 0x20d5f10
0:00:09.252363335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:189:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m driver name: "mxc_v4l2"  card type: "ar1335_mipi"
0:00:09.252427001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:205:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m vbuffer virt addr 0x6c56a000 phys addr 0x3c200000
0:00:09.252486335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:313:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0>\0x1b[00m qbuf 1 0x20d5f10
0:00:09.252545335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:158:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m alloc 2 0x6d008028
0:00:09.252638001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:189:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m driver name: "mxc_v4l2"  card type: "ar1335_mipi"
0:00:09.252697001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:205:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m vbuffer virt addr 0x6c4d4000 phys addr 0x45800000
0:00:09.252759001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:313:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0>\0x1b[00m qbuf 2 0x6d008028
0:00:09.252818001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:158:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m alloc 3 0x6d0080c8
0:00:09.252908001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:189:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m driver name: "mxc_v4l2"  card type: "ar1335_mipi"
0:00:09.583783335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:205:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m vbuffer virt addr 0x6c43e000 phys addr 0x45900000
0:00:09.583965001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:313:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0>\0x1b[00m qbuf 3 0x6d0080c8
0:00:09.584104668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:158:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m alloc 4 0x6d008168
0:00:09.584332335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:189:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m driver name: "mxc_v4l2"  card type: "ar1335_mipi"
0:00:09.584458668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:205:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m vbuffer virt addr 0x6c3a8000 phys addr 0x45a00000
0:00:09.584583668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:313:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0>\0x1b[00m qbuf 4 0x6d008168
0:00:09.584704668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:158:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m alloc 5 0x6d008208
0:00:09.584887335 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:189:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m driver name: "mxc_v4l2"  card type: "ar1335_mipi"
0:00:09.585006668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:205:gst_imx_v4l2_buffer_pool_alloc_buffer:<imxv4l2bufferpool0>\0x1b[00m vbuffer virt addr 0x6c312000 phys addr 0x45b00000
0:00:09.585127668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:313:gst_imx_v4l2_buffer_pool_release_buffer:<imxv4l2bufferpool0>\0x1b[00m qbuf 5 0x6d008208
0:00:09.615323668 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m   imxv4l2bufferpool v4l2_buffer_pool.c:279:gst_imx_v4l2_buffer_pool_acquire_buffer:<imxv4l2bufferpool0>\0x1b[00m dqbuf 0 0x20d5e70
0:00:09.615525001 \0x1b[333m  482\0x1b[00m  0x1fa3950 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:449:gst_imx_v4l2src_fill:<imxv4l2videosrc0>\0x1b[00m fill
**Caught SIGSEGV**
#0  0x76d2e730 in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x76dea89a in ?? () from /lib/arm-linux-gnueabihf/libglib-2.0.so.0
Spinning.  Please run 'gdb gst-launch-1.0 482' to continue debugging, Ctrl-C to quit, or Ctrl-\ to dump core._

Kindly help to solve this issue.
Thanks!

**Comment by tyounger24** [comment]
I would suggest trying to use imxg2dtextoverlay instead of textoverlay.
