### ISSUE TITLE
When will "v2" be available in a Yocto Recipe?

### ISSUE THREAD

**Issue by jobusch** [Freescale/gstreamer-imx#252]
Hey,
I was just wondering when "v2" will be available in a Yocto Recipe for IMX8M.
Thanks for the good work!

**Comment by dv1** [comment]
Hi,

well, it is mainly a matter of time (or lack thereof). [See this reply for more.](https://github.com/Freescale/gstreamer-imx/issues/242#issuecomment-561727760)

**Comment by jobusch** [comment]
Thanks for your response! 
So actually I found out using a newer Linux Kernel the gstreamer-imx-plugins are available for Yocto. Maybe it already uses the version v2? Or does the master version also work with the imx8m? What is the difference between master and v2? From your response in the other thread I only get that there is some extra the imx8m does not need anymore?

Sorry I am pretty new to that topic. Thank you for your time!

**Comment by dv1** [comment]
v2 is now merged into master, and meta-freescale's recipe got updated.
