### ISSUE TITLE
PXP support for linux-fslc kernel

### ISSUE THREAD

**Issue by QB4-dev** [Freescale/gstreamer-imx#253]
In new kernel versions the pxp-dma driver which was creating node **/dev/pxp_device**  has been removed.

Now there is single PXP driver here:
linux-fslc/drivers/media/platform/imx-pxp.c 
but...
`
imxpxpdevice device.c:46:gst_imx_pxp_open: could not open /dev/pxp_device: No such file or directory
`
 /dev/pxp_device is not created even if pxp driver is loaded - it is creates /dev/video0 device

Any plans for new kernels imxpxpvideosink support?

**Comment by dv1** [comment]
/dev/video0 is a Video4Linux2 device, so I don't think this would work. Regarding the kernels, one of the -imx branches in linux-fslc should have the PxP device, shouldn't it? Also keep in mind that PxP is not available on Dual and Quad i.MX6 variants.

**Comment by QB4-dev** [comment]
Hello
>  Regarding the kernels, one of the -imx branches in linux-fslc should have the PxP device, shouldn't it?

Yes, you are right, I just noticed huge difference between pure -fslc and -imx branch:
In new -flsc kernels pxp-dma driver was missing, also pxp node was removed from device-tree:

- 5.0.x+fslc (no pxp node and no pxp-dma driver)
  https://github.com/Freescale/linux-fslc/blob/5.0.x+fslc/arch/arm/boot/dts/imx6ul.dtsi 

and for contrast
- 4.14-2.0.x-imx( pxp node in devicetree and no pxp-dma driver available)
https://github.com/Freescale/linux-fslc/blob/4.14-2.0.x-imx/arch/arm/boot/dts/imx6ul.dtsi
https://github.com/Freescale/linux-fslc/tree/4.14-2.0.x-imx/drivers/dma/pxp

Thank you for tips, I'll use older -imx kernel with PXP DMA support
