### ISSUE TITLE
Building gstreamer-imx plugins for Android

### ISSUE THREAD

**Issue by Vishnu-R-95** [Freescale/gstreamer-imx#255]
I have built the gstreamer-imx plugins for android and found that the plugins were built as static libraries.
But these plugins, built as static libraries, were not found by gst-inspect-1.0 when I tried the command using adb-shell on the Android emulator.
I think that the gst-inspect-1.0 only identifies the plugins that are saved as shared libraries.
Will these plugins work if they are built as shared libraries instead of static ones?

**Comment by angolini** [comment]
@dv1 do you think this questions is easy to answer?

**Comment by dv1** [comment]
@Vishnu-R-95 in case you are still using this, note that this is not gstreamer-imx specific. From what I recall, when building for Android, you *have* to build statically on Android. Also see: https://gstreamer.freedesktop.org/documentation/installing/for-android-development.html?gi-language=c
