### ISSUE TITLE
Display + record with overlay using imxg2dtimeoverlay

### ISSUE THREAD

**Issue by jigneshpatel47** [Freescale/gstreamer-imx#258]
Hi,

I am working on GStreamer IMX pipeline to display + record video with overlay. I have used "**imxg2dtimeoverlay**" for overlay on camera stream.

I have error using following command:
 **gst-launch-1.0 imxv4l2videosrc device=/dev/video0 imx-capture-mode=0 fps-n=15 ! tee name=t t. ! queue !  imxipuvideotransform ! imxg2dtimeoverlay valignment=top halignment=left font-desc="Sans, 72" t. ! queue ! imxvpuenc_h264 bitrate=10000  ! filesink location=test.avi  t. ! queue leaky=1  ! imxipuvideotransform ! imxipuvideosink  framebuffer=/dev/fb0 use-vsync=true sync=false**

Setting pipeline to PAUSED ...
0:00:00.252117756  2930  0x1fb4d00 WARN         imxv4l2videosrc v4l2src.c:124:gst_imx_v4l2src_is_tvin:<imxv4l2videosrc0> VIDIOC_QUERYSTD failed: Inappropriate ioctl for device
0:00:00.252256422  2930  0x1fb4d00 WARN         imxv4l2videosrc v4l2src.c:128:gst_imx_v4l2src_is_tvin:<imxv4l2videosrc0> VIDIOC_G_STD failed: Inappropriate ioctl for device
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
[INFO]	ringBufferEnable 0, chromaInterleave 0, mapType 0, linear2TiledEnable 1
0:00:00.723608763  2930  0x1f98580 WARN                GST_PADS gstpad.c:4106:gst_pad_peer_query:<imxipuvideotransform0:src> could not send sticky events
0:00:00.931901403  2930  0x1f988c0 WARN                 basesrc gstbasesrc.c:2950:gst_base_src_loop:<imxv4l2videosrc0> error: Internal data stream error.
0:00:00.932089068  2930  0x1f988c0 WARN                 basesrc gstbasesrc.c:2950:gst_base_src_loop:<imxv4l2videosrc0> error: streaming stopped, reason not-negotiated (-4)
0:00:00.932736065  2930  0x1f988c0 WARN                   queue gstqueue.c:989:gst_queue_handle_sink_event:<queue0> error: Internal data stream error.
0:00:00.932927064  2930  0x1f988c0 WARN                   queue gstqueue.c:989:gst_queue_handle_sink_event:<queue0> error: streaming stopped, reason not-negotiated (-4)
ERROR: from element /GstPipeline:pipeline0/GstImxV4l2VideoSrc:imxv4l2videosrc0: Internal data stream error.
Additional debug info:
gstbasesrc.c(2950): gst_base_src_loop (): /GstPipeline:pipeline0/GstImxV4l2VideoSrc:imxv4l2videosrc0:
streaming stopped, reason not-negotiated (-4)
Execution ended after 0:00:00.624233254
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

Is there any missing in pipeline?
How can I display + record video with overlay using imxg2dtimeoverlay.

Thanks & Regards,
Jignesh Patel

**Comment by bmx666** [comment]
Hi @jigneshpatel47
Can you check this https://github.com/Freescale/gstreamer-imx/pull/147#issuecomment-311968885 ?
