### ISSUE TITLE
Gstreamer Android vpudec issue

### ISSUE THREAD

**Issue by abeeshmp** [Freescale/gstreamer-imx#259]
Hi , 

I tried to get the vpudec element in the Anrdoid runs on variscite Reference board. 

I used 

GST ANDROID BINARY : gstreamer-1.0-android-universal-1.10.0.tar.bz2
NDK : android-ndk-r15c-linux-x86_64.zip

I am getting the error . 
**ERROR : specified instance size for type 'GstImxVpuDecoder' is smaller than the parent type's 'GstVideoDecoder' instance size**

I tried with latest NDK and Gstreamer android binary release also. 

Please help me to solve this issue.

I am ready to give more details if needed.

**Comment by angolini** [comment]
As far as I know Android is not yet supported (I'm telling from the README TODO section)
