### ISSUE TITLE
Detect memory leak in uniaudio_decoder.c

### ISSUE THREAD

**Issue by supercatexpert** [Freescale/gstreamer-imx#26]
After updated to the latest gstreamer-imx, I found a critical memory leak in gst_imx_audio_uniaudio_dec_handle_frame, then I found the out_buf of imx_audio_uniaudio_dec->codec->decode_frame() (line 496) is not freed after usage.

Should I use free() or something to free it?

**Comment by supercatexpert** [comment]
I tried to add gst_imx_audio_uniaudio_dec_free(out_buf); at line 515, and it really works.

**Comment by dv1** [comment]
Thanks! Please send in a merge request so I can include this patch. But don't use free() directly. Use gst_imx_audio_uniaudio_dec_free() instead, since the uniaudio wrapper uses gst_imx_audio_uniaudio_dec_malloc() for allocating. If these functions internally ever use anything other than malloc/free, we'd have a mismatch.

**Comment by supercatexpert** [comment]
diff --git a/src/audio/uniaudio_decoder.c b/src/audio/uniaudio_decoder.c
index a0b5acd..f9e58c6 100644
--- a/src/audio/uniaudio_decoder.c
+++ b/src/audio/uniaudio_decoder.c
@@ -510,6 +510,11 @@ static GstFlowReturn gst_imx_audio_uniaudio_dec_handle_frame(GstAudioDecoder *de
                        gst_adapter_push(imx_audio_uniaudio_dec->out_adapter, tmp_buf);
                }
 
+               if( out_buf != NULL)
+               {
+                       gst_imx_audio_uniaudio_dec_free(out_buf);
+               }
+
                if ((buffer != NULL) && (offset == in_map.size))
                {
                        dec_loop = FALSE;

**Comment by dv1** [comment]
I rather meant a patch formatted like the ones produced by the "git format-patch" command :) Example: https://bug-61355-attachments.webkit.org/attachment.cgi?id=110273
I could add this line myself, but I'd prefer to have your name in the git commit. After all, you fixed it.

**Comment by supercatexpert** [comment]
I have updated the patch, thank you.

**Comment by dv1** [comment]
Pushed, thanks.
