### ISSUE TITLE
imxipuvideotransform mess with the video when downscaling

### ISSUE THREAD

**Issue by Pehoh** [Freescale/gstreamer-imx#261]
Hello,
I'm facing an issue with imxipuvideotransfrom since version 0.13.0.
We were en pyro branch of Yocto, with 0.12.2 version of gstreamer-imx, and the downscaling was working fine.
Since we moved to Warrior branch, the downscaling does not work well anymore.
The image is cut in multiple pieces, and scrolls.
The minimum pipeline to obtain the issue is the following one (on 0.13.0):

~~~
 gst-launch-1.0 imxv4l2videosrc device=/dev/video0 \
 ! video/x-raw, format=I420, width=1920, height=1080 \
 ! queue \
 ! imxipuvideotransform \
 ! queue \
 ! video/x-raw, width=1280, height=720, format=I420 \
 ! imxg2dvideosink use-vsync=true
~~~
The input source is in 1920x1080.
By removing the queues, the behavior change, the scrolling is no more present, but the video is still cut in multiple pieces.
Did you encounter this issue? I know that the IPU is tricky, but I need to downscale the video in I420 (for the encoder), and the IPU is the only hardware element that fits my needs.

**Comment by angolini** [comment]
A v2.0.0 was released in 2021. Would you, please, retest using the latest release and update the status of this issue here? @Pehoh
