### ISSUE TITLE
imx8 Gstreamer Support 

### ISSUE THREAD

**Issue by avrdct** [Freescale/gstreamer-imx#264]
As per the documentation gstreamer-imx is tested only in iMX 6, iMx 7. We are planning to use IMX8 Mini Quad for our development, whether the gstremer support is available for the same. We are planning to use mainly imxvideoconvert, vpuenc_h264 pluggins.  

Thanks
Abhilash

**Comment by dv1** [comment]
imx8 support is in now. If you are still working on this, it may be an option now.
