### ISSUE TITLE
Kernel crash with two imxv4l2videosrc

### ISSUE THREAD

**Issue by garygumdrops** [Freescale/gstreamer-imx#274]
Hi

I am getting a [kernel crash](https://github.com/Freescale/gstreamer-imx/files/5218205/kernel_crash1.txt) when using the following pipeline with two imxv4l2videosrc blocks:

gst-launch-1.0 -v imxg2dcompositor name=c \
      sink_0::xpos=0 sink_0::ypos=0 sink_0::width=400 sink_0::height=480 \
      sink_1::xpos=400 sink_1::ypos=0 sink_1::width=400 sink_1::height=480 ! \
    queue2 ! "video/x-raw, width=800, height=480" ! imxg2dvideosink use-vsync=true \
  imxv4l2videosrc device=/dev/video0 imx-capture-mode=0 fps=15 ! imxipuvideotransform ! "video/x-raw, width=400, height=480" ! c.sink_0 \
  imxv4l2videosrc device=/dev/video0 imx-capture-mode=0 fps=15 ! imxipuvideotransform ! "video/x-raw, width=400, height=480" ! c.sink_1

**Comment by dv1** [comment]
The driver is very, very buggy and racy. It is entirely possible that two instances cause internal race conditions that lead to this crash. Unfortunately, fixing that driver is a lot of work. At that point, it might be better to consider to move to linux mainline.

The upcoming version v2 has an entirely rewritten imxv4l2videosrc element that might help. Try again with the v2 branch, or with the next release.
