### ISSUE TITLE
imxvpudec creates artifacts under packet loss where avdec_h264 does not

### ISSUE THREAD

**Issue by rodgerbenham** [Freescale/gstreamer-imx#28]
I am streaming video over WiFi and imxvpudec is causing artifacts to display when there is a temporary disturbance in the signal quality when decoding h264.

I have a file saved of the corruption, my pipeline is:
`gst-launch-1.0 -v filesrc location=video.h264 ! h264parse ! imxvpudec ! imxipuvideosink`

It works great until the streamed video is conditioned to have 1% packet loss.

![screen shot 2015-02-09 at 3 03 47 pm](https://cloud.githubusercontent.com/assets/4905775/6100870/a1fcc3f4-b06c-11e4-8833-f6035604c3ef.png)

From this point on however, imxvpudec causes artifacts to display:
(Apologies for the sore neck, metadata based image rotation is super lame)
![img_0178](https://cloud.githubusercontent.com/assets/4905775/6100904/1d019d5e-b06d-11e4-854a-f6de87831361.JPG)

Where if I change imxvpudec out for avdec_h264, no artifacts display (very slight jerk, but I consider this a win) using the following pipeline:
`gst-launch-1.0 -v filesrc location=video.h264 ! h264parse ! avdec_h264 ! imxipuvideosink`
![img_0181](https://cloud.githubusercontent.com/assets/4905775/6100907/47dda248-b06d-11e4-8aec-86f190654f95.JPG)

I would much prefer to use hardware decoding rather than software however. @dv1 are there any options in the decoder to ignore packets with errors? I have dived into the decoder.c file and haphazardly experimented with the skipFrameMode settings but to no avail.

**Comment by dv1** [comment]
The VPU itself apparently can skip incomplete and/or corrupt frames, but I never tried this out. I will as part of the upcoming. imxvpuapi integration.

**Comment by penzrgb** [comment]
Excellent. Let me know if there's anything I can do to help in the integration.
