### ISSUE TITLE
[USB camera Interface on iMX6Q SBC]

### ISSUE THREAD

**Issue by Ash-S** [Freescale/gstreamer-imx#280]
Hi, I am struggling to interface USB camera to iMX6Q SABRE for video streaming on X11 display or on vlc player. I can see the camera detected as /dev/video*. I tried with this.....
```
gst-launch-1.0   \
  imxg2dcompositor name=c background-color=0x223344 \
      sink_0::xpos=0 sink_0::ypos=90 sink_0::width=160 sink_0::height=110 sink_0::zorder=55 sink_0::fill_color=0xff00ff00 sink_0::alpha=0.39 sink_0::rotation=0 \
      sink_1::xpos=0 sink_1::ypos=20 sink_1::width=620 sink_1::height=380 sink_1::fill_color=0x44441133 ! \
    queue2 ! "video/x-raw, width=800, height=600" ! imxg2dvideosink \
  videotestsrc pattern=0 ! "video/x-raw, framerate=30/1" ! c.sink_0 \
  videotestsrc pattern=18 ! "video/x-raw, framerate=30/1" ! c.sink_1
```
it shows me......
 
![image](https://user-images.githubusercontent.com/11657541/98204812-17298400-1f7a-11eb-997a-b30d4c87e10d.png)

but nothing happen. no display window open. 

Please help. Thanks.

**Comment by dv1** [comment]
imxg2dvideosink does not open an X11 window. It paints directly to the framebuffer. On X11, use glimagesink or imxeglvivsink (the latter is gone in the upcoming v2 version though). Try again with one of those, or perhaps try your command line again when X11 is not running. If problems persist, feel free to reopen this issue.
