### ISSUE TITLE
imxg2dallocator could not allocate 115200 bytes of physical memory

### ISSUE THREAD

**Issue by davidlawson** [Freescale/gstreamer-imx#29]
I'm currently trying the following pipeline:

`gst-launch-1.0 videotestsrc ! imxg2dvideosink`

And I'm using Igor Pečovnik's Cubox-i Debian image.

```
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
g2d_alloc: alloc memory fail with size 115200!
0:00:00.074134969 27620  0x12a7150 ERROR        imxg2dallocator ../src/g2d/allocator.c:59:gst_imx_g2d_alloc_phys_mem:<imxg2dallocator0> could not allocate 115200 bytes of physical memory
0:00:00.074684332 27620  0x12a7150 ERROR   imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:205:gst_imx_phys_mem_buffer_pool_alloc_buffer:<imxphysmembufferpool0> could not allocate 115200 bytes for new buffer
0:00:00.075120355 27620  0x12a7150 ERROR         imxbaseblitter ../src/common/base_blitter.c:202:gst_imx_base_blitter_set_input_buffer:<imxg2dblitter0> error acquiring input frame buffer: unknown
ERROR: from element /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0: Internal data flow error.
Additional debug info:
gstbasesrc.c(2943): gst_base_src_loop (): /GstPipeline:pipeline0/GstVideoTestSrc:videotestsrc0:
streaming task paused, reason error (-5)
ERROR: pipeline doesn't want to preroll.
Setting pipeline to NULL ...
Freeing pipeline ...
```

Any ideas? I've tried recompiling the kernel, modifying the Vivante driver and increasing registerMemSize2D and registerMemSizeVG but that didn't help.

I also tried the `imxpxpvideosink` and got the error `could not open /dev/pxp_device: No such file or directory`. The `imxipuvideosink` works fine.

**Comment by dv1** [comment]
What is the status here? I was never able to reproduce this problem. Did you see this with other rootfs like Yocto Fido or Archlinuxarm?

**Comment by Gnate** [comment]
I get this same issue using Archlinuxarm.

**Comment by dv1** [comment]
Do you get it every time? I have seen it a few times now, but it is very elusive here.

**Comment by linux4kix** [comment]
None of the information provided is very meaningful.  Failing to allocate memory can be attributed to plenty of problems.  Please post full dmesg, preferably with a kernel that has CONFIG_CMA_DEBUG enabled.

All these problems are from distributions that have backported newer LTS kernel releases onto my 3.14.14 kernel.  So my guess is that the distributions have broken something with the memory allocations and this is not a gstreamer-imx bug.  If the users seeing this problem can't test with a known bug free kernel then this should be pushed back to the distros.

I have verified that gstreamer-imx works as it should on all SR hardware for both the linux-imx6-3.14 release, as well as the new linux-fsl kernel trees with the default configurations.  If this is other iMX6 hardware then I can't comment.

**Comment by dv1** [comment]
Yes, I can confirm that it never happened on SolidRun hardware. It did happen on other iMX6 devices, and I also doubt it is gstreamer-imx specific. I just don't see anything in the code that could cause this. Perhaps I am missing a subtle error though, which is why I need more information, just as linux4kix mentioned (kernel version, i.MX6 device type, dmesg output, preferably with CONFIG_CMA_DEBUG enabled).

**Comment by dv1** [comment]
Due to inactivity here, and the fact that repeated attempts still did not replicate this issue reliably (and everything indicates this to be a kernel issue), I'm closing it now.

**Comment by DuBistKomisch** [comment]
Just as a follow up, this was definitely a kernel issue. We're now using a SolidRun linux-fsl kernel and it works fine.
