### ISSUE TITLE
[gst 1.16]  gst-discoverer-1.0 not working properly with some mkv contents on imx8 / imx8x platforms

### ISSUE THREAD

**Issue by pga-avionics** [Freescale/gstreamer-imx#291]
On my apalis imx8 and colibri imx8x, gst-discoverer-1.0 does not work with some MKV contents whereas it works on Windows and Linux boxes (debian, ubuntu...).
Same gstreamer version: 1.16.3

`gst-discoverer-1.0 http://fmr-dev.net/tmp/the_100.mkv`

At first glance, the problem doesn't come from gst-discoverer itself, but rather from the underlying uridecodebin element.

Please find attached the expected output (from a working Windows platform) and the output from the apalis, which is wrong.

Please note that there's no network constraints, no fw, no proxy...

[apalis_output_nok.txt](https://github.com/Freescale/gstreamer-imx/files/6716793/apalis_output_nok.txt)
[windows_output_ok.txt](https://github.com/Freescale/gstreamer-imx/files/6716794/windows_output_ok.txt)

**Comment by dv1** [comment]
This is most likely not a gstreamer-imx problem. You are using the imx-gst1.0-plugin package (the "AIUR" log lines indicate as much, since aiur is the demuxer in that package). Uninstall imx-gst1.0-plugin and try again if the discoverer works.

**Comment by dv1** [comment]
Closing this since it very likely is not a gstreamer-imx problem. Reopen this if necessary.
