### ISSUE TITLE
memory allocation error for 8 sdtv encoding pipelines, increasing coherent_pool does not help

### ISSUE THREAD

**Issue by FrankBau** [Freescale/gstreamer-imx#30]
Hi, 
I use a nitrogen_max board with yocto build image (fsl-community-bsp, current master, 3.10.31 kernel) with an 8-channel PCIe frame grabber (v4l2src using videobuf2) and tried to record 8 streams:

<pre>
for i in `seq 0 7`;
do
  gst-launch-1.0 v4l2src device=/dev/video$i num_buffers=1000 ! 'video/x-raw, width=720, height=576' ! imxipuvideotransform ! imxvpuenc_h264 bitrate=2000 ! filesink location=$i.h264 &
  msleep 500
done
</pre>

Two of eight pipelines failed because of memory allocation errors: 
<pre>
[ERR]	mem allocation failed!
0:00:01.105497000   937   0x93a200 WARN     imxphysmemallocator ../src/common/phys_mem_allocator.c:154:gst_imx_phys_mem_allocator_alloc:<imxvpuencallocator0> could not allocate memory block with 725761 bytes
</pre>

From gstreamer 0.10 I knew that setting `coherent_pool=128M` on the Linux cmdline helped out (default is 32M). But, for gstreamer 1.0, not a single pipeline could be created due to memory allocation error after increasing the coherent pool size:

<pre>
0:00:01.158983666   639  0x1eca090 ERROR        imxipuallocator ../src/ipu/allocator.c:66:gst_imx_ipu_alloc_phys_mem:<imxipuallocator0> could not allocate 622080 bytes of physical memory: Cannot allocate memory
0:00:01.159278666   639  0x1eca090 WARN     imxphysmemallocator ../src/common/phys_mem_allocator.c:154:gst_imx_phys_mem_allocator_alloc:<imxipuallocator0> could not allocate memory block with 622080 bytes
0:00:01.159470000   639  0x1eca090 ERROR   imxphysmembufferpool ../src/common/phys_mem_buffer_pool.c:211:gst_imx_phys_mem_buffer_pool_alloc_buffer:<imxphysmembufferpool0> could not allocate 622080 bytes for new buffer
0:00:01.159701333   639  0x1eca090 WARN              bufferpool /home/frank/nitrogen6_max/master_20150218/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0/1.4.5-r0/gstreamer-1.4.5/gst/gstbufferpool.c:302:do_alloc_buffer:<imxphysmembufferpool0> alloc function failed
</pre>

To nail this down, I simplified the pipline by using `videotestsrc` instead of the hardware grabber: 
<pre>
gst-launch-1.0 videotestsrc ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideotransform ! imxvpuenc_h264 bitrate=2000 ! filesink location=x.h264
</pre>

With default coherent pool size this work, but with increased coherent pool size I got:
<pre>
[ERR]   mem allocation failed!
[ERR]   Unable to obtain physical mem
0:00:00.148766000   607   0x16a150 ERROR          imxvpubaseenc ../src/vpu/encoder/base_enc.c:534:gst_imx_vpu_base_enc_set_format:<imxvpuh264enc0> opening new VPU handle failed: failure
</pre>

What are the recommended methods to set/increse the available memory and to avoid those errors ?

Frank

**Comment by sasamy** [comment]
Hi Frank,
![screenshot from 2015-02-13 11 24 27](https://cloud.githubusercontent.com/assets/309884/6336056/f96b6650-bbb0-11e4-9875-fa840e3b2891.jpg)

even if you are able to allocate enough memory, there are limitations VPU

**Comment by dv1** [comment]
@sasamy, while that is true, the errors are about memory allocation failures. It is possible the 0.10 plugins are not using the IPU allocator, but the VPU one instead (even though both shouldn't be more than just frontends for the coherent memory allocation calls..). Perhaps this makes a difference. Also, @FrankBau, you got 8 videotestsrc pipelines to work with the default pool size? Did I read this correctly?

**Comment by linux4kix** [comment]
If you clock the VPU to 352mhz it will be able to handle 8 streams.  To fix the memory allocation errors, remove your coherent_pool line and instead do cma=256M

**Comment by xkentr** [comment]
I ran into this issue when running a large encode pipeline with gstreamer 0.10 (2x720p, 2x360p). The CMA allocator wastes large amounts of memory due to the way it aligns the allocations. You can change this behavior by reducing CONFIG_CMA_ALIGNMENT (and possibly break something else...). I have not tried the same pipeline with the 1.0 plugins yet, but I'll let you know how it goes.

I think the coherent_pool advice is out of date, it didn't help me at all (3.10.17 kernel).

**Comment by FrankBau** [comment]
Yes, for gstreamer 0.10 the following 8 pipelines work (kernel 3.10.17, VPU 352 MHz):
<pre>
for i in `seq 0 7`;
do
    gst-launch v4l2src device=/dev/video$i ! 'video/x-raw-yuv, format=(fourcc)UYVY, width=720, height=576' ! mfw_ipucsc ! vpuenc codec=avc ! filesink location=$i.h264 &
done
</pre>
But, I got DMA errors from the PCIe device which I hope to circumvent with gstreamer 1.0 and a videobuf2 driver.

**Comment by FrankBau** [comment]
@linux4kix: with yocto master (kernel 3.10.31) I have removed coherent_pool and checked:
<pre>
# dmesg | grep cma
cma: CMA: reserved 256 MiB at 26000000
</pre>
but the last 2 of 8 pipelines are failing with mem alloc error as described above in the original posting.

@dv1: no, not 8 videotestsrc pipelines are running.
Same image as above, no coherent pool, 256 MiB cma,  yocto master, kernel 3.10.31:
<pre>
for i in `seq 0 7`;
do
  gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideotransform ! imxvpuenc_h264 bitrate=2000 ! filesink location=$i.h264 &
done
</pre>
6 pipelines are running, the other two show 2040000.vpu: Physical memory allocation error!
The point was that increasing coherent_pool had worsen the situation. But now I understood that coherent_pool is no longer needed.

**Comment by linux4kix** [comment]
@FrankBau If you have a chance can you enable CONFIG_CMA_DEBUG in your kernel config and then post your output of dmesg both with cma=256M and cma=384M?  I am interested in seeing how the allocations are being done.

**Comment by FrankBau** [comment]
With CONFIG_CMA_DEBUG (yocto dizzy kernel 3.10.17):
<pre>
# gst-launch-1.0 videotestsrc num_buffers=100 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideotransform ! imxvpuenc_h264 bitrate=2000 ! filesink location=/dev/null
</pre>

<pre>
# dmesg | grep cma
...
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 4, align 2)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 124, align 7)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 385, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 152, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 203, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 148, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 178, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 178, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 178, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 178, align 8)
cma: dma_alloc_from_contiguous(cma c5eb4a80, count 178, align 8)
</pre>
All, but the "align 7" block are released when the pipeline exits ! ?
When the same pipeline is executed repeatedly, no more "align 7" allocs occur.

The PCIe live recodring pipeline
<pre>
# gst-launch-1.0  v4l2src device=/dev/video8 num_buffers=100 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideotransform ! imxvpuenc_h264 bitrate=2000 ! filesink location=/dev/null 
</pre>
shows exactly the alloc/release pattern.
Starting the same pipeline k times shows k times that pattern.
 
Frank

**Comment by FrankBau** [comment]
Well, thanks for your support. `cma=<a huge value>M` did the trick for me. Frank
