### ISSUE TITLE
mp3_enc_interface.h doesn't exist in 0.13.x tag

### ISSUE THREAD

**Issue by nlbutts** [Freescale/gstreamer-imx#301]
I'm trying to build this software via meta-freescale in Yocto. But I get the following compiler error:

../git/src/audio/mp3_encoder.h:26:10: fatal error: mp3_enc_interface.h: No such file or directory
   26 | #include <mp3_enc_interface.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.

mp3_enc_interface.h doesn't exist in this repo. It doesn't appear to exist in any GStreamer repo/plugin either.

**Comment by dv1** [comment]
What Yocto version was this? And does gstreamer-imx 2.x work?

**Comment by dv1** [comment]
I tried a build with gstreamer 2.x, latest git master, and Yocto git master. Worked fine. Closing this. If there are still problems even with 2.x for you, please reopen.
