### ISSUE TITLE
Encoder hang when used with tee 

### ISSUE THREAD

**Issue by feelwa17** [Freescale/gstreamer-imx#306]
gst-inspect-1.0 version 1.20.1
GStreamer 1.20.1

The same issue still happened. 
The issue has been happening since five years ago

**Comment by dv1** [comment]
What gstreamer-imx version is this? 2.0.0?

**Comment by dv1** [comment]
As said in https://github.com/Freescale/gstreamer-imx/issues/223 , I cannot reproduce this. It may have been fixed by other commits. If it happens to you, and you can provide more details (logs in particular), please reopen.
