### ISSUE TITLE
imxipuvideosink output-rotation issue

### ISSUE THREAD

**Issue by FrankBau** [Freescale/gstreamer-imx#31]
I run 4 pipelines as follows:
<pre>
gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink window-y-coord=360  window-x-coord=640 window-width=352 window-height=288 output-rotation=0
gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink window-y-coord=360  window-x-coord=640 window-width=288 window-height=352 output-rotation=4
gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink window-y-coord=360  window-x-coord=640 window-width=288 window-height=352 output-rotation=7
gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink window-y-coord=360  window-x-coord=640 window-width=352 window-height=288 output-rotation=0
</pre>

The expected behaviour is that I see the color bar test pattern in different orientations:
(0): none
(4): rotate-90cw
(7): rotate-90ccw
(0): none
I see the color bar test pattern, but in the two rotated cases, the test pattern does not fill the given screen area,  but looks like compressed to a squared image within the given screen area with black top+bottom bars.
(gstreamer 0.10.1 yocto dizzy, 3.10.17 kernel, 1280x720-60 HDMI Monitor)
Kind regards

Frank

**Comment by dv1** [comment]
So you are saying that width and height should also be swapped in the 90cw/90ccw cases (if force-aspect is set to TRUE), right? I agree, and will add this. Thanks for reporting.

**Comment by FrankBau** [comment]
No, it looks more like a squared image with top+bottom black bars with the correct window. So as if one variable (width/height) might be used twice or clipped. Can you reproduce my pipelines above ?
Frank

**Comment by dv1** [comment]
I think I see what's the underlying problem: aspect ratio is not preserved in rotations. Run these pipelines for exampl:

gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=1280, height=480' ! imxg2dvideosink output-rotation=0
gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=1280, height=480' ! imxg2dvideosink output-rotation=3

Here, I use the G2D videosink, not the IPU one, but both use the same base code.
I'll fix this by respecting the aspect ratio during rotations in the base blitter video sink code.

**Comment by dv1** [comment]
I added a fix for this. Please check if this corrects it for you.

**Comment by FrankBau** [comment]
Yes, all 8 cases work, thanks a lot.
Here are my pipelines for testing:

<pre>
for i in `seq 0 3`
do
  gst-launch-1.0 videotestsrc num_buffers=1 pattern=green ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink 
  gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink window-y-coord=360 window-x-coord=640 window-width=352 window-height=288 output-rotation=$i
done
for i in `seq 4 7`
do
  gst-launch-1.0 videotestsrc num_buffers=1 pattern=green ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink 
  gst-launch-1.0 videotestsrc num_buffers=250 ! 'video/x-raw, format=UYVY, width=720, height=576' ! imxipuvideosink window-y-coord=360 window-x-coord=640 window-width=288 window-height=352 output-rotation=$i
done
</pre>
