### ISSUE TITLE
Multiple imxipuvideotransform instances with deinterlace-mode

### ISSUE THREAD

**Issue by angelobt** [Freescale/gstreamer-imx#32]
Hello,

I'm trying to create a pipeline with gstreamer-imx version 0.10.1.

My hardware is iMX6solo.

I've a problem with imxipuvideotransform.

My application needs to have different video resolutions, so I have to use imxipuvideotransform many times.

If I use the element without deinterlace-mode, all is working fine. Instead using the deinterlacer I get these errors:

imx-ipuv3 2400000.ipu: ERR:[0x86440c00]-no:0x110 "wait_for_comp_timeout" ret:0,l
ine:2941
imx-ipuv3 2400000.ipu: ERR:[0x86440c00]-no:0x130 "wait_for_comp_timeout" ret:0,l
ine:2941
imx-ipuv3 2400000.ipu: ERR:[0x86440c00]-no:0x190 "wait_for_comp_timeout" ret:0,l
ine:2941

and I have to reboot my board.

Here are my pipelines:
###### 

not working
###### 

gst-launch-1.0 imxv4l2src fps-n=25 ! 'video/x-raw, width=720, height=576, format=I420, framerate=25/1' ! queue ! imxipuvideotransform deinterlace-mode=2 ! 'video/x-raw, width=720, height=576, format=I420' ! tee name=t t. ! imxipuvideosink force-aspect-ratio=false window-width=800 window-height=480 t. ! queue ! imxipuvideotransform ! 'video/x-raw, width=800, height=480, format=I420' ! queue !  imxvpuenc_h264 bitrate=1000 idr-interval=30 ! queue ! avimux name=mux ! filesink location=/home/root/test1.avi async=false t. ! queue ! imxipuvideotransform ! 'video/x-raw, width=320, height=240, format=I420' ! fakesink async=false
###### 

working
###### 

gst-launch-1.0 imxv4l2src fps-n=25 ! 'video/x-raw, width=720, height=576, format=I420, framerate=25/1' ! queue ! imxipuvideotransform  ! 'video/x-raw, width=720, height=576, format=I420' ! tee name=t t. ! imxipuvideosink force-aspect-ratio=false window-width=800 window-height=480 t. ! queue ! imxipuvideotransform ! 'video/x-raw, width=800, height=480, format=I420' ! queue !  imxvpuenc_h264 bitrate=1000 idr-interval=30 ! queue ! avimux name=mux ! filesink location=/home/root/test1.avi async=false t. ! queue ! imxipuvideotransform ! 'video/x-raw, width=320, height=240, format=I420' ! fakesink async=false

Is it possible to use more instances of imxipuvideotransform ?

Is there a way to avoid this issue ?

thanks

**Comment by dv1** [comment]
The i.MX6 reference manual states that "VDIC supports a single video stream at any given time". The question is whether or not this is handled by the driver properly.

Does this error also happen to you in simpler pipelines without tee elements (that is, without branching)?

**Comment by angelobt** [comment]
If I use a simpler pipeline like

gst-launch-1.0 imxv4l2src fps-n=25 ! 'video/x-raw, width=720, height=576, format=I420, framerate=25/1' ! queue ! imxipuvideotransform deinterlace-mode=2 ! 'video/x-raw, width=720, height=576, format=I420, framerate=25/1' ! queue ! imxipuvideotransform ! 'video/x-raw, width=800, height=480, format=I420'  !  imxvpuenc_h264 bitrate=2000 idr-interval=25 ! rtph264pay ! multiudpsink clients=192.168.1.2:5001,192.168.1.2:5002,192.168.1.2:5003

I have no IPU errors.

So do you think is something related to tee element ?

**Comment by angelobt** [comment]
I have done further tests:

seems that queue element causes the problem:
if I put a queue at the beginning of a tee branch and queue "separates" two IPU elements, I get 

mx-ipuv3 2400000.ipu: ERR:[0x86440c00]-no:0x110 "wait_for_comp_timeout" ret:0,line:2941

Do you know the reason why this issue happens ?

**Comment by dv1** [comment]
I have one suspicion. Keep in mind that a queue spawns a new thread. Downstream then runs in a different thread than upstream. Without queues though, all elements will process data sequentially. So perhaps you are triggering a race condition in the driver.

**Comment by charlesu** [comment]
Has anyone done more investigation on this? I am having a similar issue here and I would like to know whether there is a driver patch available.

**Comment by dv1** [comment]
What's your hardware, kernel version, Linux distribution, and GStreamer pipeline?

**Comment by charlesu** [comment]
We are using imx6q running Linux kernel 3.14.52-1.1.0_ga distributed by Freescale. We are not using gstreamer but with code that submits different ipu tasks to the IPU module. To test this, we have an app that simply submits ipu task in a loop and the task can be vdi or csc task or both at the same time. Base on out test, I can have as many instances of the app opened if it only involves calling non vdi tasks. But if I have a mix of both, that is some apps do vdi tasks and some apps do ipu csc tasks, than I will get the timeout issue once I have three instances of apps going.
