### ISSUE TITLE
imxipuvideotransform color convert not work

### ISSUE THREAD

**Issue by poucz** [Freescale/gstreamer-imx#33]
Hello,
i want uset imxipuvideotransform to convert yuv to rgb. 
I try it with:

    filesrc location=video.mp4 !qtdemux !h264parse ! imxvpudec !  imxipuvideotransform!video/x-raw,width=400,height=240,format=RGB ! appsink name=video_sink

But when i get sample it's totaly black!
So i try remove color convertor:

    filesrc location=video.mp4 !qtdemux !h264parse ! imxvpudec !  imxipuvideotransform!appsink name=video_sink

Now I receive some not black data.
So I think it's some issue....

**Comment by dv1** [comment]
On 03/11/2015 02:36 PM, poucz wrote:
>
> Hello,
> i want uset imxipuvideotransform to convert yuv to rgb.
> I try it with:
>
> |filesrc location=video.mp4 !qtdemux !h264parse ! imxvpudec !  imxipuvideotransform!video/x-raw,width=400,height=240,format=RGB ! appsink name=video_sink
> |
>
> But when i get sample it's totaly black!
> So i try remove color convertor:
>
> |filesrc location=video.mp4 !qtdemux !h264parse ! imxvpudec !  imxipuvideotransform!appsink name=video_sink
> |
>
> Now I receive some not black data.
> So I think it's some issue....
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Freescale/gstreamer-imx/issues/33>.
>

Check if you get an error in the logs. Run the pipeline with the 
GST_DEBUG enviroment variable set to "*imx*:2" .
The IPU is unfortunately somewhat picky with regards to frame sizes.

**Comment by poucz** [comment]
I was check, but without error, only some warning when a used GST_DEBUG=2:

[INFO]	Product Info: i.MX6Q/D/S
0:00:01.753053667  1514  0x1611780 WARN                 basesrc /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0/1.4.1-r0/gstreamer-1.4.1/libs/gst/base/gstbasesrc.c:3460:gst_base_src_start_complete:<filesrc0> pad not activated yet
D- void Player_core::Play() 	 Hrani zkonceno
0:00:01.755395667  1514  0x160a060 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type iods
0:00:01.755964667  1514  0x160a060 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type uuid
0:00:01.756503667  1514  0x160a060 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type �TIM
0:00:01.756965667  1514  0x160a060 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type �TSC
0:00:01.757363334  1514  0x160a060 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type �TSZ
0:00:01.758695000  1514  0x160a060 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux.c:8243:qtdemux_parse_trak:<qtdemux0> unknown version 00000000
D- void Player_core::Refresh() 	 refresh
D- void Player_core::Refresh() 	 Waiting for sample....
[INFO]	bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
[WARN]	VPU iram is less than needed, some parts don't use iram

**Comment by dv1** [comment]
What do you see with RGBA or RGBx?

**Comment by poucz** [comment]
Hi,
thank for reply.
It's still return black sample (when i tried RGBA, RGBx).
So I also try build pipeline in CMD, with same result (black screen). Output is bellow

```
root@wandboard-dual:~# gst-launch-1.0 filesrc location=/home/root/rbsp_launch_480p.mp4 ! qtdemux ! h264parse ! imxvpudec ! imxipuvideotransform ! "video/x-raw, width=400, height=240, format=RGB" ! videoconvert dither=0 ! imxeglvivsink
Setting pipeline to PAUSED ...
[INFO]	Product Info: i.MX6Q/D/S
0:00:00.247200333   559   0x7119a0 WARN                 basesrc /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0/1.4.1-r0/gstreamer-1.4.1/libs/gst/base/gstbasesrc.c:3460:gst_base_src_start_complete:<filesrc0> pad not activated yet
Pipeline is PREROLLING ...
0:00:00.249150667   559   0x72e920 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type iods
0:00:00.249773000   559   0x72e920 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type uuid
0:00:00.250268000   559   0x72e920 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type �TIM
0:00:00.250720333   559   0x72e920 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type �TSC
0:00:00.251164667   559   0x72e920 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux_types.c:200:qtdemux_type_get: unknown QuickTime node type �TSZ
0:00:00.252477333   559   0x72e920 WARN                 qtdemux /home/pou/f/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0-plugins-good/1.4.1-r0/gst-plugins-good-1.4.1/gst/isomp4/qtdemux.c:8243:qtdemux_parse_trak:<qtdemux0> unknown version 00000000
[INFO]	bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
[WARN]	VPU iram is less than needed, some parts don't use iram
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock

```

**Comment by dv1** [comment]
I tried this pipeline on a nitrogen6x, and it shows output. Please re-check if this still happens with the latest release. Also set the GST_DEBUG environment variable to 2,*imx*:9 please, to get more log output.

**Comment by dv1** [comment]
Due to inactivity here, and the fact that repeated attempts still did not replicate this issue, I'm closing it now. Feel free to reopen it if it occurs again.
