### ISSUE TITLE
videosink with overlay not working as expected

### ISSUE THREAD

**Issue by FrankBau** [Freescale/gstreamer-imx#35]
I'm using yocto dizzy with kernel 3.10.17 and framebuffer output (no X11, no wayland) on a HDMI monitor.
The goal is to render some output to /dev/fb0 and other output to /dev/fb1 and let the IPU do global alpha blending.  

I my scenario, fb0 is rendered by a Qt5 app, say `Qt5_CinematicExperience -platform eglfs &`
This works, I see the animation and can check by repeated `md5sum /dev/fb0` that fb0 is constantly updated.

When I now issue `gst-launch videotestsrc ! mfw_isink disp-width=320 disp-height=240` I see the color bar pattern overlay as expected on top of the Qt5 animation. So far so good.

But, I want to use the newer gstreamer-1.0 plugins and failed with the following pipeline:
<pre>
gst-launch-1.0 videotestsrc ! imxipuvideosink sync=false window-width=320 window-x-coord=100 window-y-coord=100 window-height=240 framebuffer=/dev/fb1
</pre>

I can verify with `md5sum /dev/fb1` that the framebuffer is constantly updated, but I don't see the overlay on the screen. Same when I use `imxg2dvideosink` instead of `imxipuvideosink`.  
Any help is highly appreciated.

PS: For testing, the Qt app might be replaced by something simpler like `cat  /dev/urandom > /dev/fb0` showing identical behaviour.

**Comment by otavio** [comment]
While I understand why you might be intending to do this, we have been using QtMultimedia for playing video and doing the "UI" overlay in QML. This has been working fine for our use cases.

**Comment by FrankBau** [comment]
Hi Otavio,
thanks for your suggestion. My use case is a multi-channel hybrid DVR/NVR and gstreamer 1.0 looks very promising for building the flexible copy-free pipelines we need for this.
Frank

**Comment by FrankBau** [comment]
Overlay and alpha blending can be done on top of gstreamer, so there is no need to include it here. (as it was done in mfw_isink in gstreamer 0.10)
I created a working example rendering a video to /dev/fb1 using a pipeline
gst-launch-1.0 filesrc location=big_buck_bunny_1080p_h264.mp4 ! qtdemux ! h264parse ! imxvpudec ! imxipuvideosink framebuffer=/dev/fb1
with an Qt 5.4 qml GUI overlay on /dev/fb0 using some (semi-)transparent GUI elements and background.
So I close this issue.
Frank

**Comment by rosciio** [comment]
Hi
I have the same problem but on 3.14.
I'm using this pipeline: 
gst-launch-1.0 videotestsrc ! imxipuvideosink sync=false window-width=320 window-x-coord=100 window-y-coord=100 window-height=240 framebuffer=/dev/fb1

and on Qtquick 2.5 I set opacity=0.5 and background color=#000000

I can't see the video on fb1, so the overlay doesn't work.

Anyone have idea?
thanks
Marco from italy

**Comment by rosciio** [comment]
Hi,
the solution is in this thread
https://community.freescale.com/thread/376331

thanks
Marco

**Comment by dv1** [comment]
Thanks, I'll see if I can add this to the FAQ section.
