### ISSUE TITLE
Audio issue: pipeline with imxv4l2src and alsasrc elements

### ISSUE THREAD

**Issue by angelobt** [Freescale/gstreamer-imx#36]
Hello,

I have this pipeline that grabs audio and video and send audio through udp:

gst-launch-1.0 imxv4l2src fps-n=25 ! 'video/x-raw, width=720, height=576, format=I420, framerate=25/1' !  fakesink  alsasrc provide-clock=false ! mulawenc ! rtppcmupay ! udpsink host=10.39.65.21 port=5006 

audio is very bad

If I use videotestsrc instead of imxv4l2src all is working fine

gst-launch-1.0 videotestsrc ! 'video/x-raw, width=720, height=576, format=I420, framerate=25/1' ! fakesink  alsasrc provide-clock=false ! mulawenc ! rtppcmupay ! udpsink host=10.39.65.21 port=5006

Anyone know the reason ?

I have an iMX6Solo board.

Thanks in advance

**Comment by dv1** [comment]
Both sources are live sources. This might be the problem. Try putting a queue before each sink.

**Comment by dv1** [comment]
@angelobt What's the state of this?

**Comment by angelobt** [comment]
It was an hardware issue.
