### ISSUE TITLE
1920x1080 slow-motion deinterlacing doesn't work

### ISSUE THREAD

**Issue by behlingc** [Freescale/gstreamer-imx#38]
Pipeline:
gst-launch-1.0 filesrc location=/vertrezmotion.ts ! tsdemux ! mpegvideoparse ! imxvpudec  ! imxipuvideotransform deinterlace-mode=1 ! imxg2dvideosink

Test video:
http://www.w6rz.net/vertrezmotion.zip

Kernel: 3.10.53

Error kernel hangs after:

...
Setting pipeline to PAUSED ...
[INFO]  Product Info: i.MX6Q/D/S
Pipeline is PREROLLING ...
[INFO]  bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_10 = 0x40000000
imx-ipuv3 2800000.ipu: IPU Warning - IPU_INT_STAT_10 = 0x40000000
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_10 = 0x40000000
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_10
...

See also my Freescale community thread:
https://community.freescale.com/message/515310#515310

**Comment by dv1** [comment]
I do see something wrong with the slow-deinterlace mode. I am reworking the IPU stack as part of a general improvement, and will look into this as well.

**Comment by behlingc** [comment]
Thanks for the answer. Can you provide some details?

**Comment by dv1** [comment]
One big problem with IPU deinterlacing (and with the IPU in general) is the severe lack of documentation about the driver and its ioctls. Parts of the driver code are amazingly confusing and complex, which doesn't help. I appreciate the investigations you've made. I strongly suspect the IPU elements are currently using the deinterlacer incorrectly. I'm working as fast as I can on the reworks. I'll know more then.

**Comment by dv1** [comment]
I am about to finally push the newer blitter stuff. I did several experiments, but just cannot make sense of the slow deinterlacing mode. For this reason, I kicked it out for now. It seriously complicates the IPU blitter logic, with little noticeable gain. Did you find large gains of slow-mode over fast-mode?

**Comment by dv1** [comment]
In the new release, I don't support the slow mode anymore, due to it having numerous problems with questionable gains. If needed, I'll add it back again, but only if a significant benefit is demonstrated (it apparently requires both the current and the last video frame to work, which complicates the internal logic in the gstreamer-imx blitter code). I am considering to try out the medium mode though.
