### ISSUE TITLE
imxvpuenc_h264 is not compatible with mp4mux.

### ISSUE THREAD

**Issue by angolini** [Freescale/gstreamer-imx#39]
gst-launch-1.0 videotestsrc num-buffers=1 ! imxvpuenc_h264 ! mp4mux ! filesink location=i.mp4
WARNING: erroneous pipeline: could not link imxvpuh264enc0 to mp4mux0

This is because in 1.0, imxvpuenc_h264 is not compatible with mp4mux.
 
imxvpuenc_h264 pad template:
  SRC template: 'src'
    Availability: Always
    Capabilities:
      video/x-h264
        **stream-format: byte-stream**
              alignment: { au, nal }
 

mp4mux sink pad template:
  	video/x-h264
      	**stream-format: avc**
          	alignment: au
              	width: [ 16, 4096 ]
             	height: [ 16, 4096 ]

Can you, please, advice?

**Comment by mgroftisza** [comment]
I will eventually have a need for the exact same imxvpuenc_h264 ! mp4mux in my pipline, but haven't tried it yet.  I suspect that you might be ale to get away with sticking h264parse in between them.  Try:
imxvpuenc_h264 ! h264parse ! mp4mux.

**Comment by dv1** [comment]
Yes, I agree. In fact, I use h264parse all the time with imxvpudec. It makes little sense to duplicate the byte-stream -> avcc conversion. Just use the already existing conversion in h264parse.
(This is also why in the latest Yocto gstreamer-imx recipe, h264parse is marked as a RRECOMMENDS dependency.)

**Comment by angolini** [comment]
Thanks @mgroftisza and @dv1  for the suggestion.

Please, fell free to close this issue. I would only like to be notified if this feature (stream-format=avc) is implemented in future.

Thanks a lot,
Daiane
