### ISSUE TITLE
imxipuvideosink video tearing

### ISSUE THREAD

**Issue by msmithatcarmanahsigns** [Freescale/gstreamer-imx#40]
I'm using kernel 3.14.28 and imxipuvideosink to play video.  It works ok, but there is very noticeable screen tearing.

Is there a fix for this?

Thanks

Marlon

**Comment by dv1** [comment]
I am reworking the blitter-based sinks and transform elements for more complex composite and vsync output. This will be the fix.

**Comment by msmithatcarmanahsigns** [comment]
Thanks very much!  Is there any kind of patch or quick fix I could apply by myself in the meantime?

**Comment by dv1** [comment]
Unfortunately no. The fix involves the use of framebuffer panning. The virtual framebuffer height is 3x larger than the physical one in most, if not all i.MX6 devices. The idea then is to implement page flipping by alternatively panning from y position 0 to y position (fixed_height) and back. Tests seem to indicate that panning implicitely uses vsync. I'm doing this as fast as I can, since I was busy with other stuff in the last few months, and need to catch up. The result will address and hopefully fix several issues, not just this one.

**Comment by msmithatcarmanahsigns** [comment]
Ok.  Thanks for the quick response!  I'll keep an eye on this repo for the update!

**Comment by angelobt** [comment]
Hi, any news ?

**Comment by dv1** [comment]
As part of a new compositor feature, I had to refactor the blitter infrastructure. During this, I noticed that it seems to be possible to achieve vsync by using page flipping. imx kernels allocate a virtual framebuffer height that is 3 times the physical height, so it can even support triple buffering. This is the way to go. I need to finish the new blitter stuff first, then I do that.

**Comment by angelobt** [comment]
Ok. Thanks for the quick response!

**Comment by dv1** [comment]
The G2D, IPU, PxP video sinks in the new release now have vsync support. Use the video sinks with the use-vsync=true property set.

**Comment by angelobt** [comment]
First, thanks for your work.

I have tested new version, but unfortunately I get kernel panic error.

gst-launch-1.0 imxv4l2videosrc fps-n=25 ! 'video/x-raw, width=720, height=576, format=I420, framerate=25/1, interlace-mode=progressive' !  imxipuvideosink force-aspect-ratio=false window-width=800 window-height=480 async=false use-vsync=true

Setting pipeline to PAUSED ...
ERROR: unrecognized std! ffffff (PAL=ff, NTSC=b000
ERROR: unrecognized std! ffffff (PAL=ff, NTSC=b000
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
Unable to handle kernel paging request at virtual address 00394ecd
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
pgd = 9cf4c000
[00394ecd] *pgd=00000000
Internal error: Oops: 5 [#1] PREEMPT SMP ARM
Modules linked in: usb_f_ecm g_ether usb_f_rndis u_ether libcomposite configfs w
l18xx(O) wlcore(O) mac80211(O) cfg80211(O) wlcore_sdio(O) compat(O) evbug
CPU: 0 PID: 560 Comm: BtClass Tainted: G           O 3.14.28 #1
task: 9c2b5f80 ti: 9cf0c000 task.ti: 9cf0c000
PC is at ext4_getattr+0x40/0xa4
LR is at 0x394e9d
pc : [<8015f834>]    lr : [<00394e9d>]    psr: 60030013
sp : 9cf0df08  ip : 00000000  fp : 7ecaae3c
r10: 00000000  r9 : 9cf0c000  r8 : 9cf0df50
r7 : 00000000  r6 : 00000008  r5 : 9cf0df50  r4 : 9a150f88
r3 : 00000000  r2 : 9cf0df50  r1 : 00000000  r0 : 00000000
Flags: nZCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment user
Control: 10c53c7d  Table: 2cf4c059  DAC: 00000015
Process BtClass (pid: 560, stack limit = 0x9cf0c238)
Stack: (0x9cf0df08 to 0x9cf0e000)
df00:                   8015f7f4 00000000 00000001 ffffff9c 74f02a98 9cf0df50
df20: 9cf0c000 00000000 7ecaae3c 800d9144 9cb870d0 9a2e95d8 7ecaadb0 00000000
df40: 74f16000 000000c3 8000e724 800d980c 00000d27 00000000 00707700 800081a4
df60: 00000001 00000000 00000000 00000000 0000007f 00000000 55a77102 0ee6b280
df80: 55a77102 0ee6b280 55a77102 0f7f4900 00001000 00051b28 00000008 00000000
dfa0: 74f02a98 8000e5a0 74f02a98 00000000 74f02a98 7ecaadb0 7ecaadb0 0000002f
dfc0: 74f02a98 00000000 74f16000 000000c3 00000001 00000000 000040f8 7ecaae3c
dfe0: 0169757e 7ecaad54 74e73a08 74ea5df8 20030010 74f02a98 2fff8811 2fff8c11
[<8015f834>] (ext4_getattr) from [<800d9144>] (vfs_fstatat+0x58/0x98)
[<800d9144>] (vfs_fstatat) from [<800d980c>] (SyS_stat64+0x14/0x30)
[<800d980c>] (SyS_stat64) from [<8000e5a0>] (ret_fast_syscall+0x0/0x30)
Code: e3a00000 e594c190 e591e200 e5d1100c (e59ee030)
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_10 = 0x00000001
Unable to handle kernel paging request at virtual address 5a5f007e
pgd = 80004000
[5a5f007e] *pgd=00000000
Internal error: Oops: 5 [#2] PREEMPT SMP ARM
Modules linked in: usb_f_ecm g_ether usb_f_rndis u_ether libcomposite configfs w
l18xx(O) wlcore(O) mac80211(O) cfg80211(O) wlcore_sdio(O) compat(O) evbug
CPU: 0 PID: 38 Comm: cfinteractive Tainted: G      D    O 3.14.28 #1
task: 9c1aad00 ti: 9c1f0000 task.ti: 9c1f0000
PC is at dev_pm_opp_find_freq_ceil+0x38/0xa8
LR is at 0x3b5dc100
pc : [<80340664>]    lr : [<3b5dc100>]    psr: 30030113
sp : 9c1f1ea0  ip : 5a5f0076  fp : 80c90804
r10: 000f32a0  r9 : 00060ae0  r8 : 00000002
r7 : 9c1f1ec4  r6 : 000f32a0  r5 : 3b5dc100  r4 : 9c1f1ec4
r3 : 9c5ac880  r2 : 5a5f0076  r1 : 9fbd8010  r0 : 9ca58bcc
Flags: nzCV  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
Control: 10c53c7d  Table: 2cf4c059  DAC: 00000015
Process cfinteractive (pid: 38, stack limit = 0x9c1f0238)
Stack: (0x9c1f1ea0 to 0x9c1f2000)
1ea0: 9ca59f10 5a5f0076 80d2f510 8045eac4 00000000 80d2f44c 000f32a0 8004bac8
1ec0: 00000000 3b5dc100 00000000 9ca58c00 00000000 80d2f44c 9ca59f10 000f32a0
1ee0: 9c1f1f3c 000f32a0 80c90804 8045838c 9c1f1efc 80c86c80 7ef2cb97 00000002
1f00: 00000004 00060ae0 000f32a0 80649d20 9fbd9030 80c905d0 00000000 80c86030
1f20: 9fbd90b0 8045d72c 9c05feb0 80c86030 9c1f0028 80d2f4e8 9c1da0c0 00000001
1f40: 8045d5b8 00000000 9c1da0c0 00000000 8045d5b8 00000000 00000000 00000000
1f60: 00000000 80047800 0bff7bff 00000000 2fd38e1f 00000000 00000000 00000000
1f80: 9c1f1f80 9c1f1f80 00000000 00000000 9c1f1f90 9c1f1f90 9c1f1fac 9c1da0c0
1fa0: 80047734 00000000 00000000 8000e638 00000000 00000000 00000000 00000000
1fc0: 00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000
1fe0: 00000000 00000000 00000000 00000000 00000013 00000000 f9388f3f cf3fdcf9
[<80340664>] (dev_pm_opp_find_freq_ceil) from [<8045eac4>] (imx6q_set_target+0x6
4/0x48c)
[<8045eac4>] (imx6q_set_target) from [<8045838c>] (__cpufreq_driver_target+0x14c
/0x1c8)
[<8045838c>] (__cpufreq_driver_target) from [<8045d72c>] (cpufreq_interactive_sp
eedchange_task+0x174/0x190)
[<8045d72c>] (cpufreq_interactive_speedchange_task) from [<80047800>] (kthread+0
xcc/0xe4)
[<80047800>] (kthread) from [<8000e638>] (ret_from_fork+0x14/0x3c)
Code: e58d3004 e59d2004 e1520000 0a00000b (e5d2c008)
---[ end trace f73fbbf0eea26c5a ]---
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_10 = 0x00000001
---[ end trace f73fbbf0eea26c5b ]---
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT_STAT_5 = 0x00000001
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:01.309092897
Setting pipeline to PAUSED ...
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...
Unable to handle kernel paging request at virtual address 009b5d44
pgd = 80004000
[00939500] *pgd=00000000
Internal error: Oops: 80000005 [#4] PREEMPT SMP ARM
Modules linked in: usb_f_ecm g_ether usb_f_rndis u_ether libcomposite configfs w
l18xx(O) wlcore(O) mac80211(O) cfg80211(O) wlcore_sdio(O) compat(O) evbug
CPU: 0 PID: 0 Comm: swapper/0 Tainted: G      D    O 3.14.28 #1
task: 80c94368 ti: 80c88000 task.ti: 80c88000
PC is at 0x939500
LR is at call_timer_fn.isra.33+0x24/0x88
pc : [<00939500>]    lr : [<80036ce4>]    psr: 20010113
sp : 80c89e40  ip : 80c89e60  fp : 00939500
r10: 00626700  r9 : 80cd8454  r8 : 00939500
r7 : 00000101  r6 : 80c88000  r5 : 80c89e60  r4 : 80c88000
r3 : 80c89e40  r2 : 00000101  r1 : 00626700  r0 : 00626700
Flags: nzCv  IRQs on  FIQs on  Mode SVC_32  ISA ARM  Segment kernel
Control: 10c53c7d  Table: 2ccb0059  DAC: 00000015
Process swapper/0 (pid: 0, stack limit = 0x80c88238)
Stack: (0x80c89e40 to 0x80c8a000)
9e40: bfb3948c 00000025 80cd7c40 80c89e60 00000000 00200200 80c8a0c0 80036ea8
9e60: 9c091ed4 9c091ed4 bfb3948c 00000000 00000001 80c8a084 80c88000 80c88010
9e80: 00000101 80c8a080 40000001 80030d0c 00000057 9c00a240 80cd58ff 00000000
9ea0: 80c8a080 80c85450 80cd7a00 0000000a 8064d398 ffffca26 80c8a0c0 00200000
9ec0: 9c00a240 80c88028 00000057 00000000 f4a00100 bf1ccb97 00000025 80c88000
9ee0: 00000000 8003109c 80c85e44 8000ee90 f4a0010c 80c90970 80c89f18 80008600
9f00: 00000009 8045fbb8 00010013 ffffffff 80c89f4c 80012340 80c89f60 3b9aca00
9f20: bfb37d1c 00000025 80c96ccc 80c96ccc 9fbd90d0 00000000 bf1ccb97 00000025
9f40: 80c88000 00000000 00000017 80c89f60 00000009 8045fbb8 00010013 ffffffff
9f60: bfb37d1c 00000025 80c9c754 9fbd90d0 80c90574 9fbd90d0 00000000 00000000
9f80: 00000000 80d2f578 80c96ccc 8045fcfc 00000000 80c88000 80c90574 8064d38c
9fa0: 80c88038 80cd58fd 80cd58fd 8000f1bc 00000000 80067038 ffffffff 80c37b10
9fc0: ffffffff ffffffff 80c3758c 00000000 00000000 80c79140 00000000 10c53c7d
9fe0: 80c904fc 80c7913c 80c95400 10004059 412fc09a 10008074 00000000 00000000
[<80036ce4>] (call_timer_fn.isra.33) from [<80036ea8>] (run_timer_softirq+0x160/
0x1e4)
[<80036ea8>] (run_timer_softirq) from [<80030d0c>] (__do_softirq+0x140/0x248)
[<80030d0c>] (__do_softirq) from [<8003109c>] (irq_exit+0xb8/0xf4)
[<8003109c>] (irq_exit) from [<8000ee90>] (handle_IRQ+0x44/0x90)
[<8000ee90>] (handle_IRQ) from [<80008600>] (gic_handle_irq+0x2c/0x5c)
[<80008600>] (gic_handle_irq) from [<80012340>] (__irq_svc+0x40/0x70)
Exception stack(0x80c89f18 to 0x80c89f60)
9f00:                                                       80c89f60 3b9aca00
9f20: bfb37d1c 00000025 80c96ccc 80c96ccc 9fbd90d0 00000000 bf1ccb97 00000025
9f40: 80c88000 00000000 00000017 80c89f60 00000009 8045fbb8 00010013 ffffffff
[<80012340>] (__irq_svc) from [<8045fbb8>] (cpuidle_enter_state+0x54/0xe4)
[<8045fbb8>] (cpuidle_enter_state) from [<8045fcfc>] (cpuidle_idle_call+0xb4/0x1
4c)
[<8045fcfc>] (cpuidle_idle_call) from [<8000f1bc>] (arch_cpu_idle+0x8/0x44)
[<8000f1bc>] (arch_cpu_idle) from [<80067038>] (cpu_startup_entry+0x100/0x14c)
[<80067038>] (cpu_startup_entry) from [<80c37b10>] (start_kernel+0x350/0x35c)
Code: bad PC value
---[ end trace f73fbbf0eea26c5d ]---
Kernel panic - not syncing: Fatal exception in interrupt

**Comment by dv1** [comment]
Strange. Does it work with use-vsync=false ?

**Comment by angelobt** [comment]
yes it works.

I have installed plugins via opkg install --force-reinstall.
I want to recompile and do an other test.

**Comment by angelobt** [comment]
I have tried to recompile, but same result

**Comment by dv1** [comment]
So, if it works with use-vsync=false , then the framebuffer reconfiguration is probably failing somehow. Try running the gst-launch-1.0 line with the environment variable GST_DEBUG=2,*imx*:4,*blitter*:9,*ipu*:9  .

**Comment by angelobt** [comment]
gst-launch-1.0 --gst-debug=*imx*:4,*blitter*:9,*ipu*:9 imxv4l2videosrc fps-n=25 ! 'video/x-raw, width=720, height=576, framerate=25/1' ! imxipuvideosink use-vsync=true 
0:00:00.081346131   439  0x13c08e0 INFO         imxv4l2videosrc v4l2src.c:329:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps filter (NULL)
0:00:00.081829473   439  0x13c08e0 INFO         imxv4l2videosrc v4l2src.c:340:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps video/x-raw, format=(string)I420, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string)progressive, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:00.082658154   439  0x13c08e0 INFO         imxv4l2videosrc v4l2src.c:329:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps filter (NULL)
0:00:00.082969827   439  0x13c08e0 INFO         imxv4l2videosrc v4l2src.c:340:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps video/x-raw, format=(string)I420, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string)progressive, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
0:00:00.083663506   439  0x13c08e0 INFO         imxv4l2videosrc v4l2src.c:329:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps filter (NULL)
0:00:00.083949844   439  0x13c08e0 INFO         imxv4l2videosrc v4l2src.c:340:gst_imx_v4l2src_get_caps:<imxv4l2videosrc0> get caps video/x-raw, format=(string)I420, width=(int)[ 16, 2147483647 ], height=(int)[ 16, 2147483647 ], interlace-mode=(string)progressive, framerate=(fraction)[ 0/1, 100/1 ], pixel-aspect-ratio=(fraction)[ 0/1, 100/1 ]
Setting pipeline to PAUSED ...
0:00:00.086678560   439  0x13c08e0 INFO     imxblittervideosink video_sink.c:851:gst_imx_blitter_video_sink_open_framebuffer_device:<imxipuvideosink0> opening framebuffer /dev/fb0
0:00:00.086995232   439  0x13c08e0 INFO     imxblittervideosink video_sink.c:1102:gst_imx_blitter_video_sink_get_format_from_fb:<imxipuvideosink0> framebuffer uses 32 bpp (sizes: r 8 g 8 b 8  offsets: r 16 g 8 b 0) => format BGRA
0:00:00.087665578   439  0x13c08e0 INFO     imxblittervideosink video_sink.c:906:gst_imx_blitter_video_sink_open_framebuffer_device:<imxipuvideosink0> framebuffer FD is 5
0:00:00.087945916   439  0x13c08e0 INFO     imxblittervideosink video_sink.c:923:gst_imx_blitter_video_sink_open_framebuffer_device:<imxipuvideosink0> framebuffer configuration:  resolution is 800 x 480 , virtual 800 x 480 => need to reconfigure virtual height
0:00:00.088251255   439  0x13c08e0 INFO     imxblittervideosink video_sink.c:1020:gst_imx_blitter_video_sink_reconfigure_fb:<imxipuvideosink0> setting new configuration: original virtual height: 480 new virtual height: 960
0:00:00.161874580   439  0x13c08e0 INFO     imxphysmemallocator phys_mem_allocator.c:62:gst_imx_phys_mem_allocator_init:<GstImxPhysMemAllocator@0x1318110> initializing physical memory allocator
0:00:00.162823931   439  0x13c08e0 INFO            imxipudevice device.c:61:gst_imx_ipu_open: IPU device opened
0:00:00.163478276   439  0x13c08e0 INFO         imxipuallocator allocator.c:169:gst_imx_ipu_allocator_init:<GstImxIpuAllocator@0x1318110> initialized IPU allocator
0:00:00.164542962   439  0x13c08e0 TRACE             imxblitter blitter.c:64:gst_imx_blitter_init:<GstImxBlitter@0x13c6050> initializing blitter base
0:00:00.165406644   439  0x13c08e0 DEBUG        imxipuallocator allocator.c:73:gst_imx_ipu_alloc_phys_mem:<imxipuallocator0> allocated 256 bytes of physical memory at address 0x24ffe000
0:00:00.166091656   439  0x13c08e0 INFO     imxphysmemallocator phys_mem_allocator.c:152:gst_imx_phys_mem_allocator_alloc:<imxipuallocator0> allocated memory block 0x13bb908 at phys addr 0x24ffe000 with 256 bytes
0:00:00.166701667   439  0x13c08e0 DEBUG    imxblittervideosink video_sink.c:599:gst_imx_blitter_video_sink_change_state:<imxipuvideosink0> cleaning up any previous vsync by flipping to page 0
0:00:00.167353679   439  0x13c08e0 LOG      imxblittervideosink video_sink.c:984:gst_imx_blitter_video_sink_select_fb_page:<imxipuvideosink0> switching to page 0
0:00:01.327371559   439  0x13c08e0 INFO         imxv4l2videosrc v4l2src.c:117:gst_imx_v4l2src_capture_setup:<imxv4l2videosrc0> capture mode 0: 720x576
Pipeline is live and does not need PREROLL ...
Setting pipeline to PLAYING ...
New clock: GstSystemClock
0:00:01.335823711   439  0x13bc800 INFO         imxv4l2videosrc v4l2src.c:317:gst_imx_v4l2src_negotiate:<imxv4l2videosrc0> negotiated caps video/x-raw, format=(string)I420, width=(int)720, height=(int)576, interlace-mode=(string)progressive, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1
0:00:01.340036120   439  0x13bc800 INFO         imxv4l2videosrc v4l2src.c:349:gst_imx_v4l2src_set_caps:<imxv4l2videosrc0> set caps video/x-raw, format=(string)I420, width=(int)720, height=(int)576, interlace-mode=(string)progressive, framerate=(fraction)25/1, pixel-aspect-ratio=(fraction)1/1
0:00:01.409789042   439  0x13bc800 TRACE             imxblitter blitter.c:253:gst_imx_blitter_set_input_frame:<imxipublitter0> input frame uses DMA memory - setting it directly as input frame
0:00:01.410202717   439  0x13bc800 LOG      imxblittervideosink video_sink.c:984:gst_imx_blitter_video_sink_select_fb_page:<imxipuvideosink0> switching to page 0
0:00:01.410620724   439  0x13bc800 LOG            imxipublitter blitter.c:363:gst_imx_ipu_blitter_fill_region:<imxipublitter0> fill op task input:  width:  8  height: 8  format: 0x34424752  crop: 0,0 8x8  phys addr 0x24ffe000  deinterlace enable 0 motion 0x0
0:00:01.411022065   439  0x13bc800 LOG            imxipublitter blitter.c:372:gst_imx_ipu_blitter_fill_region:<imxipublitter0> fill op task output:  width:  800  height: 480  format: 0x41524742  crop: 0,0 800x480  paddr 0x2c400000  rotate: 0
0:00:01.411500407   439  0x13bc800 LOG          imxipuallocator allocator.c:123:gst_imx_ipu_map_phys_mem:<imxipuallocator0> mapped IPU physmem memory:  virt addr 0x76f65000  phys addr 0x24ffe000
0:00:01.411909081   439  0x13bc800 LOG          imxipuallocator allocator.c:135:gst_imx_ipu_unmap_phys_mem:<imxipuallocator0> unmapped IPU physmem memory:  virt addr 0x76f65000  phys addr 0x24ffe000
0:00:01.414017785   439  0x13bc800 LOG            imxipublitter blitter.c:424:gst_imx_ipu_blitter_blit:<imxipublitter0> main_task input:  width:  720  height: 576  format: 0x30323449 (I420)  crop: 0,0 720x576  phys addr 0x2c400000  deinterlace enable 0 motion 0x0
0:00:01.414403792   439  0x13bc800 LOG            imxipublitter blitter.c:434:gst_imx_ipu_blitter_blit:<imxipublitter0> main_task output:  width:  800  height: 480  format: 0x41524742 (BGRA)  crop: 100,0 600x480  paddr 0x2c400000  rotate: 0
0:00:01.454767852   439  0x13bc800 TRACE             imxblitter blitter.c:253:gst_imx_blitter_set_input_frame:<imxipublitter0> input frame uses DMA memory - setting it directly as input frame
0:00:01.455003190   439  0x13bc800 LOG      imxblittervideosink video_sink.c:984:gst_imx_blitter_video_sink_select_fb_page:<imxipuvideosink0> switching to page 1
0:00:01.455135859   439  0x13bc800 LOG            imxipublitter blitter.c:424:gst_imx_ipu_blitter_blit:<imxipublitter0> main_task input:  width:  720  height: 576  format: 0x30323449 (I420)  crop: 0,0 720x576  phys addr 0x2df00000  deinterlace enable 0 motion 0x0
0:00:01.455305528   439  0x13bc800 LOG            imxipublitter blitter.c:434:gst_imx_ipu_blitter_blit:<imxipublitter0> main_task output:  width:  800  height: 480  format: 0x41524742 (BGRA)  crop: 100,0 600x480  paddr 0x2c577000  rotate: 0

**Comment by angelobt** [comment]
additional information

kernel = 3.14.28 (91cf351a2afc17ac4a260e4d2ad1e32d00925a1b git://git.freescale.com/imx/linux-2.6-imx.git)

yocto = fido 1.8.0

video in = pal 720x576 UYVY interleaved

let me know if you need other logs or infomations

**Comment by angelobt** [comment]
If you want more information, you can point me where to add prints inside kernel, and I can do tests for you.
let me know if you want any help.

**Comment by dv1** [comment]
As it turns out, I wasn't re-requesting the fixed screen info after reconfiguring the framebuffer. Also, I added more error logging in case reconfiguring fails. Please try now.

**Comment by angelobt** [comment]
Thanks now it works!!!!

Now I go deep with other tests

**Comment by dv1** [comment]
Alright, good to hear. If anything else comes up, please open new issues. I'll close this one.
