### ISSUE TITLE
Respect Pixel Aspect Ratio in imxvpuenc_h264

### ISSUE THREAD

**Issue by waechtjn** [Freescale/gstreamer-imx#41]
As it seems, imxvpuenc_h264 currently does not respect the pixel aspect ratio of its input by omitting VUI information in the SPS header(s). This causes the resulting video to be displayed in the wrong aspect ratio in certain players.

Consider the pipelines

```
gst-launch-1.0 videotestsrc num-buffers=1000 ! "video/x-raw, format=I420, pixel-aspect-ratio=(fraction)64/45, width=720, height=576" ! progressreport ! x264enc ! h264parse ! mp4mux ! filesink location=t.mp4
```

and

```
gst-launch-1.0 videotestsrc num-buffers=1000 ! "video/x-raw, format=I420, pixel-aspect-ratio=(fraction)64/45, width=720, height=576" ! progressreport ! imxvpuenc_h264 quant-param=23 ! h264parse ! mp4mux ! filesink location=t.mp4
```

While the file belonging to the first one plays correctly in VLC and in Windows Media Player, the second one only plays correctly in VLC; Windows Media Player assumes it has a 1:1 pixel aspect ratio and plays it in 5:4. A similar phenomenon is likely to happen in other players as well.

I assume this happens because the VPU's h264 stream does not contain VUI information in its SPS headers. This is indicated by the comparison of h264_analyze's output for both streams.
x264:

```
!! Found NAL at offset 4 (0x0004), size 29 (0x001D) 
XX 00 00 00 01 67 64 00 1F AC D9 40 B4 12 6F FC 01 

==================== NAL ====================
 forbidden_zero_bit : 0 
 nal_ref_idc : 3 
 nal_unit_type : 7 ( Sequence parameter set ) 
======= SPS =======
 profile_idc : 100 
 constraint_set0_flag : 0 
 constraint_set1_flag : 0 
 constraint_set2_flag : 0 
 constraint_set3_flag : 0 
 constraint_set4_flag : 0 
 constraint_set5_flag : 0 
 reserved_zero_2bits : 0 
 level_idc : 31 
 seq_parameter_set_id : 0 
 chroma_format_idc : 1 
 residual_colour_transform_flag : 0 
 bit_depth_luma_minus8 : 0 
 bit_depth_chroma_minus8 : 0 
 qpprime_y_zero_transform_bypass_flag : 0 
 seq_scaling_matrix_present_flag : 0 
 log2_max_frame_num_minus4 : 0 
 pic_order_cnt_type : 0 
   log2_max_pic_order_cnt_lsb_minus4 : 2 
   delta_pic_order_always_zero_flag : 0 
   offset_for_non_ref_pic : 0 
   offset_for_top_to_bottom_field : 0 
   num_ref_frames_in_pic_order_cnt_cycle : 0 
 num_ref_frames : 4 
 gaps_in_frame_num_value_allowed_flag : 0 
 pic_width_in_mbs_minus1 : 44 
 pic_height_in_map_units_minus1 : 35 
 frame_mbs_only_flag : 1 
 mb_adaptive_frame_field_flag : 0 
 direct_8x8_inference_flag : 1 
 frame_cropping_flag : 0 
   frame_crop_left_offset : 0 
   frame_crop_right_offset : 0 
   frame_crop_top_offset : 0 
   frame_crop_bottom_offset : 0 
 vui_parameters_present_flag : 1 
=== VUI ===
 aspect_ratio_info_present_flag : 1 
   aspect_ratio_idc : 255 
     sar_width : 64 
     sar_height : 45 
 overscan_info_present_flag : 0 
   overscan_appropriate_flag : 0 
 video_signal_type_present_flag : 0 
   video_format : 0 
   video_full_range_flag : 0 
   colour_description_present_flag : 0 
     colour_primaries : 0 
   transfer_characteristics : 0 
   matrix_coefficients : 0 
 chroma_loc_info_present_flag : 0 
   chroma_sample_loc_type_top_field : 0 
   chroma_sample_loc_type_bottom_field : 0 
 timing_info_present_flag : 1 
   num_units_in_tick : 1 
   time_scale : 60 
   fixed_frame_rate_flag : 1 
 nal_hrd_parameters_present_flag : 0 
 vcl_hrd_parameters_present_flag : 0 
   low_delay_hrd_flag : 0 
 pic_struct_present_flag : 0 
 bitstream_restriction_flag : 1 
   motion_vectors_over_pic_boundaries_flag : 1 
   max_bytes_per_pic_denom : 0 
   max_bits_per_mb_denom : 0 
   log2_max_mv_length_horizontal : 11 
   log2_max_mv_length_vertical : 11 
   num_reorder_frames : 2 
   max_dec_frame_buffering : 4 
=== HRD ===
 cpb_cnt_minus1 : 0 
 bit_rate_scale : 0 
 cpb_size_scale : 0 
   bit_rate_value_minus1[0] : 0 
   cpb_size_value_minus1[0] : 0 
   cbr_flag[0] : 0 
 initial_cpb_removal_delay_length_minus1 : 0 
 cpb_removal_delay_length_minus1 : 0 
 dpb_output_delay_length_minus1 : 0 
 time_offset_length : 0 
!! Found NAL at offset 37 (0x0025), size 5 (0x0005) 
...
```

VPU:

```
!! Found NAL at offset 4 (0x0004), size 9 (0x0009) 
XX 00 00 00 01 67 42 40 1F A6 80 B4 12 64 
==================== NAL ====================
 forbidden_zero_bit : 0 
 nal_ref_idc : 3 
 nal_unit_type : 7 ( Sequence parameter set ) 
======= SPS =======
 profile_idc : 66 
 constraint_set0_flag : 0 
 constraint_set1_flag : 1 
 constraint_set2_flag : 0 
 constraint_set3_flag : 0 
 constraint_set4_flag : 0 
 constraint_set5_flag : 0 
 reserved_zero_2bits : 0 
 level_idc : 31 
 seq_parameter_set_id : 0 
 chroma_format_idc : 1 
 residual_colour_transform_flag : 0 
 bit_depth_luma_minus8 : 0 
 bit_depth_chroma_minus8 : 0 
 qpprime_y_zero_transform_bypass_flag : 0 
 seq_scaling_matrix_present_flag : 0 
 log2_max_frame_num_minus4 : 1 
 pic_order_cnt_type : 2 
   log2_max_pic_order_cnt_lsb_minus4 : 0 
   delta_pic_order_always_zero_flag : 0 
   offset_for_non_ref_pic : 0 
   offset_for_top_to_bottom_field : 0 
   num_ref_frames_in_pic_order_cnt_cycle : 0 
 num_ref_frames : 1 
 gaps_in_frame_num_value_allowed_flag : 0 
 pic_width_in_mbs_minus1 : 44 
 pic_height_in_map_units_minus1 : 35 
 frame_mbs_only_flag : 1 
 mb_adaptive_frame_field_flag : 0 
 direct_8x8_inference_flag : 1 
 frame_cropping_flag : 0 
   frame_crop_left_offset : 0 
   frame_crop_right_offset : 0 
   frame_crop_top_offset : 0 
   frame_crop_bottom_offset : 0 
 vui_parameters_present_flag : 0 
=== VUI ===
 aspect_ratio_info_present_flag : 0 
   aspect_ratio_idc : 0 
     sar_width : 0 
     sar_height : 0 
 overscan_info_present_flag : 0 
   overscan_appropriate_flag : 0 
 video_signal_type_present_flag : 0 
   video_format : 0 
   video_full_range_flag : 0 
   colour_description_present_flag : 0 
     colour_primaries : 0 
   transfer_characteristics : 0 
   matrix_coefficients : 0 
 chroma_loc_info_present_flag : 0 
   chroma_sample_loc_type_top_field : 0 
   chroma_sample_loc_type_bottom_field : 0 
 timing_info_present_flag : 0 
   num_units_in_tick : 0 
   time_scale : 0 
   fixed_frame_rate_flag : 0 
 nal_hrd_parameters_present_flag : 0 
 vcl_hrd_parameters_present_flag : 0 
   low_delay_hrd_flag : 0 
 pic_struct_present_flag : 0 
 bitstream_restriction_flag : 0 
   motion_vectors_over_pic_boundaries_flag : 0 
   max_bytes_per_pic_denom : 0 
   max_bits_per_mb_denom : 0 
   log2_max_mv_length_horizontal : 0 
   log2_max_mv_length_vertical : 0 
   num_reorder_frames : 0 
   max_dec_frame_buffering : 0 
=== HRD ===
 cpb_cnt_minus1 : 0 
 bit_rate_scale : 0 
 cpb_size_scale : 0 
   bit_rate_value_minus1[0] : 0 
   cpb_size_value_minus1[0] : 0 
   cbr_flag[0] : 0 
 initial_cpb_removal_delay_length_minus1 : 0 
 cpb_removal_delay_length_minus1 : 0 
 dpb_output_delay_length_minus1 : 0 
 time_offset_length : 0 
!! Found NAL at offset 17 (0x0011), size 5 (0x0005) 
...
```

Unfortunately, I could not find information on whether the VPU supports VUI information in SPS headers by using `vpu_EncGiveCommand()` and `ENC_PUT_AVC _HEADER` (or any of the other methods to specify headers) nor does this functionality seem to be exposed by the VPU Wrapper Library.

A possible fall-back solution is to amend the SPS headers with VUI information (pixel aspect ratio) manually after receiving them from the VPU.

**Comment by dv1** [comment]
I have considered this several times, and I do agree that it would be best to add VUI information to the SPS headers, but only recently it has become possible to do this in an efficient manner: a sister project to gstreamer-imx , https://github.com/Freescale/libimxvpuapi , is a replacement for libfslvpuwrap on i.MX6 devices. It now has a backend which uses imx-vpu directly. This backend keeps a copy of the SPS header, and manually inserts it in front of I/IDR frames. It is therefore much simpler now to just modify this copy. The next gstreamer-imx release will use libimxvuapi in rewritten VPU elements. Therefore, this issue actually now belongs to libimxvpuapi, since the VUI information insertion needs to be added there. I'll check if I can squeeze this in before the next libimxvpuapi / gstreamer-imx releases.

**Comment by waechtjn** [comment]
Thank you for your answer; it is great to hear that you are considering this feature. However, I am not sure whether implementing it in libimxvpuapi is the right place since you could no longer treat the SPS headers generated by the VPU as an opaque data blob which you insert into the right positions in the stream. Instead, you need to implement NALU/SPS parsing and writing, which leaves you with two options: implementing it yourself, which is tedious and error-prone, or using some third-party library (x264, gstreamer, ...). In the latter case you would have a dependency to that library directly in libimxvpuapi, which - to me - seems undesirable for such a low-level project.

If you made the SPS data blob accessible via some API function, it would be possible to manipulate it directly from within gstreamer-imx, which already has a dependency on GStreamer and its h264 parsing abilities. (Just my two cents, of course. You probably have a better overview of your projects' architectures.)

I have investigated GStreamer's SPS parsing and generating abilities and you might find the following information helpful if you choose to implement the feature. Unfortunately, GStreamer has not much to offer in generating SPS headers as it even lacks a bitstream writer. Somebody wrote a GstBitWriter (https://bugzilla.gnome.org/show_bug.cgi?id=707543) but it seems to have never been integrated. Also there are some deficiency concerning GStreamer's SPS parsing abilities: if some fields were not present in the original data stream, the parser will include the appropriate default values in its output, which is a reasonable behaviour if you want to get the information but gets in your way if you want to manipulate the SPS as you would generate way more information than necessary (which wastes memory, though not very much admittedly) or need to check against the default values (which is time consuming).

**Comment by dv1** [comment]
True, however the parsing would have to be done once, not for every frame. Still, parsing h.264 data isn't exactly trivial, I agree. And while delegating this to upper layers can make sense, it also means that every integration has to implement it on their own. I'm not sure if this is wise. Anyway, I'll revisit this in the next libimxvpuapi release.
