### ISSUE TITLE
imxipuvideotransform: enable-crop property

### ISSUE THREAD

**Issue by angelobt** [Freescale/gstreamer-imx#47]
Hi,

I have updated to version 0.11.0, but I have noticed that enable-crop property has been removed.

I did a patch to add crop metadata to imxv4l2videosrc in order to let imxipuvideotransform to perform the crop operation.
I need this behaviour because my pipeline creates many branches (tee) after imxipuvideotransform.

Is there an other way to achieve the same result ?

Thanks

**Comment by dv1** [comment]
Right, sorry about that. Cropping was complicating the code, and I couldn't delay the release any longer. I will reintroduce cropping in the next few commits.

**Comment by dv1** [comment]
Reintroduced the crop property (it is called "input-crop" now). It is now in master. The compositor pads also support cropping. Let me know if it works for you. Tests here showed it to be working.
