### ISSUE TITLE
imxvpudec regression

### ISSUE THREAD

**Issue by isaacrj-scio** [Freescale/gstreamer-imx#48]
Hi!

I have just updated to 0.11 and I'm having problems with pipelines that did work perfectly with 0.10.2. The issue seems to be related to imxvpudec, when I use this element in any pipeline the pipeline does start and play perfectly, but it fails on stop with these errors:

`** (gst-launch-1.0:1561): CRITICAL **: gst_video_decoder_negotiate_default: assertion 'state' failed
(gst-launch-1.0:1561): GStreamer-CRITICAL **: gst_buffer_get_meta: assertion 'buffer != NULL' failed
(gst-launch-1.0:1561): GStreamer-CRITICAL **: gst_mini_object_unref: assertion 'mini_object != NULL' failed`

In my app, I'm calling gstreamer from Java and when this happens, gstreamer blows the JVM away, killing my main app with it.

I did some tests on command line swapping elements to try to isolate the issue:

-This works OK: 
`gst-launch-1.0 videotestsrc ! queue ! imxipuvideosink framebuffer=/dev/fb0`

-This works OK too:
`gst-launch-1.0 videotestsrc ! queue ! x264enc tune=zerolatency speed-preset=superfast bitrate=512 ! queue ! h264parse ! queue ! avh264_dec ! queue ! imxipuvideosink framebuffer=/dev/fb0`

-This fails on exit
`gst-launch-1.0 videotestsrc ! queue ! x264enc tune=zerolatency speed-preset=superfast bitrate=512 ! queue ! h264parse ! queue ! imxvpudec ! queue ! imxipuvideosink framebuffer=/dev/fb0`

-This fails on exit too:
`gst-launch-1.0 videotestsrc ! queue ! x264enc tune=zerolatency speed-preset=superfast bitrate=512 ! queue ! h264parse ! queue ! imxvpudec ! queue ! imxv4l2sink device=/dev/video16`

All this tests work and exit nicely on 0.10.2.

Thanks!

**Comment by dv1** [comment]
I was actually tracking this recently. Curiously, these errors do not seem to appear with the current git master version of GStreamer. It is related to the GstVideoCodecFrame values, which aren't released properly. I have a patch, which I tested with various videos. Also, seeking seems to work properly. But I want to run more tests to be sure. Nevertheless, I pushed it now. Please check if it helps.

**Comment by isaacrj-scio** [comment]
Hi again !

I recompiled from git and reinstalled, but now gstreamer is not loading the imxvpu plugin:

`root@sgw-t-scio:~# gst-inspect-1.0 

(gst-plugin-scanner:908): GStreamer-WARNING **: Failed to load plugin '/usr/lib/gstreamer-1.0/libgstimxvpu.so': /usr/lib/gstreamer-1.0/libgstimxvpu.so: undefined symbol: GST_VIDEO_DECODER_CAST`

I'm using gstreamer 1.2.3, built using Yocto

**Comment by dv1** [comment]
OK, try again, fixed that. This macro is new in GStreamer 1.4, and I won't make 1.4 a requirement yet.

**Comment by isaacrj-scio** [comment]
It works perfectly now. Thanks a lot!

**Comment by dv1** [comment]
No problem. Please keep me posted in case something related to this comes up. I anyway plan a cleanup of the VPU elements for the next release.

**Comment by dv1** [comment]
Closing this for now. Feel free to reopen if the issues ever reappears.
