### ISSUE TITLE
Framebuffer cleanup when using imxipuvideosink with use-vsync=true

### ISSUE THREAD

**Issue by isaacrj-scio** [Freescale/gstreamer-imx#49]
Hi again!

Although it's not big deal, I suspect that when using imxipuvideosink with use-vsync=true, only one of the pageflipping pages on the fb gets cleared (filled with black). 

Thus, if you play a 16:9 video and then play a 4:3 one, instead of black bars in either side of the frame, you get blinking bars that alternate black with whatever fragment of frame was left there by the wider video.

The issue can be reproduced from command line by running:

`gst-launch-1.0 videotestsrc ! 'video/x-raw, width=1280, height=720' ! queue ! imxipuvideosink use-vsync=true`

  Followed by:
`gst-launch-1.0 videotestsrc ! 'video/x-raw, width=880, height=720' ! queue ! imxipuvideosink use-vsync=true`

Thank you again!

**Comment by dv1** [comment]
Fixed this in master. Please try if it works for you.

**Comment by isaacrj-scio** [comment]
It works now. Thanks!

**Comment by dv1** [comment]
No problem. Closing the issue now.
