### ISSUE TITLE
imxg2dvideosink - g2d_clear_2d: fail with status -20

### ISSUE THREAD

**Issue by pylorak** [Freescale/gstreamer-imx#58]
Hello,

I am trying to output video to the framebuffer using the G2D engine. I have built the latest version of gstreamer-imx, compiled against kernel 3.10.53 and vendor-supplied BSP-libraries for the same kernel.

The gstreamer pipeline I test with is:

gst-launch-1.0 -v filesrc location="${VIDEO}" !  avidemux ! imxvpudec ! imxg2dvideosink window-x-coord=0 window-y-coord=35 window-width=438 window-height=248 framebuffer="/dev/fb0"

It fails to draw anything to the screen, and outputs "g2d_clear_2d: fail with status -20" in the console for (probably) every frame.

If I replace imxg2dvideosink with imxipuvideosink it works almost perfectly, except that the IPU engine doesn't output in exactly the same location/size as requested in the pipeline parameters above. I still get a "good" picture with the IPU, except for the position and size of the video, which is why I need the G2D engine. 

The video is I420, 960x544 on an iMX.6 Quad board. See gstreamer console log below. 

Thank you for your support.

Console log:
--------------------------------------------------
Setting pipeline to PAUSED ...
[INFO]  Product Info: i.MX6Q/D/S
Pipeline is PREROLLING ...
/GstPipeline:pipeline0/GstImxVpuDec:imxvpudec0.GstPad:sink: caps = image/jpeg, framerate=(fraction)25/1, width=(int)960, height=(int)544
[INFO]  bitstreamMode 1, chromaInterleave 0, mapType 0, tiled2LinearEnable 0
/GstPipeline:pipeline0/GstImxVpuDec:imxvpudec0.GstPad:src: caps = video/x-raw, format=(string)I420, width=(int)960, height=(int)544, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, colorimetry=(string)bt601, framerate=(fraction)25/1
/GstPipeline:pipeline0/GstImxG2DVideoSink:imxg2dvideosink0.GstPad:sink: caps = video/x-raw, format=(string)I420, width=(int)960, height=(int)544, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, colorimetry=(string)bt601, framerate=(fraction)25/1
g2d_clear_2d: fail with status -20
Pipeline is PREROLLED ...
Setting pipeline to PLAYING ...
g2d_clear_2d: fail with status -20
New clock: GstSystemClock
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
g2d_clear_2d: fail with status -20
^Chandling interrupt.
Interrupt: Stopping pipeline ...
Execution ended after 0:00:00.914979929
Setting pipeline to PAUSED ...
g2d_clear_2d: fail with status -20
Setting pipeline to READY ...
Setting pipeline to NULL ...
Freeing pipeline ...

**Comment by dv1** [comment]
Hi, sorry for the late reply. I tried this out, but I don't get an error. What i.MX6Quad-based is this? Also, can you re-run your pipeline with the GST_DEBUG environment variable set to "2,*imx*:5,*g2d*:9" ?

**Comment by pylorak** [comment]
Sorry, I intend to help provide all the information necessary, but I have no way right now. I will post here again as soon as I get a chance. It will surely happen, but might take a few weeks for reasons not in my control.

**Comment by pylorak** [comment]
I have the hardware in my hands again. Running the gstreamer pipeline with the debug options you suggested, imxg2dvideosink told me it doesn't support the display format. Added ",bpp=16" to the video options on the kernel command line, and all works fine now. Thank you for your help.
