### ISSUE TITLE
Pipeline crashes with imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT

### ISSUE THREAD

**Issue by FrankBau** [Freescale/gstreamer-imx#60]
I'm using a tw6869 PCIe device for /dev/video1

The following pipeline works perfectly:
`gst-launch-1.0 imxv4l2videosrc device=/dev/video1 input=0 ! imxipuvideotransform ! fakesink`

But, when I insert a H.264 (or other) encoder, the pipeline crashes the whole system and a reset is needed:
`gst-launch-1.0 imxv4l2videosrc device=/dev/video1 input=0 ! imxipuvideotransform ! imxvpuenc_h264 ! fakesink`

The last message I get on the console is: `imx-ipuv3 2400000.ipu: IPU Warning - IPU_INT`

The video format at the source is `'video/x-raw, format=(string)UYVY, width=(int)720, height=(int)576, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, colorimetry=(string)bt601, framerate=(fraction)25/1'`, for the encoder it needs to be converted to I420.

The video driver code is hosted here https://github.com/FrankBau/tw6869 and used to work with  version 0.10.1 (when the component still was named imxv4l2src). The video driver relies heavily  on videobuf2. 

When I replace imxv4l2videosrc by videotestsrc, the pipeline works too:
`gst-launch-1.0 videotestsrc ! 'video/x-raw, format=(string)UYVY, width=(int)720, height=(int)576, pixel-aspect-ratio=(fraction)1/1, interlace-mode=(string)progressive, colorimetry=(string)bt601, framerate=(fraction)25/1' ! imxipuvideotransform ! imxvpuenc_h264 ! fakesink`

I'm clueless how to dig further into that. Any ideas appreciated.

Frank

**Comment by dv1** [comment]
The main problem I see here is that I do not have this hardware, nor can I receive any analog TV signals (if I see this right, the tw6869 is used for capturing analog TV signals?). Does running this with the GST_DEBUG environment variable set to "2,*imx*:9" produce any logs before the reset?

**Comment by FrankBau** [comment]
Thanks for your suggestion. I did that but uploading the log file failed. The last few lines before the crash come from imxipublitter0 telling that a UYVY -> I420 conversion is needed:

`0:00:03.427319667  3815    0xbf8c0 LOG          imxv4l2videosrc v4l2src.c:269:gst_imx_v4l2src_fill:<imxv4l2videosrc0> fill`

`0:00:03.427400667  3815    0xbf8c0 LOG     imxblittervideotransform blitter_video_transform.c:1136:gst_imx_blitter_video_transform_prepare_output_buffer:<imxipuvideotransform0> input and output caps are not equal`

`0:00:03.427454001  3815    0xbf8c0 LOG     imxblittervideotransform blitter_video_transform.c:1142:gst_imx_blitter_video_transform_prepare_output_buffer:<imxipuvideotransform0> passthrough: no`

`0:00:03.427532001  3815    0xbf8c0 LOG            imxipublitter blitter.c:321:gst_imx_ipu_blitter_set_input_frame:<imxipublitter0> input stream is progressive -> no deinterlacing necessary`

`0:00:03.427581667  3815    0xbf8c0 TRACE         imxbaseblitter base_blitter.c:154:gst_imx_base_blitter_set_input_buffer:<imxipublitter0> input buffer uses DMA memory - setting it as actual input buffer`

`0:00:03.427635667  3815    0xbf8c0 LOG            imxipublitter blitter.c:417:gst_imx_ipu_blitter_blit_frame:<imxipublitter0> task input:  width:  720  height: 576  format: 0x59565955 (UYVY)  crop: 0,0 720x576  phys addr 0xcb000  deinterlace enable 0 motion 0x0`

`0:00:03.427721334  3815    0xbf8c0 LOG            imxipublitter blitter.c:427:gst_imx_ipu_blitter_blit_frame:<imxipublitter0> task output:  width:  720  height: 576  format: 0x30323449 (I420)  crop: 0,0 0x0  paddr 0x6e500000  rotate: 0`

`0:00:03.427826001  3815    0xbf8c0 LOG            imxipublitter blitter.c:440:gst_imx_ipu_blitter_blit_frame:<imxipublitter0> need to clear empty regions`

`0:00:03.427872001  3815    0xbf8c0 LOG            imxipublitter blitter.c:469:gst_imx_ipu_blitter_blit_frame:<imxipublitter0> clear op task input:  width:  64  height: 64  format: 0x34424752  crop: 0,0 64x64  phys addr 0x7db2c000  deinterlace enable 0 motion 0x0`

`0:00:03.427948334  3815    0xbf8c0 LOG      imx-ipuv3 2400000.ipu: IPU`

The thing is that address `0xcb000` looks odd. The other addresses were allocated somewhere earlier, but this is the first occurrence of  `0xcb000`.
The tw6869 driver relies on videobuf2:

`	q->mem_ops = &vb2_dma_contig_memops;`

I will try to debug further into that direction...

**Comment by sasamy** [comment]
Hello,
imxv4l2videosrc at the moment supports only V4L2_FIELD_INTERLACED - you can try to use it in the driver instead of V4L2_FIELD_INTERLACED_BT / V4L2_FIELD_INTERLACED_TB, otherwise frames incorrectly are considered as non-interlaced.

**Comment by dv1** [comment]
Hello,
thanks @sasamy . @FrankBau , if this fixes the issue, please leave a comment about it.

**Comment by FrankBau** [comment]
Hi,
I close this because it is not an gstreamer-imx issue but a driver issue. 
Frank

**Comment by jigneshpatel47** [comment]
Hi @FrankBau ,

I am also facing the same issue.

My Application getting crashed some times after printing below:
`0:00:02.244321000 \0x1b[331m  456\0x1b[00m  0x169b400 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:456:gst_imx_v4l2src_fill:<imxv4l2videosrc0>\0x1b[00m fill`

when my application is not crashing it prints :

> 
> 0:00:02.255064334 \0x1b[331m  456\0x1b[00m  0x2d3b000 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00m     imxv4l2videosrc v4l2src.c:456:gst_imx_v4l2src_fill:<imxv4l2videosrc0>\0x1b[00m fill
> 0:00:02.341767667 \0x1b[331m  456\0x1b[00m  0x2d3b000 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00mimxblittervideotransform video_transform.c:1296:gst_imx_blitter_video_transform_prepare_output_buffer:<imxg2dvideotransform0>\0x1b[00m input and output caps are not equal
> 0:00:02.341854667 \0x1b[331m  456\0x1b[00m  0x2d3b000 \0x1b[33;01mLOG    \0x1b[00m \0x1b[00mimxblittervideotransform video_transform.c:1304:gst_imx_blitter_video_transform_prepare_output_buffer:<imxg2dvideotransform0>\0x1b[00m passthrough: no
> 0:00:02.341981334 \0x1b[331m  456\0x1b[00m  0x2d3b000 \0x1b[37mDEBUG  \0x1b[00m \0x1b[00m imxphysmemallocator phys_mem_allocator.c:139:gst_imx_phys_mem_allocator_alloc_internal:<imxg2dallocator1>\0x1b[00m alloc_internal called: maxsize: 1228800, align: 0, offset: 0, size: 1228800

Can you please help me, how can you have solved the issue?

Thanks,
Jignesh Patel
