### ISSUE TITLE
imxipuvideotransform problem with 1920x1080

### ISSUE THREAD

**Issue by fictionjs** [Freescale/gstreamer-imx#61]
Hello!
Is it possible to make colorspace conversion for format 1920x1080 using imxipuvideotransform? I get the following error:
`inw 2, onw 480, ilw 8, ilc 0, olw 1440, irw 8, irc 2, orw 1440, orc 480, difwr 18446744069533073408, lirr 34`
`mxc_ipu mxc_ipu: split mode output width overflow`
`mxc_ipu mxc_ipu: ERR: no-0x0,ipu_queue_task err:-22`

I guess it is because of the limitations in IPU (max 1024x1024), but why is it able to convert 1280x720 but not 1920x1080? If I understand it correctly, 1920 image is splitted into 480/1440. So it is still too large to be served by the IPU. Should I split it into more pieces?

**Comment by dv1** [comment]
Can you paste an example gst-launch pipeline? 1920x1080 should work with colorspace conversions. It is downscaling that you have to be careful about. See https://github.com/Freescale/gstreamer-imx/issues/27#issuecomment-149328711 for an explanation why. This will be fixed in a later release, since it requires a significant number of workarounds and special handling.

**Comment by fictionjs** [comment]
I have noticed, that the Y42B to I420 conversion works if the width is not bigger then 1360 pixels. Here is the pipeline that works:
>gst-launch-1.0 -v videotestsrc ! 'video/x-raw,format=(string)Y42B, width=1920, height=1080, framerate=30/1' ! imxipuvideotransform ! 'video/x-raw,format=(string)I420, width=1360, height=1080, framerate=30/1' ! imxipuvideosink sync=false

and the one that does not work:
>gst-launch-1.0 -v videotestsrc ! 'video/x-raw,format=(string)Y42B, width=1920, height=1080, framerate=30/1' ! imxipuvideotransform ! 'video/x-raw,format=(string)I420, width=1400, height=1080, framerate=30/1' ! imxipuvideosink sync=false

**Comment by dv1** [comment]
Hrm. Then this could indeed be a splitting issue. Difficult to say, because the IPU driver code is such a messy maze. I could also imagine that the source and/or destination color format is important. What happens if try some RGB formats for example?

**Comment by fictionjs** [comment]
I would have to double check it, but I am 90% sure it was the same for RGB output format. I have not tried RGB input format yet.

**Comment by fictionjs** [comment]
It seems that the problem #27 is very similar to mine. I am pretty sure that the splitting issue is fault of the IPU driver. I have tested different widths of images (for YUV->YUV, RGB->YUV and YUV->RGB conversion), and the split ratios are:
640/640 for 1280
688/672 for 1360 (the same for 1368 - the last one that actually works)
1032/344 for 1376
1040/352 for 1392
1200/400 for 1600
1440/480 for 1920

I have tested that on Sabre Lite, and the versions of software are: GStreamer-imx Plugins 0.11.1, Linux 3.14.38.

**Comment by fictionjs** [comment]
Ok, so I have noticed another strange thing. When I try the following pipeline:	
>gst-launch-1.0 videotestsrc num-buffers=3 ! 'video/x-raw,format=(string)Y42B, width=1360, height=480, framerate=30/1' ! imxipuvideotransform ! 'video/x-raw,format=(string)I420, width=1360, height=480, framerate=30/1' ! fakesink

I can see, that the function ipu_calc_stripes_sizes() is called 4 times: 
* 1) input: 8x8 RGB4, output: 1360x480 I420 (1360 is splitted into 1016/344)
* 2, 3, 4) input: 1360x480 422P, output: 1360x480 I420 (1360 is splitted into 688/672)

That pipeline works fine. But when I try:
>gst-launch-1.0 videotestsrc num-buffers=3 ! 'video/x-raw,format=(string)Y42B, width=1408, height=480, framerate=30/1' ! imxipuvideotransform ! 'video/x-raw,format=(string)I420, width=1408, height=480, framerate=30/1' ! fakesink

ipu_calc_stripes_sizes() is called 3 times:
* 1, 2, 3) input: 8x8 RGB4, output: 1408x480 I420 (1408 is splitted into 1056/352)

That pipeline does not work. So I am not sure anymore, if it is trying to make Y42B->I420 conversion for widths bigger than 1360 pixels at all.

**Comment by fictionjs** [comment]
After changing src/ipu/blitter.c according to: "ipu: Increase fill frame width from 8 to 64 pixels" from master branch the problem disappeared. So it seems that the plugin version was too old. Now the pipeline works fine:
>gst-launch-1.0 videotestsrc ! 'video/x-raw,format=(string)Y42B, width=1920, height=1080, framerate=30/1' ! imxipuvideotransform ! 'video/x-raw,format=(string)I420, width=1920, height=1080, framerate=30/1' ! fakesink

It shows only the following warnings:
mxc_ipu mxc_ipu: output u/v offset not 8 align
mxc_ipu mxc_ipu: output u/v offset not 8 align
imx-ipuv3 2800000.ipu: IDMAC21's U offset is not 8-byte aligned
imx-ipuv3 2800000.ipu: IDMAC21's V offset is not 8-byte aligned
imx-ipuv3 2800000.ipu: IDMAC22's U offset is not 8-byte aligned
imx-ipuv3 2800000.ipu: IDMAC22's V offset is not 8-byte aligned
