### ISSUE TITLE
Issue Streaming HLS created with imxvpuenc_h264 vs 

### ISSUE THREAD

**Issue by cottrelld** [Freescale/gstreamer-imx#63]
Hi.

We’re attempting to stream RTMP/HLS from a hardware encoded stream using imxvpuenc_h264 (built from the latest on master).

The RTMP stream plays ok, but we're having issues with HLS.  A similar pipeline using the software encoder does work and play in safari/iOS devices well.

The simplified gstreamer pipelines are below.  Are you able to please take a look to help see why the stream works from the software encoder but not the hardware encoder?

**GStreamer line to create a hardware encoded h.264 line and stream it via RTMP (does not work with HLS):**

gst-launch-1.0 -e videotestsrc ! imxvpuenc_h264 bitrate=3000 idr-interval=16 ! h264parse ! flvmux streamable=true name=mux ! queue ! rtmpsink location="rtmp://104.197.190.7/live/test"

(tested by opening in http://104.197.190.7:1935/live/test/playlist.m3u8 in safari)

**GStreamer line to create a software encoded h.264 line and stream it via RTMP  (works with HLS):**

gst-launch-1.0 -e videotestsrc ! x264enc bitrate=3000 key-int-max=16 ! video/x-h264,profile=constrained-baseline ! h264parse ! flvmux streamable=true name=mux ! queue ! rtmpsink location="rtmp://104.197.190.7/live/test"

Thanks,
-David

**Comment by dv1** [comment]
These links give me a 404 error.

**Comment by oshoemaker** [comment]
In order for those links to be valid the stream must be active. To test, please run one of the commands mentioned in the previous post, wait 5 seconds, and visit the URL.

**Comment by dv1** [comment]
Can you provide some example pipelines that use HLS? I tried several, but they all worked. And when you say "latest master", do you refer to the version that now uses libimxvpuapi?

**Comment by willnewton** [comment]
This issue should now be resolved.

**Comment by dv1** [comment]
Excellent, thanks for the info.
