### ISSUE TITLE
gstphotography-1.0 : not found

### ISSUE THREAD

**Issue by fictionjs** [Freescale/gstreamer-imx#66]
While configuring gst1-imx I can see that gstphotography-1.0 is not found:                     
> Checking for 'gstreamer-1.0 >= 1.2.0'                        : yes
Checking for 'gstreamer-base-1.0 >= 1.2.0'                   : yes
Checking for 'gstreamer-audio-1.0 >= 1.2.0'                  : yes
Checking for 'gstreamer-video-1.0 >= 1.2.0'                  : yes
Checking for library gstphotography-1.0                      : not found

I can see also that libgstphotography-1.0 in gst1-plugins-bad-1.6.1 is built. But I am not sure if this is the library that is required. 
All I want to do is to build imxv4l2videosrc. Can you help me?

**Comment by dv1** [comment]
Look into build/config.log . It tells you more details about why this check failed. Also, does libgstphotography-1.0 exist in the rootfs? Depending on the distro, it might be in /usr/lib or in /usr/lib/<architecture>/ (the latter is typical in Debian based rootfs).

**Comment by fictionjs** [comment]
libgstphotography-1.0 was built for TARGET, but not for HOST. After adding:
>GST1_PLUGINS_BAD_INSTALL_STAGING = YES

in buildroot/package/gstreamer1/gst1-plugins-bad/gst1-plugins-bad.mk everything is fine. Thanks!
