### ISSUE TITLE
Leaking hardware buffer when destroying pipeline

### ISSUE THREAD

**Issue by tfriem** [Freescale/gstreamer-imx#67]
When using the vpu hardware decoder the used hardware buffers are not freed after destroying a pipeline.

This is a small sample program that repeatly plays a video file and it crashes after some time because there is no memory left: [test_gst_parse_launch.txt](https://github.com/Freescale/gstreamer-imx/files/38942/test_gst_parse_launch.txt)

Additionally we check the number of hardware buffers while running the test application with the command:
`watch --interval=0.5 'cat /proc/APPLICATION_PID_HERE/maps | grep mxc_vpu | wc -l'`
and it's constantly increasing until the crash.

Setup:
* Freescale IMX 6 Quad (automotive or something like that)
* gstreamer 1.4.5
* gstreamer-imx current master (813756a0cb70d7aa609c3d35427179e75ca10013)
  * same with release 0.11.1
* libimxvpuapi release 0.10.0
* imx-vpu 1_3.10.17-1.0.0-r0

**Comment by dv1** [comment]
Do you also see this with fakesink instead of tcpserversink? Also, is the mjpeg encoder necessary, or does it also happen with a pipeline like `filesrc location=video.flv ! flvdemux ! h264parse ! imxvpudec ! fakesink sync=true` ?

**Comment by dv1** [comment]
Okay, I fixed this in libimxvpuapi. Checkout the latest master of that library. With that, the leaks are gone for me.

**Comment by tfriem** [comment]
Thank you for your help. The provided example is now working without leaks. 

But our full application (mixing 4x h264 ->  1x mjpeg) still has the same problem. We will try to isolate when this happens and provide more information on it.

**Comment by dv1** [comment]
Does it happen with 0.11.1 ? Or just with master?

**Comment by tfriem** [comment]
It happens with gstreamer-imx 0.11.1 as well. We updated to master because we saw some fixes regarding leaks and hoped they will solve our problem.

We can break it down to the imxvpudec, as we have a version with the h264_decoder from vanilla gstreamer working well (running a few hours with switches every 10s without any crashes).

Maybe something when using multiple imxvpudec in the same pipeline, as we have 4 different input streams?

I will do some more testing tomorrow.

**Comment by tfriem** [comment]
We can't get any example program ready to reproduce our problem. So the general pipeline setup works well (4x decoder + mixing + 1x encoder).

But when comparing the log output from the example application to our application, we could see a difference regarding the vpu init instance counter. In our application it doesn't reach zero and the vpu is not unloaded. But according to the logs in both cases an unref and stop is called on the decoder.

We are still trying to find out where the difference is.

**Comment by dv1** [comment]
Here's a possibility: perhaps for some reason, Qt5 does not unref the decoded video frame that comes from the VPU properly. Such a frame is stored in a GstBuffer, and said GstBuffer will keep its associated allocator alive. The allocator in this case is a VPU allocator object. Through libimxvpuapi, this object calls vpu_UnInit() only if *all* references to it are gone (frames, decoders ...), including the aforementioned GstBuffer. vpu_UnInit() ís the counterpart to vpu_Init(). The latter calls the IOSystemInit() function inside the imx-vpu library. This function opens a file descriptor to /dev/mxc_vpu , and mmaps it. vpu_Uninit() does the opposite, munmap-ing and closing the FD.

**Comment by tfriem** [comment]
After a lot of testing, we found the cause of the problem. It seems to be missing or wrong fps information in the video source. We could see the difference when connecting to a real camera and connecting to the gestreamer rtsp-server. On the real camera the rtspsrc in gstreamer is displaying 0 fps. When connected to the rtsp-server it displays the correct fps.

We could build a workaround in our application by adding fps caps in front of the decoder. Not sure if the root cause ins in gstreamer or this plugins. But we have tested two different IP cameras from diferent vendors, so the missin/wrong fps doesn't look like an edge case for me.

**Comment by dv1** [comment]
Ah! Interesting. How do you see the FPS? I need this information to reconstruct this. I can imagine that some sort of metadata is missing.

**Comment by tfriem** [comment]
I'm looking at the autogenerated caps in the pipeline while in playing state. The pipeline is rtspsrc -> rtph264depay -> h264parse -> imxvpudec -> videomixer... With the "broken" cameras, the fps between all this elements are shown as 0. It changes after the videomixer, where 25 fps is shown. The real output of the cameras is 12 fps.

But even with the broken fps, the output of the pipeline is fine. So for me it looks like if just the cleanup routine is using the fps information. As we are using a capsfilter element as a workaround to set the right fps right before the imxvpudec, it may be possible to set a wrong fps for reconstructing the problem. But I'm not sure.

**Comment by dv1** [comment]
I found this stream: rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov with it, I can see that the "framerate" caps is not present until after the h264parse element, where it is set to 0/1.
Try this URL to see if it reconstructs your leak. I couldn't see any.

**Comment by tfriem** [comment]
Sorry for the late answer, I had some other work to do around the holidays.

Our systems are not connected to the internet, so I can't easily test the stream you provided. What I can do is remove our workaround (manually set correct fps) and test it again with the 0.12 release. But it will take some time, as it's not our main focus currently.

**Comment by tfriem** [comment]
I'm not sure what exactly fixed our problems, but we are now running gstreamer 1.6.1 and gstreamer-imx 0.12 and are not experiencing any noticable memory leaks anymore. So I will close this issue.

Thanks for your help!
