### ISSUE TITLE
Outputing to imxXvideosink causes distortion in CSI encoded video

### ISSUE THREAD

**Issue by nickaein** [Freescale/gstreamer-imx#69]
We are trying to encode the incoming CSI video and stream it over network while a Qt application is outputing a video on the display interface. To simulate this situation, we use two pipelines:
- First pipeline for encoding the CSI video input and streaming it over network
- Second pipeline for outputting a sample video to DISP interface.

The problem is that running the second pipleline (which acts as an Qt application) causes distortion in the output of first pipeline. 

I have experimented several cases by varying the second pipeline (the display pipeline). In all cases, the first pipleline (the encoding pipeline) was:

`gst-launch-1.0 -v imxv4l2videosrc ! queue2 ! imxvpuenc_h264 bitrate=6000 idr-interval=100 ! queue2 ! mpegtsmux alignment=7 ! rndbuffersize max=1316 min=1316 ! udpsink host=10.1.1.52  port=6666`

We have tried the followings as the second pipeline:

**Case 1: Pipeline with imxipuvideosink as sink**

Running the following pipleline works as expected (after applying 57431776f8bbd27914abd613d9fb678f21334e74 patch):

`gst-launch-1.0 videotestsrc ! imxipuvideosink`

**Case 2: Pipeline with imxipuvideosink as sink in HD resolution**

However, when the output size resolution is set to 1920x1080, it causes distortion in the encoded video:

`gst-launch-1.0 videotestsrc ! video/x-raw, format=I420, width=1920, height=1080 ! imxipuvideosink`

**Case 3: Pipeline with imxg2dvideosink as sink**

Using `imxg2dvideosink` instead of `imxipuvideosink` leads to distortion in the streamed video:

`gst-launch-1.0 videotestsrc ! imxg2dvideosink`

**Notes**
- If I replace `imxv4l2videosrc` with `videotestsrc ! video/x-raw, format=I420, width=1920, height=1080` there will be no distortion
- I guess the Qt application works just like the Case 3 where G2D (GPU) is employed to output the video. Therefore, solving the issue with Case 3 can solve the acutal problem.
- After running pipleline in Case 3, the pipleline in Case 1 will also causes distortion. Therefore, running Case 3 probably cause some misconfiguration/memory corruption that also effects Case 1

**Comment by dv1** [comment]
What kernel and distro are you using? Running it with Yocto Fido and kernel 3.10.53 on a nitrogen6x here didn't produce any of these issues. I did see a big lag, but this is probably a TS problem. The bitrate seems a bit high, I get regular "freezes". Not sure what that is. Lowering the bitrate gets rid of the problem.

I'll try next with a newer kernel.

**Comment by nickaein** [comment]
I am using Freescale Kernel 3.14.28:

http://git.freescale.com/git/cgit.cgi/imx/linux-2.6-imx.git/tag/?id=rel_imx_3.14.28_1.0.0_ga

and rootfs built with `repo sync`ed Fido branch of [FSL Community BSP](https://freescale.github.io).

The hardware I have tried are [TX6Q](www.karo-electronics.com/tx6q.html) and [TX6DL](http://www.karo-electronics.com/tx6dl.html) CoMs that have i.MX6Q and i.MX6DL processors.

I've also tried GStreamer 0.10 variant of these pipelines on Freescale Kernel 3.10.17 (not 3.10.53 though) with Yocto dizzy and had the same problem. 

If you don't have any issue on 3.14.28 too, does that mean some misconfiguration in the DTB is causing the problem?

**Comment by dv1** [comment]
Could you make a screencapture or a photo of the distortions? No difference on 3.14.28 by the way. So, the source of the problem can actually be in the receiver (as said above), or yes, some misconfiguration. But it would help to know what the distortions look like on your end.

Also, I need to know about the receiver. I tried both vlc and GStreamer as UDP receivers. VLC's image was fine (I sent to port 16666, so the vlc command line was: `vlc udp://@:16666`). GStreamer's looked the same if I set its video sink to ignore timestamps (example:  `gst-launch-1.0 udpsrc port=16666 caps=video/mpegts\,\ systemstream\=\(boolean\)true\,\ packetsize\=\(int\)188 ! decodebin ! autovideosink sync=false` ).

**Comment by nickaein** [comment]
I have recorded the video outputs in different cases using the following pipeline:

`gst-launch-1.0 -v imxv4l2videosrc ! imxvpuenc_h264 bitrate=3000 ! h264parse ! matroskamux ! filesink location=out.mkv`

Here is the pipelines in the order I have run them and their corresponding recorded video by the above pipeline. 
It can be observed how each one is effecting the above:

### 1. imxipuvideosink as the output

**Pipeline:** `gst-launch-1.0 videotestsrc ! imxipuvideosink`
**Sample video:** https://drive.google.com/file/d/0B0xoao6g6xzoTkc4WHFRMEtSOE0
**Notes:** As you can see, everything is fine in this case.

### 2. imxg2dvideosink as the output
**Pipeline:** `gst-launch-1.0 videotestsrc ! imxg2dvideosink`
**Sample video:** https://drive.google.com/file/d/0B0xoao6g6xzoSk9HbXR1czkzWlk
**Notes:** There are occasional jumps (tearing?) in the video output.

### 3. imxg2dvideosink with use-vsync=true
**Pipeline:** `gst-launch-1.0 videotestsrc ! imxg2dvideosink use-vsync=true`
**Sample video:** https://drive.google.com/file/d/0B0xoao6g6xzoOXBUVnExendpWk0
**Notes:** There are many jumps in this case.

### 4. imxg2dvideosink with setting use-vsync back to false
**Pipeline:** `gst-launch-1.0 videotestsrc ! imxg2dvideosink use-vsync=false`
**Sample Video:** https://drive.google.com/file/d/0B0xoao6g6xzoSlkyUEloWHhsNnc
**Notes:** It is interesting that after running pipeline (3), setting `use-vsync` back to false doesn't reduce the jumps. The output in this case is very similar to case 3, while we expected it to be similar to case 2.

**Comment by dv1** [comment]
Very interesting! I have not seen anything even remotely like that.

Also, I missed at first that you also tried out GStreamer 0.10. This rules out gstreamer-imx, since it is 1.0 only. I strongly suspect kernel problems at this point. Perhaps MPEGTS issues as well (dropped packets causing intermittent trouble?).

(At this point I want to emphasize that aside from debugging, using GStreamer 0.10 nowadays must be avoided as much as possible.)

If you have a different imx6 hardware, I'd strongly suggest to try to build Yocto Jethro for it, and try the pipelines there again. As said, I tried them on a nitrogen6x. I'll also try them on a Sabre SD DualLite board once I get access to it.

**Comment by nickaein** [comment]
**One important observation**
I think this worth mentioning: The distortion only happens when there is a _change_ in the video output. For instance, if I run a Qt application which change the background color every 10 seconds, there will be a distortion (jump) in the encoded video every 10 seconds.

**Kernel:**
I am using the following kernel source:

http://git.freescale.com/git/cgit.cgi/imx/linux-2.6-imx.git/tag/?id=rel_imx_3.14.28_1.0.0_ga

Is that the stable/official branch to use?

I also suspect DTB. I have ported the VPU/IPU/GPU sections of sabresd reference boards which doesn't lead to any improvement. Sadly, Ka-Ro doesn't provide DTB for kernel 3.10/3.14 and the only available DTB is for 3.16.

**MPEGTS:**
At first I too suspected the network streaming and MPEGTS, but note that the jumps only appears when I output to `imxg2dvideosink` (instead of `imxipuvideosink`). Also, the same jumps are also present when using `filesink`. These two can rule out the streaming issue.

**Hardware:**
I also suspected the hardware (e.g. whether the track for CSI clock is too close to DISP pixel) but again, as the distortion only happens for `imxg2dvideosink` and not `imxipuvideosink`, I ruled that out too.

**Comment by dv1** [comment]
"I have ported the VPU/IPU/GPU sections of sabresd reference boards which doesn't lead to any improvement." What do you mean by that, exactly? Are you referring to kernel patches?

**Comment by linux4kix** [comment]
dv1, just asked that I test this on my HB2 with an OV5640 mipi/csi camera.  I ran the above tests without any glitching or problems at all.    You are more than welcome to test against our iMX6 kernel that supports many of the various iMX6 based board variants, https://github.com/SolidRun/linux-fslc  You will basically just need to drop in your device-tree files if you are using a stock 3.14.28 fsl kernel.  You are also welcome to test our debian images here,  https://images.solid-build.xyz/IMX6/Debian/

Those images will require your boards u-boot, and drop the device-tree file in /boot/

**Comment by nickaein** [comment]
Oopsie. I meant the VPU/IPU/GPU sections in *DTB (Device tree)*.

**Comment by dv1** [comment]
Any updates on this? Otherwise I close. This seems very much like a devicetree/kernel issue.
