### ISSUE TITLE
imxv4l2videosrc frame rate issue

### ISSUE THREAD

**Issue by akhudosh** [Freescale/gstreamer-imx#72]
imxv4l2videosrc has fps-n property set to 30 as a default value. That value stays constant unless changed manually, regardless of the real source FPS. In Gstreamer-0.10 tvsrc had code which autodetected the input source standard and set fps-n accordingly

**Comment by dv1** [comment]
I've added code that looks up the standard and uses its framerate. It also looks up which framerate the hardware is actually using. I could only test it with an ov5642 which has no standard settings. Please try out the latest commit.

**Comment by akhudosh** [comment]
I have tried the latest commit. Apparently mxc_v4l2_capture driver does not handle ENUMSTD ioctl correctly. It just returns the current standard field value, and frameperiod is never changed in the code from the default value of 30/1

**Comment by dv1** [comment]
Commit aa50ca9048de3db1e65daf67e5764428faeaafb2 reflects this, and simplifies the fps detection as a consequence of this driver limitation. Reopen if there are still problems

**Comment by akhudosh** [comment]
It did the trick, PAL signals are encoded correctly now
