### ISSUE TITLE
imxv4l2src does not handled interlaced content properly

### ISSUE THREAD

**Issue by akhudosh** [Freescale/gstreamer-imx#77]
The pipeline gst-launch-1.0 imxv4l2videosrc ! imxipuvideotransform deinterlace=1 ! imxgd2videosink provides the same interlaced image as the pipeline without imxipuvideotransform.

If imxv4l2videosrc is replaced with imxv4l2src (NXP plugin), the resulting image is properly deinterlaced.

**Comment by dv1** [comment]
Commit 4d2d0bc019ec28692918478fa2c66627dc9d9c44 adds a workaround for TV input. Does this fix the problem for you?

**Comment by akhudosh** [comment]
Yes, it fixed deinterlacing
