### ISSUE TITLE
IPU task crash on gst-reconfigure-event (valve drop=true)

### ISSUE THREAD

**Issue by dierberg** [Freescale/gstreamer-imx#78]
Hello,

we are using the imx ipu (version 0.12.0) with gst valve. when valve property "drop" is changed on a playing pipeline the ipu reports:
"imx-ipuv3 2400000.ipu: ERR:[0x86440c00]-no:0x110 "wait_for_comp_timeout" " and got into big trouble. I assume that the reconfigure event is the reason, it is send upstream (at sinkpad) when the drop property of valve changes: http://gstreamer.freedesktop.org/data/doc/gstreamer/head/gstreamer/html/GstEvent.html#gst-event-new-reconfigure 

patching gstvalve.c may help but seems to be not a good resolution:

diff --git a/plugins/elements/gstvalve.c b/plugins/elements/gstvalve.c
index 23ffa1c..0c85b40 100644
--- a/plugins/elements/gstvalve.c
+++ b/plugins/elements/gstvalve.c
@@ -140,7 +140,6 @@ gst_valve_set_property (GObject * object,
   switch (prop_id) {
     case PROP_DROP:
       g_atomic_int_set (&valve->drop, g_value_get_boolean (value));
-      gst_pad_push_event (valve->sinkpad, gst_event_new_reconfigure ());
       break;
     default:
       G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
--

**Comment by dierberg** [comment]
May be there is a relation to issue #32 ?

**Comment by dv1** [comment]
I presume that drop was initially set to FALSE in the valve?

I ran this simple test, and I did not see the problem:

	#include <iostream>
	#include <gst/gst.h>


	int main(int argc, char *argv[])
	{
		gst_init(&argc, &argv);

		GstElement *pipeline = gst_parse_launch("videotestsrc ! video/x-raw,format=RGB ! imxipuvideotransform ! video/x-raw,format=I420 ! valve name=test-valve drop=false ! fakesink sync=true ", NULL);
		GstElement *valve = gst_bin_get_by_name(GST_BIN(pipeline), "test-valve");

		gst_element_set_state (pipeline, GST_STATE_PLAYING);
		std::cerr << "Started\n";

		g_usleep(1000000 * 3);
		std::cerr << "Switching\n";
		g_object_set(G_OBJECT(valve), "drop", gboolean(TRUE), NULL);
		std::cerr << "Switched\n";

		g_usleep(1000000 * 3);
		gst_element_set_state (pipeline, GST_STATE_NULL);
		std::cerr << "Stopped\n";

		gst_object_unref(GST_OBJECT(valve));
		gst_object_unref(GST_OBJECT(pipeline));

		return 0;
	}

This is with gstreamer-imx 0.12.0 , linux-imx 3.14.28 , on a nitrogen6x (i.MX6 quad). Yocto Jethro, GStreamer 2.0.

**Comment by dierberg** [comment]
I even cant reproduce this bug with 0.12. Sorry, we used 0.10 before...
