### ISSUE TITLE
ios/safari cannot play hls segments encoded by imxvpuenc_h264

### ISSUE THREAD

**Issue by aultimus** [Freescale/gstreamer-imx#80]
Potentially related to https://github.com/Freescale/gstreamer-imx/issues/63

ios fails to play hls playlists composed of ts segments produced by the imxvpuenc_h264 plugin. 

hls playlists composed of segments produced by the software encoder (x264enc) work on ios.

### SW Encoded example (plays in safari)

pipeline to produce SW encoded ts segments
```
gst-launch-1.0 -e v4l2src ! x264enc ! h264parse ! 'video/x-h264,profile=constrained-baseline' ! h264parse ! mpegtsmux ! multifilesink next-file=2 location="%05d.ts"
```

example SW encoded segment

https://s3-eu-west-1.amazonaws.com/cocoon-live-streaming/ios_example/sw/00001.ts

example playlist of SW encoded segment - plays in safari

https://s3-eu-west-1.amazonaws.com/cocoon-live-streaming/ios_example/sw/playlist.m3u8

### HW Encoded example (does not play in safari)
pipeline to produce HW encoded ts segments
```
gst-launch-1.0 -e imxv4l2videosrc imx-capture-mode=3 ! imxipuvideotransform ! imxvpuenc_h264 bitrate=700 idr-interval=90 ! mpegtsmux ! multifilesink next-file=2 location="%05d.ts"
```

example HW encoded segment

https://s3-eu-west-1.amazonaws.com/cocoon-live-streaming/ios_example/hw/00992.ts

example playlist of HW encoded segment - does not play in safari

https://s3-eu-west-1.amazonaws.com/cocoon-live-streaming/ios_example/hw/playlist.m3u8

EDIT:
```
$ gst-inspect-1.0 imxvpuenc_h264 | grep Version
Version                  0.12.0
```

**Comment by willnewton** [comment]
This should be fixed by the fix to https://github.com/Freescale/libimxvpuapi/issues/7
