### ISSUE TITLE
imxvpuenc_h264 : Forcing output framerate

### ISSUE THREAD

**Issue by fcoiffie** [Freescale/gstreamer-imx#83]
I am a user of gstreamer-0.10 on a i.MX6 platform and used 'vpuenc' feature to encode h264 video.
With 'vpuenc', options was available to force encoding framerate (for example: force-framerate=1 'framerate-nu=25).
(Used command: gst-launch-0.10 -e -v imxv4l2src capture-mode=0 fps-n=30 device=/dev/video0 ! vpuenc codec=avc force-framerate=1 framerate-nu=25 ! rtph264pay ! udpsink host=192.168.1.2 port=3000 sync=false)

Unfortunately, in gstreamer-1.0, the command to encode video ('imxvpuenc_h264') doesn't provide an option to force framerate at encoding.

(Command: gst-launch-1.0 -e -v imxv4l2videosrc capture-mode=0 device=/dev/video0 ! imxvpuenc_h264 bitrate=3500 ! rtph264pay ! udpsink host=192.168.1.2 port=3000 sync=false)

I already tried to force framerate of encoding using caps, and by recompiling feature to force 'framerate' in the source code, but framerate at encoding stay a video source framerate.

Is it possible to make encoding framerate accessible again for 'imxvpuenc_h264' ?

**Comment by dv1** [comment]
I am not familiar with this feature of the 0.10 plugins. If the incoming data used 30 Hz, but you set force-framerate=1 framerate-nu=25 , what happened? All the original timestmaps got thrown away and new ones based on the 25 fps got generated?

**Comment by fcoiffie** [comment]
I believed it was done by VPU itself (or libfslvpuwrapper).
But, in fact, it was directly done by the Gstreamer plugin 'vpuenc' with the following code:
```
static GstBuffer *
gst_vpuenc_preencode_process (GstVpuEnc * vpuenc, GstBuffer * buffer)
{
  GstBuffer *ret = buffer;
  if (buffer) {
    vpuenc->vpu_stat.in_cnt++;
    if ((vpuenc->options.force_framerate)
        && (GST_BUFFER_TIMESTAMP_IS_VALID (buffer))) {
      GstClockTime expect_ts =
          vpuenc->segment_start + (vpuenc->frame_cnt +
          1) * vpuenc->frame_interval;
      if (GST_BUFFER_TIMESTAMP (buffer) < expect_ts) {
        GST_DEBUG ("Drop frame since force framerate control");
        gst_buffer_unref (buffer);
        ret = NULL;
        goto bail;
      }
    }
    vpuenc->frame_cnt++;
  }

bail:
  return ret;
}
```

**Comment by dv1** [comment]
Something like this is actually not the encoder's task. The 0.10 plugins could do this because they completely threw away incoming timestamps (which does cause many problems in other situations). I recommend you look at the videoparse element. Here is an example of how to retimestamp a 25 Hz video signal to 30 Hz timestamps:

    gst-launch-1.0 videotestsrc ! "video/x-raw, framerate=25/1" ! videoparse framerate=30/1 ! "video/x-raw" ! fakesink sync=true silent=false -v

**Comment by fcoiffie** [comment]
I have solved my issue by using 'videorate' gstreamer-1.0 plugin.

This issue can be closed.

Thanks for your help !

**Comment by venkatesh-kuppan** [comment]
is it possible to generate/dispay 1 frame per 10 seconds using any of the current GStreamer plugins? I want to perform some testing where I insert 1 video frame every 10 seconds. The rest time, I display some other kind of dummy information, until the 1 video frame is available
