### ISSUE TITLE
glib object name conflict with gst1.0-fsl-plugin

### ISSUE THREAD

**Issue by dierberg** [Freescale/gstreamer-imx#86]
GstImxCompositorPad conflicts with the same named object in gst1.0-fsl-plugin.  Please rename it.

**Comment by dv1** [comment]
OK, thanks for the info. However, it is not recommended to mix gst1.0-fsl-plugin and gstreamer-imx, partially because gst1.0-fsl-plugin introduces its own demuxers and parsers, which have caused compatibility problems in the past.

**Comment by dv1** [comment]
Renamed in git master. Conflicts should be resolved.
