### ISSUE TITLE
appsrc  with  imxvpuenc_h264  pipline fails with reason:  not-negotiated (-4)

### ISSUE THREAD

**Issue by hannesharms** [Freescale/gstreamer-imx#89]
I am trying to start the following pipeline:

`appsrc name=my_src ! immxipuvideotransform ! imxvpuenc_h264 bitrate=1000 ! rtph264pay ! fakesink`
 
The appsrc caps is set inside the application with:

`gst_caps_new_simple("video/x-raw",
            "format", G_TYPE_STRING, "BGR",
            "width", G_TYPE_INT, 640,
            "height", G_TYPE_INT, 480,
            "interlace-mode", G_TYPE_STRING, "progressiv",
            "framerate", GST_TYPE_FRACTION, 10, 1, 
            "pixel-aspect-ratio", GST_TYPE_FRACTION, 1, 1,
            nullptr);`

When calling `gst_app_src_push_sample(GST_APP_SRC_CAST(appsrc_), sample);`
I get the following error:

`GST: bus: Internal data flow error.
 GST: debug: gstreamer1.0/1.6.3-r0/gstreamer-1.6.3/libs/gst/base/gstbasesrc.c(2943):  gst_base_src_loop (): /GstPipeline:pipeline0/GstAppSrc:source:
streaming task paused, reason not-negotiated (-4)`

When changing the pipeline to a CPU version like this:

`appsrc name=my_src ! videoconvert !  x264enc !  video/x-h264, profile=baseline ! rtph264pay ! fakesink` the stream is working.

Are there any special requirements I missed to link appsrc with imx-plugins ?

**Comment by nrmmota** [comment]
I recently came across a similar error. The error was due to a audio or
video codec from a buck bunny stream that was not being linked somewhere.
Try using GST_DEBUG="*:2" to get more debug log.

2016-03-16 17:56 GMT+00:00 hannesharms <notifications@github.com>:

**Comment by hannesharms** [comment]
The problem was not related to any video codec problem. 
With `GST_DEBUG="*:2"`` I found out that ` imxvpuenc_h264` was completely missing on the system, don’t know why.  After recompiling whole operating system with bitbake the pipline is running. 
So in my case appsrc is working in combination with imx plugins now.
