### ISSUE TITLE
Display artifacts with vpudec and eglvivisink

### ISSUE THREAD

**Issue by ddejean** [Freescale/gstreamer-imx#90]
Bug
---
When decoding and displaying a VP8 stream with a weird resolution using the VPU and the eglvivsink, the resulting picture is full of color artifacts.

![device-2016-03-23-082051](https://cloud.githubusercontent.com/assets/1169197/13978507/e9da146e-f0d1-11e5-8308-0a4dcf031a70.png)

The pipeline we use is:
```
udpsrc port=5000 caps="application/x-rtp, media=video, payload=100, clock-rate=90000, encoding-name=VP8-DRAFT-IETF-01" ! decodebin name=dec dec. ! queue ! imxeglvivsink"
```

After some investigations, here are the results we found:

- The stream has a resolution of 1264x711,
- The physical buffer format received in the egl sink is GL_VIV_I420,
- Still in the sink, theomputed size with stride and offset leads to a resolution of 1264x720,
- When an incoming stream has a classic resolution (eg 1280x720) it displays correctly.

Reproduce
--------------
You'll find below a network capture that you can replay to trigger the issue. We're working on Android but I think you could test think on a linux BSP

[rtp.pcap.zip](https://github.com/Freescale/gstreamer-imx/files/185543/rtp.pcap.zip)

On our platform, we can trigger the bug with this capture file using the following pipeline:
```
filesrc location=/path/to/rtp.pcap ! pcapparse dst-port=5000 caps="application/x-rtp, media=video, payload=100, clock-rate=90000, encoding-name=VP8-DRAFT-IETF-01" ! decodebin ! imxeglvivsink"
```

I'll post the results of my investigations as comments. If you need more information, do not hesitate.

**Comment by dv1** [comment]
What is the resolution of the display itself? I am running this with a 1920x1080 display (32bpp), and I do not see the artifact.

**Comment by ddejean** [comment]
The display I use is 1920x1080 but the browser has media constraints that force him to reduce the size of the capture before sending it. It works with incoming streams when they have a 1080p or 720p resolution, it works with resolutions multiple of 16 pixels ...

I'm using the imxeglvivsink with egl/android platform at version 0.12.0, but the bug is visible with the master too.

IMO you won't be able to trigger the bug without any strange video dimension. That's why I provided the cap sample :)

**Comment by dv1** [comment]
As discussed in IRC, this appears to be a GPU driver bug, not a gstreamer-imx one. Closing this. Reopen if this turns out to be incorrect.
