### ISSUE TITLE
Support for getting bayer image from imxv4l2videosrc plugin

### ISSUE THREAD

**Issue by gunasekaran7** [Freescale/gstreamer-imx#92]
I have modified mxc_v4l_capture.c to get the bayer image using V4l2-utils. I am using opencv to convert the bayer image to RGB. With that, I am able to achieve only 8 fps (Mt9v022 image sensor 640x480 running @ 25MHz pixclk). I am thinking of using gstreamer's bayer2rgb plugin to do conversion on the fly. I need some guidance on how to change src/video/v4l2src.c file in the repository to get bayer image out of the imxv4l2videosrc plugin.

**Comment by jdepedro-digi** [comment]
I have faced the same problem using a camera based on ov5647 sensor, which can only output raw bayer images. I think the main issue is that right now imxv4l2videosrc only has a src Pad Template with capabilites 'video/x-raw', but cannot be used as a src outputting 'video/x-bayer'.
In my opinion this element should be modified to also allow 'video/x-bayer' format, and thus be able to link it to the bayer2rgb element.

**Comment by dv1** [comment]
I'll try to get an ov5647 to be able to test this. This is also interesting for hw-accelerated bayer2rgb which somebody has implemented for imx in the past AFAIK.

**Comment by jdepedro-digi** [comment]
The raspberry pi camera uses the ov5647.
Can you provide more details about hw-accelerated bayer2rgb? I am pretty sure the i.MX6 IPU is not able to perform the debayering. I have been reading around about using shaders and letting the GPU do the work. I am currently trying to make that work, so any details would be appreciated.
