### ISSUE TITLE
VIDIOC_DQBUF failed: Timer expired error.  

### ISSUE THREAD

**Issue by cottrelld** [Freescale/gstreamer-imx#96]
I just updated to master, previously i was using master from 11/2015.  Now I frequently get internal data flow errors after 20-30 seconds or so. System memory doesn't appear to be full.  The error is below, and I've attached some longer output in 2 similar runs.

[imx-crash-logs.zip](https://github.com/Freescale/gstreamer-imx/files/253184/imx-crash-logs.zip)

0:01:25.760855571 23609 0xb4911860 ERROR      imxv4l2bufferpool v4l2_buffer_pool.c:247:gst_imx_v4l2_buffer_pool_acquire_buffer:<imxv4l2bufferpool0> VIDIOC_DQBUF failed: Timer expired
0:01:25.761402931 23609 0xb4911860 WARN                 basesrc gstbasesrc.c:2943:gst_base_src_loop:<imxv4l2videosrc0> error: Internal data flow error.
## bus_cb received error!

---

bus_cb error=/home/elarm/yocto/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0/1.4.5-r0/git/libs/gst/base/gstbasesrc.c(2943): gst_base_src_loop (): /GstPipeline:pipeline/GstImxV4l2VideoSrc:imxv4l2videosrc0:
## streaming task paused, reason error (-5)!

ERROR: from element /GstPipeline:pipeline/GstImxV4l2VideoSrc:imxv4l2videosrc0: Internal data flow error.
Additional debug info:
/home/elarm/yocto/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/gstreamer1.0/1.4.5-r0/git/libs/gst/base/gstbasesrc.c(2943): gst_base_src_loop (): /GstPipeline:pipeline/GstImxV4l2VideoSrc:imxv4l2videosrc0:
streaming task paused, reason error (-5)
Bus error

**Comment by cottrelld** [comment]
I narrowed it down and found the commit that causes the crash.

https://github.com/Freescale/gstreamer-imx/commit/af76b354ff5088fd983790da34c4b3d2574c23df

**if (!(copy->region)) // TODO: is this check correct?**

this was changed to:

**if (copy->region)** 

Rolling back imx to the commit just before this makes everything work fine.  After using this commit, gstreamer crashes.

-David

**Comment by dv1** [comment]
After several tries with many v4l pipelines, I still canoot reconstruct this problem. The check from af76b35 is consistent with how other metas behave. I'd need a lot more info, like the exact structure of the pipeline (a dot dump would be useful - look up GST_DEBUG_DUMP_DOT_DIR and GST_DEBUG_BIN_TO_DOT_FILE). Ideally also try to run the pipeline with gdb, and check the backtrace.

**Comment by cottrelld** [comment]
Ok, I'll get that within the next few days.  Thanks.

-David
