### ISSUE TITLE
Vsync causes flicker in background application

### ISSUE THREAD

**Issue by msmithatcarmanahsigns** [Freescale/gstreamer-imx#97]
Hi, first off thanks for all your hard work on this decoder.  It generally works well and I see there have been many fixes since I last updated my version.

I tested the new vsync functionality, and it works in fullscreen.  The issue is that my system runs a Qt application that displays a video in the top corner of the screen.  When vsync is enabled, the entire application flickers.

Is there a work around for this problem?

Thanks again

Marlon

**Comment by dv1** [comment]
Unfortunately I do not see any. vsync control implies that the entire screen is affected. If you have a composition (like you have with your application with a video in the top corner), then the application must handle vsync by itself somehow. One possibility would be to use the Vivante direct textures to display video frames in a GL qwidget. If you are using QtMultimedia it should already have that.

**Comment by angelobt** [comment]
Hi,

I have solved setting vyres of fb0 as yres * 2

my fb is 800x400 and i set virtual size to 800x960

fbset -fb /dev/fb0 -g 800 480 800 960 32 "800x480-60"

In this way double buffer has been already set and gstreamer does not need to reset the fb

**Comment by dv1** [comment]
Thanks, noted, and added to the FAQ.

**Comment by msmithatcarmanahsigns** [comment]
So I've been trying to get this to work and I think I'm close.  When I first run my application, video plays with vsync but the application is black.  The next time I run it, the application constantly flickers while the video is playing.  If I reconfigure the framebuffer as angelobt suggested, sometimes everything works correctly and sometimes the application constantly flickers while video is playing.

Do you guys have any ideas?
