### ISSUE TITLE
imxipuvideosink with use-vsync=true cause flash on fb

### ISSUE THREAD

**Issue by angelobt** [Freescale/gstreamer-imx#98]
I found a bug about imxipuvideosink when using "use-vsync=true".

I have two fb:
fb0 -> used for video (gstreamer)
fb1 -> used for QT GUI
also if fb1 is "solid" and set over fb0, when I launch a pipeline with "use-vsync=true" I see a flash on the GUI (for about 300 ms I see fb0). Same behaviour when pipeline stops.

Could you help to solve this issue ?

Thanks

**Comment by angelobt** [comment]
Hi,

I have solved setting vyres of fb0 as yres * 2

fbset -fb /dev/fb0 -g 800 480 800 960 32 "800x480-60"

In this way double buffer has been already set and gstreamer does not need to reset the fb

**Comment by dv1** [comment]
Ah, interesting. The reconfiguration of the framebuffer can indeed cause such a flicker. If this works stable for you, I will add it to the FAQ.

**Comment by angelobt** [comment]
seems stable
