### ISSUE TITLE
Green band at the bottom of deinterlaced image with imxv4l2videosink

### ISSUE THREAD

**Issue by akhudosh** [Freescale/gstreamer-imx#99]
The pipeline
gst-launch-1.0 imxv4l2videosrc ! imxipuvideotransform deinterlace=1 ! imxeglvivsink
results in the image with a green band a few pixel high at the bottom of the video image.
The same pipeline with imxv4l2src does not create this green band. Also, after imxv4l2src pipeline is run, the green band does not appear even with imxv4l2videosrc.

**Comment by dv1** [comment]
Can you run this with the -v flag and with `GST_DEBUG` set to `2,*imx*:9` ? I need this information for a replication attempt.

**Comment by akhudosh** [comment]
Both picture and the log are attached
![20160726_082300](https://cloud.githubusercontent.com/assets/6834145/17120316/ba219554-530e-11e6-8364-0406311b6eb8.jpg)
[debug.zip](https://github.com/Freescale/gstreamer-imx/files/382638/debug.zip)

**Comment by dv1** [comment]
I finally got hardware where I can reconstruct this. Right now I have no clue why this happens, but I strongly suspect a problem in the IPU driver. It only happens with certain formats, but unfortunately, it does happen fairly reliably with I420 input. On the bright side, it actually seems to be possible to let imxv4l2videosrc use some other format such a UYVY. And UYVY did not exhibit the green band.

**Comment by dv1** [comment]
I added UYVY support to imxv4l2videosrc. Please retry with the latest master.

**Comment by akhudosh** [comment]
Seems to be fixed, no longer appears on my hardware.
